/* Generated by R4LContractGen. Do not edit. */
#ifndef R4NV_R4L_BINDING_H
#define R4NV_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4NvDeviceProfile {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t copy_class;
    uint32_t rm_release;
    uint32_t command_abi;
    uint32_t adapter_id;
    uint32_t flags;
    uint64_t device_generation;
    uint64_t reset_generation;
} R4NvDeviceProfile;
_Static_assert(sizeof(R4NvDeviceProfile) == 48u, "R4NvDeviceProfile size mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, version) == 0u, "R4NvDeviceProfile.version offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, size) == 4u, "R4NvDeviceProfile.size offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, vendor_id) == 8u, "R4NvDeviceProfile.vendor_id offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, copy_class) == 12u, "R4NvDeviceProfile.copy_class offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, rm_release) == 16u, "R4NvDeviceProfile.rm_release offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, command_abi) == 20u, "R4NvDeviceProfile.command_abi offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, adapter_id) == 24u, "R4NvDeviceProfile.adapter_id offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, flags) == 28u, "R4NvDeviceProfile.flags offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, device_generation) == 32u, "R4NvDeviceProfile.device_generation offset mismatch");
_Static_assert(offsetof(R4NvDeviceProfile, reset_generation) == 40u, "R4NvDeviceProfile.reset_generation offset mismatch");

typedef struct R4NvFeatures {
    uint32_t version;
    uint32_t size;
    uint32_t command_abi;
    uint32_t features;
    uint32_t copy_class;
    uint32_t gpu_address_bits;
    uint32_t max_command_words;
    uint32_t reserved;
    uint64_t max_copy_bytes;
    uint64_t max_rows;
} R4NvFeatures;
_Static_assert(sizeof(R4NvFeatures) == 48u, "R4NvFeatures size mismatch");
_Static_assert(offsetof(R4NvFeatures, version) == 0u, "R4NvFeatures.version offset mismatch");
_Static_assert(offsetof(R4NvFeatures, size) == 4u, "R4NvFeatures.size offset mismatch");
_Static_assert(offsetof(R4NvFeatures, command_abi) == 8u, "R4NvFeatures.command_abi offset mismatch");
_Static_assert(offsetof(R4NvFeatures, features) == 12u, "R4NvFeatures.features offset mismatch");
_Static_assert(offsetof(R4NvFeatures, copy_class) == 16u, "R4NvFeatures.copy_class offset mismatch");
_Static_assert(offsetof(R4NvFeatures, gpu_address_bits) == 20u, "R4NvFeatures.gpu_address_bits offset mismatch");
_Static_assert(offsetof(R4NvFeatures, max_command_words) == 24u, "R4NvFeatures.max_command_words offset mismatch");
_Static_assert(offsetof(R4NvFeatures, reserved) == 28u, "R4NvFeatures.reserved offset mismatch");
_Static_assert(offsetof(R4NvFeatures, max_copy_bytes) == 32u, "R4NvFeatures.max_copy_bytes offset mismatch");
_Static_assert(offsetof(R4NvFeatures, max_rows) == 40u, "R4NvFeatures.max_rows offset mismatch");

typedef struct R4NvCopy {
    uint32_t version;
    uint32_t size;
    uint64_t source;
    uint64_t target;
    uint64_t bytes;
    uint64_t semaphore;
    uint32_t copy_class;
    uint32_t rows;
    uint32_t source_pitch;
    uint32_t target_pitch;
    uint32_t point;
    uint32_t flags;
} R4NvCopy;
_Static_assert(sizeof(R4NvCopy) == 64u, "R4NvCopy size mismatch");
_Static_assert(offsetof(R4NvCopy, version) == 0u, "R4NvCopy.version offset mismatch");
_Static_assert(offsetof(R4NvCopy, size) == 4u, "R4NvCopy.size offset mismatch");
_Static_assert(offsetof(R4NvCopy, source) == 8u, "R4NvCopy.source offset mismatch");
_Static_assert(offsetof(R4NvCopy, target) == 16u, "R4NvCopy.target offset mismatch");
_Static_assert(offsetof(R4NvCopy, bytes) == 24u, "R4NvCopy.bytes offset mismatch");
_Static_assert(offsetof(R4NvCopy, semaphore) == 32u, "R4NvCopy.semaphore offset mismatch");
_Static_assert(offsetof(R4NvCopy, copy_class) == 40u, "R4NvCopy.copy_class offset mismatch");
_Static_assert(offsetof(R4NvCopy, rows) == 44u, "R4NvCopy.rows offset mismatch");
_Static_assert(offsetof(R4NvCopy, source_pitch) == 48u, "R4NvCopy.source_pitch offset mismatch");
_Static_assert(offsetof(R4NvCopy, target_pitch) == 52u, "R4NvCopy.target_pitch offset mismatch");
_Static_assert(offsetof(R4NvCopy, point) == 56u, "R4NvCopy.point offset mismatch");
_Static_assert(offsetof(R4NvCopy, flags) == 60u, "R4NvCopy.flags offset mismatch");

typedef struct R4NvDriverProfile {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t copy_class;
    uint32_t rm_release;
    uint32_t command_abi;
    uint32_t reserved0;
    uint32_t reserved1;
} R4NvDriverProfile;
_Static_assert(sizeof(R4NvDriverProfile) == 32u, "R4NvDriverProfile size mismatch");
_Static_assert(offsetof(R4NvDriverProfile, version) == 0u, "R4NvDriverProfile.version offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, size) == 4u, "R4NvDriverProfile.size offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, vendor_id) == 8u, "R4NvDriverProfile.vendor_id offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, copy_class) == 12u, "R4NvDriverProfile.copy_class offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, rm_release) == 16u, "R4NvDriverProfile.rm_release offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, command_abi) == 20u, "R4NvDriverProfile.command_abi offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, reserved0) == 24u, "R4NvDriverProfile.reserved0 offset mismatch");
_Static_assert(offsetof(R4NvDriverProfile, reserved1) == 28u, "R4NvDriverProfile.reserved1 offset mismatch");

typedef struct R4NvCopyBlock {
    uint32_t enabled;
    uint32_t width;
    uint32_t height;
    uint32_t x;
    uint32_t y;
    uint32_t log2_gobs;
} R4NvCopyBlock;
_Static_assert(sizeof(R4NvCopyBlock) == 24u, "R4NvCopyBlock size mismatch");
_Static_assert(offsetof(R4NvCopyBlock, enabled) == 0u, "R4NvCopyBlock.enabled offset mismatch");
_Static_assert(offsetof(R4NvCopyBlock, width) == 4u, "R4NvCopyBlock.width offset mismatch");
_Static_assert(offsetof(R4NvCopyBlock, height) == 8u, "R4NvCopyBlock.height offset mismatch");
_Static_assert(offsetof(R4NvCopyBlock, x) == 12u, "R4NvCopyBlock.x offset mismatch");
_Static_assert(offsetof(R4NvCopyBlock, y) == 16u, "R4NvCopyBlock.y offset mismatch");
_Static_assert(offsetof(R4NvCopyBlock, log2_gobs) == 20u, "R4NvCopyBlock.log2_gobs offset mismatch");

typedef struct R4NvCopyLayout {
    R4NvCopy copy;
    R4NvCopyBlock source_block;
    R4NvCopyBlock target_block;
} R4NvCopyLayout;
_Static_assert(sizeof(R4NvCopyLayout) == 112u, "R4NvCopyLayout size mismatch");
_Static_assert(offsetof(R4NvCopyLayout, copy) == 0u, "R4NvCopyLayout.copy offset mismatch");
_Static_assert(offsetof(R4NvCopyLayout, source_block) == 64u, "R4NvCopyLayout.source_block offset mismatch");
_Static_assert(offsetof(R4NvCopyLayout, target_block) == 88u, "R4NvCopyLayout.target_block offset mismatch");

typedef struct R4NvDigest {
    uint64_t word0;
    uint64_t word1;
    uint64_t word2;
    uint64_t word3;
} R4NvDigest;
_Static_assert(sizeof(R4NvDigest) == 32u, "R4NvDigest size mismatch");
_Static_assert(offsetof(R4NvDigest, word0) == 0u, "R4NvDigest.word0 offset mismatch");
_Static_assert(offsetof(R4NvDigest, word1) == 8u, "R4NvDigest.word1 offset mismatch");
_Static_assert(offsetof(R4NvDigest, word2) == 16u, "R4NvDigest.word2 offset mismatch");
_Static_assert(offsetof(R4NvDigest, word3) == 24u, "R4NvDigest.word3 offset mismatch");

typedef struct R4NvShaderKey {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t graphics_class;
    uint32_t shader_model;
    uint32_t rm_release;
    uint32_t command_abi;
    uint32_t shader_abi;
    uint32_t resource_abi;
    uint32_t input_format;
    uint32_t output_format;
    uint64_t driver_build;
    R4NvDigest device_uuid;
    R4NvDigest pipeline_state;
} R4NvShaderKey;
_Static_assert(sizeof(R4NvShaderKey) == 120u, "R4NvShaderKey size mismatch");
_Static_assert(offsetof(R4NvShaderKey, version) == 0u, "R4NvShaderKey.version offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, size) == 4u, "R4NvShaderKey.size offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, vendor_id) == 8u, "R4NvShaderKey.vendor_id offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, device_id) == 12u, "R4NvShaderKey.device_id offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, graphics_class) == 16u, "R4NvShaderKey.graphics_class offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, shader_model) == 20u, "R4NvShaderKey.shader_model offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, rm_release) == 24u, "R4NvShaderKey.rm_release offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, command_abi) == 28u, "R4NvShaderKey.command_abi offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, shader_abi) == 32u, "R4NvShaderKey.shader_abi offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, resource_abi) == 36u, "R4NvShaderKey.resource_abi offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, input_format) == 40u, "R4NvShaderKey.input_format offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, output_format) == 44u, "R4NvShaderKey.output_format offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, driver_build) == 48u, "R4NvShaderKey.driver_build offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, device_uuid) == 56u, "R4NvShaderKey.device_uuid offset mismatch");
_Static_assert(offsetof(R4NvShaderKey, pipeline_state) == 88u, "R4NvShaderKey.pipeline_state offset mismatch");

typedef struct R4NvShaderInfo {
    uint32_t version;
    uint32_t size;
    uint32_t profile;
    uint32_t stage;
    uint32_t shader_model;
    uint32_t registers;
    uint32_t code_bytes;
    uint32_t instructions;
    uint32_t scratch_bytes;
    uint32_t stack_bytes;
    uint32_t header_bytes;
    uint32_t resource_abi;
    uint32_t max_warps_per_sm;
    uint32_t reserved;
    R4NvDigest compiler_id;
} R4NvShaderInfo;
_Static_assert(sizeof(R4NvShaderInfo) == 88u, "R4NvShaderInfo size mismatch");
_Static_assert(offsetof(R4NvShaderInfo, version) == 0u, "R4NvShaderInfo.version offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, size) == 4u, "R4NvShaderInfo.size offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, profile) == 8u, "R4NvShaderInfo.profile offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, stage) == 12u, "R4NvShaderInfo.stage offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, shader_model) == 16u, "R4NvShaderInfo.shader_model offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, registers) == 20u, "R4NvShaderInfo.registers offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, code_bytes) == 24u, "R4NvShaderInfo.code_bytes offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, instructions) == 28u, "R4NvShaderInfo.instructions offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, scratch_bytes) == 32u, "R4NvShaderInfo.scratch_bytes offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, stack_bytes) == 36u, "R4NvShaderInfo.stack_bytes offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, header_bytes) == 40u, "R4NvShaderInfo.header_bytes offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, resource_abi) == 44u, "R4NvShaderInfo.resource_abi offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, max_warps_per_sm) == 48u, "R4NvShaderInfo.max_warps_per_sm offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, reserved) == 52u, "R4NvShaderInfo.reserved offset mismatch");
_Static_assert(offsetof(R4NvShaderInfo, compiler_id) == 56u, "R4NvShaderInfo.compiler_id offset mismatch");

typedef struct R4NvShaderView {
    R4NvShaderInfo info;
    uint64_t header_address;
    uint64_t code_address;
} R4NvShaderView;
_Static_assert(sizeof(R4NvShaderView) == 104u, "R4NvShaderView size mismatch");
_Static_assert(offsetof(R4NvShaderView, info) == 0u, "R4NvShaderView.info offset mismatch");
_Static_assert(offsetof(R4NvShaderView, header_address) == 88u, "R4NvShaderView.header_address offset mismatch");
_Static_assert(offsetof(R4NvShaderView, code_address) == 96u, "R4NvShaderView.code_address offset mismatch");

typedef struct R4NvImageView {
    uint32_t version;
    uint32_t size;
    uint32_t width;
    uint32_t height;
    uint32_t format;
    uint32_t location;
    uint64_t modifier;
    uint64_t byte_length;
    uint64_t pitch;
    uint64_t alignment;
    uint32_t usage;
    uint32_t reserved;
} R4NvImageView;
_Static_assert(sizeof(R4NvImageView) == 64u, "R4NvImageView size mismatch");
_Static_assert(offsetof(R4NvImageView, version) == 0u, "R4NvImageView.version offset mismatch");
_Static_assert(offsetof(R4NvImageView, size) == 4u, "R4NvImageView.size offset mismatch");
_Static_assert(offsetof(R4NvImageView, width) == 8u, "R4NvImageView.width offset mismatch");
_Static_assert(offsetof(R4NvImageView, height) == 12u, "R4NvImageView.height offset mismatch");
_Static_assert(offsetof(R4NvImageView, format) == 16u, "R4NvImageView.format offset mismatch");
_Static_assert(offsetof(R4NvImageView, location) == 20u, "R4NvImageView.location offset mismatch");
_Static_assert(offsetof(R4NvImageView, modifier) == 24u, "R4NvImageView.modifier offset mismatch");
_Static_assert(offsetof(R4NvImageView, byte_length) == 32u, "R4NvImageView.byte_length offset mismatch");
_Static_assert(offsetof(R4NvImageView, pitch) == 40u, "R4NvImageView.pitch offset mismatch");
_Static_assert(offsetof(R4NvImageView, alignment) == 48u, "R4NvImageView.alignment offset mismatch");
_Static_assert(offsetof(R4NvImageView, usage) == 56u, "R4NvImageView.usage offset mismatch");
_Static_assert(offsetof(R4NvImageView, reserved) == 60u, "R4NvImageView.reserved offset mismatch");

typedef struct R4NvImageRequest {
    R4NvImageView view;
    uint32_t uses;
    uint32_t preference;
    uint32_t flags;
    uint32_t reserved;
} R4NvImageRequest;
_Static_assert(sizeof(R4NvImageRequest) == 80u, "R4NvImageRequest size mismatch");
_Static_assert(offsetof(R4NvImageRequest, view) == 0u, "R4NvImageRequest.view offset mismatch");
_Static_assert(offsetof(R4NvImageRequest, uses) == 64u, "R4NvImageRequest.uses offset mismatch");
_Static_assert(offsetof(R4NvImageRequest, preference) == 68u, "R4NvImageRequest.preference offset mismatch");
_Static_assert(offsetof(R4NvImageRequest, flags) == 72u, "R4NvImageRequest.flags offset mismatch");
_Static_assert(offsetof(R4NvImageRequest, reserved) == 76u, "R4NvImageRequest.reserved offset mismatch");

typedef struct R4NvImagePlan {
    uint32_t version;
    uint32_t size;
    uint32_t action;
    uint32_t layout;
    uint32_t reasons;
    uint32_t supported_uses;
    uint64_t modifier;
    uint64_t pitch;
    uint64_t byte_length;
    uint64_t allocation_bytes;
    uint32_t log2_gobs;
    uint32_t reserved;
} R4NvImagePlan;
_Static_assert(sizeof(R4NvImagePlan) == 64u, "R4NvImagePlan size mismatch");
_Static_assert(offsetof(R4NvImagePlan, version) == 0u, "R4NvImagePlan.version offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, size) == 4u, "R4NvImagePlan.size offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, action) == 8u, "R4NvImagePlan.action offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, layout) == 12u, "R4NvImagePlan.layout offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, reasons) == 16u, "R4NvImagePlan.reasons offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, supported_uses) == 20u, "R4NvImagePlan.supported_uses offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, modifier) == 24u, "R4NvImagePlan.modifier offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, pitch) == 32u, "R4NvImagePlan.pitch offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, byte_length) == 40u, "R4NvImagePlan.byte_length offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, allocation_bytes) == 48u, "R4NvImagePlan.allocation_bytes offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, log2_gobs) == 56u, "R4NvImagePlan.log2_gobs offset mismatch");
_Static_assert(offsetof(R4NvImagePlan, reserved) == 60u, "R4NvImagePlan.reserved offset mismatch");

typedef struct R4NvArchitecture {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t chipset;
    uint32_t pci_revision;
    uint32_t pci_domain;
    uint32_t pci_bus;
    uint32_t pci_device;
    uint32_t pci_function;
    uint32_t gpc_count;
    uint32_t tpc_count;
    uint32_t shader_model;
    uint32_t mp_per_tpc;
    uint32_t max_warps_per_mp;
    uint32_t rm_release;
    uint64_t vram_bytes;
    uint64_t va_start;
    uint64_t va_end;
    uint64_t memory_generation;
    uint32_t bind_alignment;
    uint32_t flags;
    uint32_t graphics_class;
    uint32_t compute_class;
    uint32_t copy_class;
    uint32_t gpfifo_class;
} R4NvArchitecture;
_Static_assert(sizeof(R4NvArchitecture) == 120u, "R4NvArchitecture size mismatch");
_Static_assert(offsetof(R4NvArchitecture, version) == 0u, "R4NvArchitecture.version offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, size) == 4u, "R4NvArchitecture.size offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, vendor_id) == 8u, "R4NvArchitecture.vendor_id offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, device_id) == 12u, "R4NvArchitecture.device_id offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, chipset) == 16u, "R4NvArchitecture.chipset offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, pci_revision) == 20u, "R4NvArchitecture.pci_revision offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, pci_domain) == 24u, "R4NvArchitecture.pci_domain offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, pci_bus) == 28u, "R4NvArchitecture.pci_bus offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, pci_device) == 32u, "R4NvArchitecture.pci_device offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, pci_function) == 36u, "R4NvArchitecture.pci_function offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, gpc_count) == 40u, "R4NvArchitecture.gpc_count offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, tpc_count) == 44u, "R4NvArchitecture.tpc_count offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, shader_model) == 48u, "R4NvArchitecture.shader_model offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, mp_per_tpc) == 52u, "R4NvArchitecture.mp_per_tpc offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, max_warps_per_mp) == 56u, "R4NvArchitecture.max_warps_per_mp offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, rm_release) == 60u, "R4NvArchitecture.rm_release offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, vram_bytes) == 64u, "R4NvArchitecture.vram_bytes offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, va_start) == 72u, "R4NvArchitecture.va_start offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, va_end) == 80u, "R4NvArchitecture.va_end offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, memory_generation) == 88u, "R4NvArchitecture.memory_generation offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, bind_alignment) == 96u, "R4NvArchitecture.bind_alignment offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, flags) == 100u, "R4NvArchitecture.flags offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, graphics_class) == 104u, "R4NvArchitecture.graphics_class offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, compute_class) == 108u, "R4NvArchitecture.compute_class offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, copy_class) == 112u, "R4NvArchitecture.copy_class offset mismatch");
_Static_assert(offsetof(R4NvArchitecture, gpfifo_class) == 116u, "R4NvArchitecture.gpfifo_class offset mismatch");

typedef struct R4NvNativeSubmitHeader {
    uint32_t version;
    uint32_t size;
    uint32_t engine_mask;
    uint32_t push_count;
    uint64_t reserved0;
    uint64_t reserved1;
} R4NvNativeSubmitHeader;
_Static_assert(sizeof(R4NvNativeSubmitHeader) == 32u, "R4NvNativeSubmitHeader size mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, version) == 0u, "R4NvNativeSubmitHeader.version offset mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, size) == 4u, "R4NvNativeSubmitHeader.size offset mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, engine_mask) == 8u, "R4NvNativeSubmitHeader.engine_mask offset mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, push_count) == 12u, "R4NvNativeSubmitHeader.push_count offset mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, reserved0) == 16u, "R4NvNativeSubmitHeader.reserved0 offset mismatch");
_Static_assert(offsetof(R4NvNativeSubmitHeader, reserved1) == 24u, "R4NvNativeSubmitHeader.reserved1 offset mismatch");

typedef struct R4NvNativePush {
    uint64_t address;
    uint32_t byte_length;
    uint32_t flags;
} R4NvNativePush;
_Static_assert(sizeof(R4NvNativePush) == 16u, "R4NvNativePush size mismatch");
_Static_assert(offsetof(R4NvNativePush, address) == 0u, "R4NvNativePush.address offset mismatch");
_Static_assert(offsetof(R4NvNativePush, byte_length) == 8u, "R4NvNativePush.byte_length offset mismatch");
_Static_assert(offsetof(R4NvNativePush, flags) == 12u, "R4NvNativePush.flags offset mismatch");

#define R4NV_COMMAND_ABI ((uint32_t)1)
#define R4NV_RM_RELEASE ((uint32_t)570144)
#define R4NV_FEATURE_COPY_LINEAR ((uint32_t)1)
#define R4NV_FEATURE_COPY_ROWS ((uint32_t)2)
#define R4NV_MAX_COMMAND_WORDS ((uint32_t)19)
#define R4NV_STATUS_OK ((int32_t)0)
#define R4NV_FEATURE_COPY_LAYOUT ((uint32_t)4)
#define R4NV_MAX_LAYOUT_COMMAND_WORDS ((uint32_t)37)
#define R4NV_SHADER_ABI ((uint32_t)1)
#define R4NV_SHADER_RESOURCE_ABI ((uint32_t)4)
#define R4NV_SHADER_MODEL_SM86 ((uint32_t)86)
#define R4NV_SHADER_GRAPHICS_CLASS_AMPERE_B ((uint32_t)51095)
#define R4NV_SHADER_CACHE_HEADER_BYTES ((uint32_t)384)
#define R4NV_SHADER_CACHE_MAX_BYTES ((uint32_t)16384)
#define R4NV_SHADER_PROFILE_RECTANGLE_VERTEX ((uint32_t)1)
#define R4NV_SHADER_PROFILE_TEXTURE_FRAGMENT ((uint32_t)2)
#define R4NV_SHADER_PROFILE_SRGB_DECODE_FRAGMENT ((uint32_t)3)
#define R4NV_SHADER_PROFILE_SRGB_ENCODE_FRAGMENT ((uint32_t)4)
#define R4NV_SHADER_PROFILE_SOLID_FRAGMENT ((uint32_t)5)
#define R4NV_SHADER_PROFILE_SOLID_VERTEX ((uint32_t)6)
#define R4NV_FEATURE_IMAGE_LAYOUT ((uint32_t)8)
#define R4NV_IMAGE_USE_TEXTURE ((uint32_t)1)
#define R4NV_IMAGE_USE_RENDER_TARGET ((uint32_t)2)
#define R4NV_IMAGE_USE_SCANOUT ((uint32_t)4)
#define R4NV_IMAGE_PREFER_COMPATIBLE ((uint32_t)0)
#define R4NV_IMAGE_PREFER_LINEAR ((uint32_t)1)
#define R4NV_IMAGE_PREFER_BLOCKLINEAR ((uint32_t)2)
#define R4NV_IMAGE_FORCE_COPY ((uint32_t)1)
#define R4NV_IMAGE_ACTION_REUSE ((uint32_t)0)
#define R4NV_IMAGE_ACTION_CONVERT ((uint32_t)1)
#define R4NV_IMAGE_REASON_LOCATION ((uint32_t)1)
#define R4NV_IMAGE_REASON_PITCH ((uint32_t)2)
#define R4NV_IMAGE_REASON_MODIFIER ((uint32_t)4)
#define R4NV_IMAGE_REASON_USAGE ((uint32_t)8)
#define R4NV_IMAGE_REASON_FORCED ((uint32_t)16)
#define R4NV_IMAGE_REASON_PREFERENCE ((uint32_t)32)
#define R4NV_SHADER_PROFILE_COLOR_FRAGMENT ((uint32_t)7)
#define R4NV_NATIVE_SUBMIT_VERSION ((uint32_t)1)
#define R4NV_NATIVE_ENGINE_GRAPHICS ((uint32_t)1)
#define R4NV_NATIVE_PUSH_INCOMPLETE ((uint32_t)1)
#define R4NV_NATIVE_PUSH_NO_PREFETCH ((uint32_t)2)
#define R4NV_NATIVE_PUSH_LIMIT ((uint32_t)510)
#define R4NV_NATIVE_ENGINE_COMPUTE ((uint32_t)2)
#define R4NV_NATIVE_ENGINE_COPY ((uint32_t)4)
#define R4NV_ARCHITECTURE_VERSION ((uint32_t)2)
#define R4NV_ARCHITECTURE_HOST_COHERENT ((uint32_t)1)
#define R4NV_STATUS_INVALID ((int32_t)-1)
#define R4NV_STATUS_UNSUPPORTED ((int32_t)-2)
#define R4NV_STATUS_CAPACITY ((int32_t)-3)
#define R4NV_STATUS_CACHE_MISS ((int32_t)-4)

#define R4NV_BACKEND_V1_EXPORT_NAME "BACKEND_V1"
#define R4NV_BACKEND_V1_ABI_MAJOR 1u
#define R4NV_BACKEND_V1_REVISION 3u
#define R4NV_BACKEND_V1_INTERFACE_ID_LO 0x52344e5642454e44ull
#define R4NV_BACKEND_V1_INTERFACE_ID_HI 0x52344f5330373931ull
#define R4NV_BACKEND_V1_TABLE_SIZE 64u
#define R4NV_BACKEND_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4NV_BACKEND_V1_TABLE_SIZE, R4NV_BACKEND_V1_ABI_MAJOR, R4NV_BACKEND_V1_REVISION, R4NV_BACKEND_V1_INTERFACE_ID_LO, R4NV_BACKEND_V1_INTERFACE_ID_HI }
typedef int32_t (*R4NvBackendV1NegotiateFn)(const R4NvDeviceProfile * profile, R4NvFeatures * output);
typedef int32_t (*R4NvBackendV1EncodeCopyFn)(const R4NvCopy * request, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4NvBackendV1EncodeCopyLayoutFn)(const R4NvCopyLayout * request, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4NvBackendV1ImageLayoutFn)(const R4NvDeviceProfile * profile, const R4NvImageRequest * request, R4NvImagePlan * output);
typedef struct R4NvBackendV1 {
    R4LInterfaceHeader header;
    R4NvBackendV1NegotiateFn negotiate;
    R4NvBackendV1EncodeCopyFn encode_copy;
    R4NvBackendV1EncodeCopyLayoutFn encode_copy_layout;
    R4NvBackendV1ImageLayoutFn image_layout;
} R4NvBackendV1;
_Static_assert(sizeof(R4NvBackendV1) == 64u, "R4NvBackendV1 size mismatch");
_Static_assert(offsetof(R4NvBackendV1, negotiate) == 32u, "R4NvBackendV1.negotiate offset mismatch");
_Static_assert(offsetof(R4NvBackendV1, encode_copy) == 40u, "R4NvBackendV1.encode_copy offset mismatch");
_Static_assert(offsetof(R4NvBackendV1, encode_copy_layout) == 48u, "R4NvBackendV1.encode_copy_layout offset mismatch");
_Static_assert(offsetof(R4NvBackendV1, image_layout) == 56u, "R4NvBackendV1.image_layout offset mismatch");
typedef struct R4NvBackendV1Client { const R4LInterfaceHeader *header; } R4NvBackendV1Client;

static inline int32_t r4nv_backend_v1_init(const R4XStartContext *ctx, R4NvBackendV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4NV", "BACKEND_V1");
    const R4LInterfaceExpectation expected = { 0x52344e5642454e44ull, 0x52344f5330373931ull, 1u, 3u, 64u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4nv_negotiate(R4NvBackendV1Client *client, const R4NvDeviceProfile * profile, R4NvFeatures * output) {
    R4NvBackendV1NegotiateFn function = (R4NvBackendV1NegotiateFn)r4l_slot_address(client->header, 32u);
    return function(profile, output);
}

static inline int32_t r4nv_encode_copy(R4NvBackendV1Client *client, const R4NvCopy * request, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4NvBackendV1EncodeCopyFn function = (R4NvBackendV1EncodeCopyFn)r4l_slot_address(client->header, 40u);
    return function(request, commands, capacity, written);
}

static inline int32_t r4nv_encode_copy_layout(R4NvBackendV1Client *client, const R4NvCopyLayout * request, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4NvBackendV1EncodeCopyLayoutFn function = (R4NvBackendV1EncodeCopyLayoutFn)r4l_slot_address(client->header, 48u);
    return function(request, commands, capacity, written);
}

static inline int32_t r4nv_image_layout(R4NvBackendV1Client *client, const R4NvDeviceProfile * profile, const R4NvImageRequest * request, R4NvImagePlan * output) {
    R4NvBackendV1ImageLayoutFn function = (R4NvBackendV1ImageLayoutFn)r4l_slot_address(client->header, 56u);
    return function(profile, request, output);
}

#define R4NV_SHADER_V1_EXPORT_NAME "SHADER_V1"
#define R4NV_SHADER_V1_ABI_MAJOR 1u
#define R4NV_SHADER_V1_REVISION 1u
#define R4NV_SHADER_V1_INTERFACE_ID_LO 0x52344e5653484452ull
#define R4NV_SHADER_V1_INTERFACE_ID_HI 0x52344f5330373934ull
#define R4NV_SHADER_V1_TABLE_SIZE 56u
#define R4NV_SHADER_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4NV_SHADER_V1_TABLE_SIZE, R4NV_SHADER_V1_ABI_MAJOR, R4NV_SHADER_V1_REVISION, R4NV_SHADER_V1_INTERFACE_ID_LO, R4NV_SHADER_V1_INTERFACE_ID_HI }
typedef int32_t (*R4NvShaderV1ShaderInfoFn)(uint32_t profile, R4NvShaderInfo * output);
typedef int32_t (*R4NvShaderV1ShaderCacheWriteFn)(uint32_t profile, const R4NvShaderKey * key, uint8_t * bytes, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4NvShaderV1ShaderCacheReadFn)(const R4NvShaderKey * key, const uint8_t * bytes, uint32_t length, R4NvShaderView * output);
typedef struct R4NvShaderV1 {
    R4LInterfaceHeader header;
    R4NvShaderV1ShaderInfoFn shader_info;
    R4NvShaderV1ShaderCacheWriteFn shader_cache_write;
    R4NvShaderV1ShaderCacheReadFn shader_cache_read;
} R4NvShaderV1;
_Static_assert(sizeof(R4NvShaderV1) == 56u, "R4NvShaderV1 size mismatch");
_Static_assert(offsetof(R4NvShaderV1, shader_info) == 32u, "R4NvShaderV1.shader_info offset mismatch");
_Static_assert(offsetof(R4NvShaderV1, shader_cache_write) == 40u, "R4NvShaderV1.shader_cache_write offset mismatch");
_Static_assert(offsetof(R4NvShaderV1, shader_cache_read) == 48u, "R4NvShaderV1.shader_cache_read offset mismatch");
typedef struct R4NvShaderV1Client { const R4LInterfaceHeader *header; } R4NvShaderV1Client;

static inline int32_t r4nv_shader_v1_init(const R4XStartContext *ctx, R4NvShaderV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4NV", "SHADER_V1");
    const R4LInterfaceExpectation expected = { 0x52344e5653484452ull, 0x52344f5330373934ull, 1u, 1u, 56u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4nv_shader_info(R4NvShaderV1Client *client, uint32_t profile, R4NvShaderInfo * output) {
    R4NvShaderV1ShaderInfoFn function = (R4NvShaderV1ShaderInfoFn)r4l_slot_address(client->header, 32u);
    return function(profile, output);
}

static inline int32_t r4nv_shader_cache_write(R4NvShaderV1Client *client, uint32_t profile, const R4NvShaderKey * key, uint8_t * bytes, uint32_t capacity, uint32_t * written) {
    R4NvShaderV1ShaderCacheWriteFn function = (R4NvShaderV1ShaderCacheWriteFn)r4l_slot_address(client->header, 40u);
    return function(profile, key, bytes, capacity, written);
}

static inline int32_t r4nv_shader_cache_read(R4NvShaderV1Client *client, const R4NvShaderKey * key, const uint8_t * bytes, uint32_t length, R4NvShaderView * output) {
    R4NvShaderV1ShaderCacheReadFn function = (R4NvShaderV1ShaderCacheReadFn)r4l_slot_address(client->header, 48u);
    return function(key, bytes, length, output);
}

#endif
