// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4FONT";

pub const R4FontAllocator = extern struct {
    user: u64,
    alloc: u64,
    realloc: u64,
    free: u64,
};

pub const R4FontDiagnostics = extern struct {
    current_bytes: u64,
    peak_bytes: u64,
    allocation_count: u64,
    reallocation_count: u64,
    reallocation_failure_count: u64,
    allocation_limit: u64,
    allocation_failed: u32,
    reserved: u32,
};

pub const R4FontFaceInfo = extern struct {
    face_count: u32,
    face_index: u32,
    glyph_count: u32,
    units_per_em: u32,
    ascender: i32,
    descender: i32,
    line_height: i32,
    max_advance: i32,
    style_flags: u32,
    reserved: u32,
    family_address: u64,
    style_address: u64,
};

pub const R4FontGlyphMetrics = extern struct {
    glyph_index: u32,
    advance_x: i32,
    advance_y: i32,
    bearing_x: i32,
    bearing_y: i32,
    width: i32,
    height: i32,
};

pub const R4FontKerning = extern struct {
    x: i32,
    y: i32,
};

pub const R4FontRaster = extern struct {
    glyph_index: u32,
    width: u32,
    height: u32,
    left: i32,
    top: i32,
    advance_x_26_6: i32,
    required_bytes: u64,
};
pub const status_ok: i32 = 0;
pub const format_unknown: u32 = 0;
pub const format_ttf: u32 = 1;
pub const format_otf_cff: u32 = 2;
pub const format_woff: u32 = 3;
pub const format_woff2: u32 = 4;
pub const format_collection: u32 = 5;
pub const style_italic: u32 = 1;
pub const style_bold: u32 = 2;
pub const max_source_bytes: u64 = 8388608;
pub const max_reconstructed_bytes: u64 = 33554432;
pub const max_raster_dimension: u32 = 512;
pub const default_allocation_limit: u64 = 67108864;
pub const status_invalid_argument: i32 = -1;
pub const status_out_of_memory: i32 = -2;
pub const status_unsupported_format: i32 = -3;
pub const status_invalid_font: i32 = -4;
pub const status_invalid_face_index: i32 = -5;
pub const status_invalid_glyph: i32 = -6;
pub const status_buffer_too_small: i32 = -7;
pub const status_too_large: i32 = -8;
pub const status_decoder_failure: i32 = -9;

pub const api_v1_export_name = "API_V1";
pub const api_v1_revision: u16 = 1;
pub const api_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 120,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x767de92df622018,
    .interface_id_hi = 0xc0549d6a89118bf3,
};
pub const ApiV1SniffFn = *const fn (bytes: [*]const u8, length: u64, output_format: *u32) callconv(.c) i32;
pub const ApiV1DecoderCreateFn = *const fn (allocator: *const R4FontAllocator, allocation_limit: u64, output_decoder: *u64) callconv(.c) i32;
pub const ApiV1DecoderDestroyFn = *const fn (decoder: u64) callconv(.c) i32;
pub const ApiV1DecoderDiagnosticsFn = *const fn (decoder: u64, output: *R4FontDiagnostics) callconv(.c) i32;
pub const ApiV1DecoderOpenFaceFn = *const fn (decoder: u64, bytes: [*]const u8, length: u64, face_index: u32, output_face: *u64) callconv(.c) i32;
pub const ApiV1FaceCloseFn = *const fn (face: u64) callconv(.c) i32;
pub const ApiV1FaceInfoFn = *const fn (face: u64, output: *R4FontFaceInfo) callconv(.c) i32;
pub const ApiV1GlyphIndexFn = *const fn (face: u64, codepoint: u32, output_glyph: *u32) callconv(.c) i32;
pub const ApiV1GlyphMetricsFn = *const fn (face: u64, glyph: u32, output: *R4FontGlyphMetrics) callconv(.c) i32;
pub const ApiV1KerningFn = *const fn (face: u64, left_glyph: u32, right_glyph: u32, output: *R4FontKerning) callconv(.c) i32;
pub const ApiV1RasterizeFn = *const fn (face: u64, glyph: u32, pixel_height: u32, output: ?[*]u8, output_capacity: u64, output_raster: *R4FontRaster) callconv(.c) i32;
pub const ApiV1 = extern struct {
    header: InterfaceHeader,
    sniff: ApiV1SniffFn,
    decoder_create: ApiV1DecoderCreateFn,
    decoder_destroy: ApiV1DecoderDestroyFn,
    decoder_diagnostics: ApiV1DecoderDiagnosticsFn,
    decoder_open_face: ApiV1DecoderOpenFaceFn,
    face_close: ApiV1FaceCloseFn,
    face_info: ApiV1FaceInfoFn,
    glyph_index: ApiV1GlyphIndexFn,
    glyph_metrics: ApiV1GlyphMetricsFn,
    kerning: ApiV1KerningFn,
    rasterize: ApiV1RasterizeFn,
};

pub const ApiV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !ApiV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, api_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x767de92df622018,
            .interface_id_hi = 0xc0549d6a89118bf3,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 120,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 56) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 64) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 72) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 80) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 88) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 96) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 104) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 112) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn sniff(self: *const ApiV1Client, bytes: [*]const u8, length: u64, output_format: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1SniffFn, self.header, 32) orelse unreachable;
        return function(bytes, length, output_format);
    }

    pub fn decoder_create(self: *const ApiV1Client, allocator: *const R4FontAllocator, allocation_limit: u64, output_decoder: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecoderCreateFn, self.header, 40) orelse unreachable;
        return function(allocator, allocation_limit, output_decoder);
    }

    pub fn decoder_destroy(self: *const ApiV1Client, decoder: u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecoderDestroyFn, self.header, 48) orelse unreachable;
        return function(decoder);
    }

    pub fn decoder_diagnostics(self: *const ApiV1Client, decoder: u64, output: *R4FontDiagnostics) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecoderDiagnosticsFn, self.header, 56) orelse unreachable;
        return function(decoder, output);
    }

    pub fn decoder_open_face(self: *const ApiV1Client, decoder: u64, bytes: [*]const u8, length: u64, face_index: u32, output_face: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecoderOpenFaceFn, self.header, 64) orelse unreachable;
        return function(decoder, bytes, length, face_index, output_face);
    }

    pub fn face_close(self: *const ApiV1Client, face: u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1FaceCloseFn, self.header, 72) orelse unreachable;
        return function(face);
    }

    pub fn face_info(self: *const ApiV1Client, face: u64, output: *R4FontFaceInfo) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1FaceInfoFn, self.header, 80) orelse unreachable;
        return function(face, output);
    }

    pub fn glyph_index(self: *const ApiV1Client, face: u64, codepoint: u32, output_glyph: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1GlyphIndexFn, self.header, 88) orelse unreachable;
        return function(face, codepoint, output_glyph);
    }

    pub fn glyph_metrics(self: *const ApiV1Client, face: u64, glyph: u32, output: *R4FontGlyphMetrics) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1GlyphMetricsFn, self.header, 96) orelse unreachable;
        return function(face, glyph, output);
    }

    pub fn kerning(self: *const ApiV1Client, face: u64, left_glyph: u32, right_glyph: u32, output: *R4FontKerning) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1KerningFn, self.header, 104) orelse unreachable;
        return function(face, left_glyph, right_glyph, output);
    }

    pub fn rasterize(self: *const ApiV1Client, face: u64, glyph: u32, pixel_height: u32, output: ?[*]u8, output_capacity: u64, output_raster: *R4FontRaster) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1RasterizeFn, self.header, 112) orelse unreachable;
        return function(face, glyph, pixel_height, output, output_capacity, output_raster);
    }
};
