#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 R4OS contributors

"""Build the deterministic R4FONT kerning fixtures without external tools.

The generated files are WOFF 1.0 containers whose SFNT tables are stored
uncompressed.  They intentionally contain only .notdef, A, V, and T.  One
font exercises the legacy `kern` table; the other exercises a DFLT/kern GPOS
PairPos Format 1 lookup.  Run with --check to compare freshly generated bytes
and manifest hashes with the checked-in fixtures.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import struct
import sys
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
TESTS_DIR = SCRIPT_PATH.parent.parent
FIXTURES_DIR = TESTS_DIR / "Fixtures"
MANIFEST_PATH = FIXTURES_DIR / "FIXTURES.json"

BSD_NOTICE = (
    "Copyright (c) 2026 R4OS contributors. "
    "Licensed under BSD-3-Clause; see LICENSE-R4FONT-FIXTURES-BSD-3-Clause.txt."
)


def u16(value: int) -> bytes:
    return struct.pack(">H", value)


def s16(value: int) -> bytes:
    return struct.pack(">h", value)


def u32(value: int) -> bytes:
    return struct.pack(">I", value)


def align4(value: int) -> int:
    return (value + 3) & ~3


def padded(data: bytes) -> bytes:
    return data + bytes(align4(len(data)) - len(data))


def table_checksum(data: bytes) -> int:
    words = padded(data)
    return sum(struct.unpack(f">{len(words) // 4}I", words)) & 0xFFFFFFFF


def simple_glyph(points: list[tuple[int, int]]) -> bytes:
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    result = bytearray()
    result += s16(1)
    result += s16(min(xs)) + s16(min(ys)) + s16(max(xs)) + s16(max(ys))
    result += u16(len(points) - 1)
    result += u16(0)
    result += bytes([0x01] * len(points))
    previous = 0
    for x in xs:
        result += s16(x - previous)
        previous = x
    previous = 0
    for y in ys:
        result += s16(y - previous)
        previous = y
    return bytes(result)


def glyf_and_loca() -> tuple[bytes, bytes]:
    glyphs = [
        simple_glyph([(50, 0), (550, 0), (550, 700), (50, 700)]),
        simple_glyph([(50, 0), (350, 700), (650, 0)]),
        simple_glyph([(50, 700), (350, 0), (650, 700)]),
        simple_glyph([(50, 600), (600, 600), (600, 700), (50, 700)]),
    ]
    data = bytearray()
    offsets: list[int] = []
    for glyph in glyphs:
        offsets.append(len(data))
        data += padded(glyph)
    offsets.append(len(data))
    return bytes(data), b"".join(u32(offset) for offset in offsets)


def cmap_table() -> bytes:
    mappings = ((0x0041, 1), (0x0054, 3), (0x0056, 2))
    end_codes = [codepoint for codepoint, _ in mappings] + [0xFFFF]
    start_codes = end_codes.copy()
    deltas = [
        (glyph - codepoint) & 0xFFFF for codepoint, glyph in mappings
    ] + [1]
    seg_count = len(end_codes)
    power = 1 << int(math.log2(seg_count))
    subtable = bytearray()
    subtable += u16(4) + u16(16 + 8 * seg_count) + u16(0)
    subtable += u16(seg_count * 2) + u16(power * 2)
    subtable += u16(int(math.log2(power))) + u16(seg_count * 2 - power * 2)
    subtable += b"".join(u16(value) for value in end_codes)
    subtable += u16(0)
    subtable += b"".join(u16(value) for value in start_codes)
    subtable += b"".join(u16(value) for value in deltas)
    subtable += b"".join(u16(0) for _ in end_codes)
    records_size = 4 + 2 * 8
    return (
        u16(0)
        + u16(2)
        + u16(0)
        + u16(3)
        + u32(records_size)
        + u16(3)
        + u16(1)
        + u32(records_size)
        + bytes(subtable)
    )


def name_table(family: str) -> bytes:
    names = {
        0: "Copyright (c) 2026 R4OS contributors",
        1: family,
        2: "Regular",
        3: f"R4OS:{family}:1.0",
        4: f"{family} Regular",
        5: "Version 1.0",
        6: family.replace(" ", "") + "-Regular",
        13: BSD_NOTICE,
        14: "https://spdx.org/licenses/BSD-3-Clause.html",
    }
    records = bytearray()
    strings = bytearray()
    for name_id, text in sorted(names.items()):
        encoded = text.encode("utf-16-be")
        records += u16(3) + u16(1) + u16(0x0409) + u16(name_id)
        records += u16(len(encoded)) + u16(len(strings))
        strings += encoded
    return u16(0) + u16(len(names)) + u16(6 + len(records)) + records + strings


def os2_table() -> bytes:
    result = bytearray()
    result += u16(0) + s16(662) + u16(400) + u16(5) + u16(0)
    result += s16(650) + s16(600) + s16(0) + s16(75)
    result += s16(650) + s16(600) + s16(0) + s16(350)
    result += s16(50) + s16(250) + s16(0)
    result += bytes(10)
    result += u32(1) + u32(0) + u32(0) + u32(0)
    result += b"R4OS"
    result += u16(0x0040) + u16(0x0041) + u16(0x0056)
    result += s16(800) + s16(-200) + s16(200) + u16(800) + u16(200)
    assert len(result) == 78
    return bytes(result)


def head_table() -> bytes:
    result = bytearray()
    result += u32(0x00010000) + u32(0x00010000) + u32(0)
    result += u32(0x5F0F3CF5) + u16(0) + u16(1000)
    result += struct.pack(">q", 0) + struct.pack(">q", 0)
    result += s16(0) + s16(0) + s16(650) + s16(700)
    result += u16(0) + u16(8) + s16(2) + s16(1) + s16(0)
    assert len(result) == 54
    return bytes(result)


def hhea_table() -> bytes:
    result = bytearray()
    result += u32(0x00010000)
    result += s16(800) + s16(-200) + s16(200)
    result += u16(700) + s16(0) + s16(0) + s16(650)
    result += s16(1) + s16(0) + s16(0)
    result += s16(0) * 4 + s16(0) + u16(4)
    assert len(result) == 36
    return bytes(result)


def maxp_table() -> bytes:
    values = (4, 4, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
    result = u32(0x00010000) + b"".join(u16(value) for value in values)
    assert len(result) == 32
    return result


def post_table() -> bytes:
    result = bytearray()
    result += u32(0x00030000) + u32(0)
    result += s16(-75) + s16(50)
    result += u32(0) * 5
    assert len(result) == 32
    return bytes(result)


def kern_table() -> bytes:
    subtable = bytearray()
    subtable += u16(0) + u16(20) + u16(0x0001)
    subtable += u16(1) + u16(6) + u16(0) + u16(0)
    subtable += u16(1) + u16(2) + s16(-115)
    return u16(0) + u16(1) + bytes(subtable)


def gpos_table() -> bytes:
    default_langsys = u16(0) + u16(0xFFFF) + u16(1) + u16(0)
    script = u16(4) + u16(0) + default_langsys
    script_list = u16(1) + b"DFLT" + u16(8) + script

    feature = u16(0) + u16(1) + u16(0)
    feature_list = u16(1) + b"kern" + u16(8) + feature

    pair_set = u16(1) + u16(3) + s16(-93)
    coverage = u16(1) + u16(1) + u16(1)
    pair_pos = (
        u16(1)
        + u16(18)
        + u16(0x0004)
        + u16(0)
        + u16(1)
        + u16(12)
        + pair_set
        + coverage
    )
    lookup = u16(2) + u16(0) + u16(1) + u16(8) + pair_pos
    lookup_list = u16(1) + u16(4) + lookup

    header_size = 10
    feature_offset = header_size + len(script_list)
    lookup_offset = feature_offset + len(feature_list)
    return (
        u16(1)
        + u16(0)
        + u16(header_size)
        + u16(feature_offset)
        + u16(lookup_offset)
        + script_list
        + feature_list
        + lookup_list
    )


def base_tables(family: str) -> dict[bytes, bytes]:
    glyf, loca = glyf_and_loca()
    return {
        b"OS/2": os2_table(),
        b"cmap": cmap_table(),
        b"glyf": glyf,
        b"head": head_table(),
        b"hhea": hhea_table(),
        b"hmtx": u16(600) + s16(0) + u16(700) + s16(0)
        + u16(700) + s16(0) + u16(650) + s16(0),
        b"loca": loca,
        b"maxp": maxp_table(),
        b"name": name_table(family),
        b"post": post_table(),
    }


def sfnt_bytes(tables: dict[bytes, bytes]) -> tuple[bytes, dict[bytes, int]]:
    tags = sorted(tables)
    num_tables = len(tags)
    power = 1 << int(math.log2(num_tables))
    header = (
        u32(0x00010000)
        + u16(num_tables)
        + u16(power * 16)
        + u16(int(math.log2(power)))
        + u16(num_tables * 16 - power * 16)
    )
    checksums = {tag: table_checksum(tables[tag]) for tag in tags}

    def assemble() -> bytes:
        data_offset = 12 + 16 * num_tables
        records = bytearray()
        body = bytearray()
        for tag in tags:
            table = tables[tag]
            offset = data_offset + len(body)
            records += tag + u32(checksums[tag]) + u32(offset) + u32(len(table))
            body += padded(table)
        return header + records + body

    unadjusted = assemble()
    adjustment = (0xB1B0AFBA - table_checksum(unadjusted)) & 0xFFFFFFFF
    head = bytearray(tables[b"head"])
    head[8:12] = u32(adjustment)
    tables[b"head"] = bytes(head)
    result = assemble()
    assert table_checksum(result) == 0xB1B0AFBA
    return result, checksums


def woff_bytes(tables: dict[bytes, bytes]) -> bytes:
    sfnt, checksums = sfnt_bytes(tables)
    tags = sorted(tables)
    directory_size = 44 + 20 * len(tags)
    directory = bytearray()
    body = bytearray()
    for tag in tags:
        table = tables[tag]
        offset = directory_size + len(body)
        directory += tag + u32(offset) + u32(len(table)) + u32(len(table))
        directory += u32(checksums[tag])
        body += padded(table)
    total_length = directory_size + len(body)
    header = bytearray()
    header += b"wOFF" + u32(0x00010000) + u32(total_length)
    header += u16(len(tags)) + u16(0) + u32(len(sfnt))
    header += u16(1) + u16(0)
    header += u32(0) * 5
    assert len(header) == 44
    return bytes(header + directory + body)


def generated_fonts() -> dict[str, bytes]:
    legacy = base_tables("R4FONT Fixture Kern")
    legacy[b"kern"] = kern_table()
    gpos = base_tables("R4FONT Fixture GPOS")
    gpos[b"GPOS"] = gpos_table()
    return {
        "sample-kern.woff": woff_bytes(legacy),
        "sample-gpos.woff": woff_bytes(gpos),
    }


def manifest() -> dict[str, object]:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def check() -> int:
    document = manifest()
    failed = False
    generator_digest = hashlib.sha256(SCRIPT_PATH.read_bytes()).hexdigest()
    if document["generator"]["sha256"] != generator_digest:
        print(
            f"generator hash mismatch: generated={generator_digest}",
            file=sys.stderr,
        )
        failed = True
    generated_by_name = generated_fonts()
    wpt = document["upstream"]["web-platform-tests"]
    wpt_commit = wpt["commit"]
    if (
        len(wpt_commit) != 40
        or any(character not in "0123456789abcdef" for character in wpt_commit)
        or not wpt["repository"].startswith("https://")
    ):
        print(f"invalid WPT fixture provenance: {wpt_commit}", file=sys.stderr)
        failed = True
    for entry in document["fixtures"]:
        name = entry["file"]
        fixture_path = FIXTURES_DIR / name
        if not fixture_path.is_file():
            print(f"missing fixture: {fixture_path}", file=sys.stderr)
            failed = True
            continue
        actual = fixture_path.read_bytes()
        digest = hashlib.sha256(actual).hexdigest()
        if entry["sha256"] != digest:
            print(f"fixture hash mismatch: {name} actual={digest}", file=sys.stderr)
            failed = True
        if entry["license"] not in ("BSD-3-Clause", "MIT"):
            print(f"non-permissive or unknown license: {name}", file=sys.stderr)
            failed = True
        notice_path = FIXTURES_DIR / entry["notice"]
        if not notice_path.is_file() or not notice_path.read_bytes():
            print(f"missing license notice: {notice_path}", file=sys.stderr)
            failed = True
        generated = generated_by_name.get(name)
        if generated is not None:
            if entry["source"] != "R4FONT/Tests/Tools/generate_minimal_fonts.py":
                print(f"generated fixture source mismatch: {name}", file=sys.stderr)
                failed = True
            if actual != generated:
                print(f"generated-byte mismatch: {fixture_path}", file=sys.stderr)
                failed = True
        elif not entry["source"].startswith("web-platform-tests/"):
            print(f"external fixture source mismatch: {name}", file=sys.stderr)
            failed = True
    if failed:
        return 1
    print("R4FONT fixture bytes, hashes, licenses, sources and generator are reproducible.")
    return 0


def write() -> int:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    for name, data in generated_fonts().items():
        path = FIXTURES_DIR / name
        path.write_bytes(data)
        print(f"wrote {path} sha256={hashlib.sha256(data).hexdigest()}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes and SHA-256 values with the repository",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
