/* Generated by R4LContractGen. Do not edit. */
#ifndef R4GFX_R4L_BINDING_H
#define R4GFX_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4GfxLinearLayout {
    uint64_t byte_length;
    uint64_t pitch;
    uint32_t width;
    uint32_t height;
    uint32_t format;
    uint32_t reserved;
} R4GfxLinearLayout;
_Static_assert(sizeof(R4GfxLinearLayout) == 32u, "R4GfxLinearLayout size mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, byte_length) == 0u, "R4GfxLinearLayout.byte_length offset mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, pitch) == 8u, "R4GfxLinearLayout.pitch offset mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, width) == 16u, "R4GfxLinearLayout.width offset mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, height) == 20u, "R4GfxLinearLayout.height offset mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, format) == 24u, "R4GfxLinearLayout.format offset mismatch");
_Static_assert(offsetof(R4GfxLinearLayout, reserved) == 28u, "R4GfxLinearLayout.reserved offset mismatch");

typedef struct R4GfxCpuImage {
    uint64_t cpu_address;
    uint64_t byte_length;
    uint64_t pitch;
    uint32_t width;
    uint32_t height;
    uint32_t format;
    uint32_t reserved;
} R4GfxCpuImage;
_Static_assert(sizeof(R4GfxCpuImage) == 40u, "R4GfxCpuImage size mismatch");
_Static_assert(offsetof(R4GfxCpuImage, cpu_address) == 0u, "R4GfxCpuImage.cpu_address offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, byte_length) == 8u, "R4GfxCpuImage.byte_length offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, pitch) == 16u, "R4GfxCpuImage.pitch offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, width) == 24u, "R4GfxCpuImage.width offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, height) == 28u, "R4GfxCpuImage.height offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, format) == 32u, "R4GfxCpuImage.format offset mismatch");
_Static_assert(offsetof(R4GfxCpuImage, reserved) == 36u, "R4GfxCpuImage.reserved offset mismatch");

typedef struct R4GfxRect {
    uint32_t x;
    uint32_t y;
    uint32_t width;
    uint32_t height;
} R4GfxRect;
_Static_assert(sizeof(R4GfxRect) == 16u, "R4GfxRect size mismatch");
_Static_assert(offsetof(R4GfxRect, x) == 0u, "R4GfxRect.x offset mismatch");
_Static_assert(offsetof(R4GfxRect, y) == 4u, "R4GfxRect.y offset mismatch");
_Static_assert(offsetof(R4GfxRect, width) == 8u, "R4GfxRect.width offset mismatch");
_Static_assert(offsetof(R4GfxRect, height) == 12u, "R4GfxRect.height offset mismatch");

#define R4GFX_STATUS_OK ((int32_t)0)
#define R4GFX_FORMAT_XRGB8888 ((uint32_t)875713112)
#define R4GFX_FORMAT_ARGB8888 ((uint32_t)875713089)
#define R4GFX_FORMAT_R8 ((uint32_t)538982482)
#define R4GFX_STATUS_INVALID ((int32_t)-1)
#define R4GFX_STATUS_UNSUPPORTED ((int32_t)-2)
#define R4GFX_STATUS_OVERFLOW ((int32_t)-3)

#define R4GFX_API_V1_EXPORT_NAME "API_V1"
#define R4GFX_API_V1_ABI_MAJOR 1u
#define R4GFX_API_V1_REVISION 1u
#define R4GFX_API_V1_INTERFACE_ID_LO 0x34584647ull
#define R4GFX_API_V1_INTERFACE_ID_HI 0x35393730ull
#define R4GFX_API_V1_TABLE_SIZE 48u
#define R4GFX_API_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4GFX_API_V1_TABLE_SIZE, R4GFX_API_V1_ABI_MAJOR, R4GFX_API_V1_REVISION, R4GFX_API_V1_INTERFACE_ID_LO, R4GFX_API_V1_INTERFACE_ID_HI }
typedef int32_t (*R4GfxApiV1LinearLayoutFn)(uint32_t width, uint32_t height, uint32_t format, uint64_t row_alignment, R4GfxLinearLayout * output);
typedef int32_t (*R4GfxApiV1FillRectFn)(const R4GfxCpuImage * image, const R4GfxRect * rect, uint32_t color);
typedef struct R4GfxApiV1 {
    R4LInterfaceHeader header;
    R4GfxApiV1LinearLayoutFn linear_layout;
    R4GfxApiV1FillRectFn fill_rect;
} R4GfxApiV1;
_Static_assert(sizeof(R4GfxApiV1) == 48u, "R4GfxApiV1 size mismatch");
_Static_assert(offsetof(R4GfxApiV1, linear_layout) == 32u, "R4GfxApiV1.linear_layout offset mismatch");
_Static_assert(offsetof(R4GfxApiV1, fill_rect) == 40u, "R4GfxApiV1.fill_rect offset mismatch");
typedef struct R4GfxApiV1Client { const R4LInterfaceHeader *header; } R4GfxApiV1Client;

static inline int32_t r4gfx_api_v1_init(const R4XStartContext *ctx, R4GfxApiV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4GFX", "API_V1");
    const R4LInterfaceExpectation expected = { 0x34584647ull, 0x35393730ull, 1u, 1u, 48u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4gfx_linear_layout(R4GfxApiV1Client *client, uint32_t width, uint32_t height, uint32_t format, uint64_t row_alignment, R4GfxLinearLayout * output) {
    R4GfxApiV1LinearLayoutFn function = (R4GfxApiV1LinearLayoutFn)r4l_slot_address(client->header, 32u);
    return function(width, height, format, row_alignment, output);
}

static inline int32_t r4gfx_fill_rect(R4GfxApiV1Client *client, const R4GfxCpuImage * image, const R4GfxRect * rect, uint32_t color) {
    R4GfxApiV1FillRectFn function = (R4GfxApiV1FillRectFn)r4l_slot_address(client->header, 40u);
    return function(image, rect, color);
}

#endif
