// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4ACO";

pub const R4AcoInfo = extern struct {
    version: u32,
    size: u32,
    mesa_major: u32,
    mesa_minor: u32,
    mesa_patch: u32,
    implementation_stage: u32,
    capability_flags: u32,
    reserved: u32,
};

pub const R4AcoDigest = extern struct {
    h0: u64,
    h1: u64,
    h2: u64,
    h3: u64,
};

pub const R4AcoRuntime = extern struct {
    version: u32,
    size: u32,
    user: u64,
    owner_generation: u64,
    allocate: u64,
    release: u64,
    clock_ns: u64,
    abort_worker: u64,
    owner_retired: u64,
    cancelled: u64,
};

pub const R4AcoRequest = extern struct {
    version: u32,
    size: u32,
    stage: u32,
    device_id: u32,
    chip_revision: u32,
    flags: u32,
    word_count: u32,
    entry_length: u32,
    words: u64,
    entry: u64,
    budget_bytes: u64,
    deadline_ns: u64,
    code: u64,
    code_capacity: u32,
    log_capacity: u32,
    log: u64,
};

pub const R4AcoSymbols = extern struct {
    s0: u64,
    s1: u64,
    s2: u64,
    s3: u64,
    s4: u64,
    s5: u64,
    s6: u64,
    s7: u64,
    s8: u64,
    s9: u64,
    s10: u64,
    s11: u64,
    s12: u64,
    s13: u64,
    s14: u64,
    s15: u64,
    s16: u64,
    s17: u64,
    s18: u64,
    s19: u64,
    s20: u64,
    s21: u64,
    s22: u64,
    s23: u64,
    s24: u64,
    s25: u64,
    s26: u64,
    s27: u64,
    s28: u64,
    s29: u64,
    s30: u64,
    s31: u64,
};

pub const R4AcoBinary = extern struct {
    version: u32,
    size: u32,
    status: i32,
    stage: u32,
    device_id: u32,
    chip_revision: u32,
    gfx_profile: u32,
    resource_abi: u32,
    code_bytes: u32,
    exec_bytes: u32,
    sgprs: u32,
    vgprs: u32,
    lds_bytes: u32,
    scratch_bytes_per_wave: u32,
    float_mode: u32,
    user_sgprs: u32,
    input_vgprs: u32,
    workgroup_x: u32,
    workgroup_y: u32,
    workgroup_z: u32,
    spi_ps_input_ena: u32,
    spi_ps_input_addr: u32,
    spi_shader_col_format: u32,
    symbol_count: u32,
    inputs_read: u64,
    outputs_written: u64,
    source_hash: R4AcoDigest,
    symbols: R4AcoSymbols,
    peak_bytes: u64,
    elapsed_ns: u64,
    log_length: u32,
    reserved: u32,
};

pub const R4AcoCacheKey = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    device_id: u32,
    chip_revision: u32,
    gfx_profile: u32,
    stage: u32,
    resource_abi: u32,
    command_abi: u32,
    driver_version: u32,
    format: u32,
    reserved: u32,
    device_generation: u64,
    reset_generation: u64,
    pipeline_layout: u64,
    source_hash: R4AcoDigest,
    pipeline_hash: R4AcoDigest,
};
pub const info_version: u32 = 1;
pub const status_ok: i32 = 0;
pub const compiler_revision: u32 = 1;
pub const capability_cpu_compile: u32 = 1;
pub const request_textures: u32 = 1;
pub const status_invalid: i32 = -1;
pub const status_unsupported: i32 = -2;
pub const status_busy: i32 = -3;
pub const status_memory: i32 = -4;
pub const status_cancelled: i32 = -5;
pub const status_compiler: i32 = -6;
pub const status_capacity: i32 = -7;
pub const status_cache_miss: i32 = -8;

pub const info_v1_export_name = "INFO_V1";
pub const info_v1_revision: u16 = 1;
pub const info_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 40,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x41434f31,
    .interface_id_hi = 0x52344f53,
};
pub const InfoV1GetInfoFn = *const fn (output: *R4AcoInfo, output_bytes: u32) callconv(.c) i32;
pub const InfoV1 = extern struct {
    header: InterfaceHeader,
    get_info: InfoV1GetInfoFn,
};

pub const compiler_v1_export_name = "COMPILER_V1";
pub const compiler_v1_revision: u16 = 1;
pub const compiler_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 56,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x41434f32,
    .interface_id_hi = 0x52344f53,
};
pub const CompilerV1CompileFn = *const fn (runtime: *const R4AcoRuntime, request: *const R4AcoRequest, output: *R4AcoBinary) callconv(.c) i32;
pub const CompilerV1CacheWriteFn = *const fn (key: *const R4AcoCacheKey, binary: *const R4AcoBinary, code: [*]const u8, code_length: u64, bytes: [*]u8, capacity: u64, written: *u64) callconv(.c) i32;
pub const CompilerV1CacheReadFn = *const fn (key: *const R4AcoCacheKey, bytes: [*]const u8, length: u64, output: *R4AcoBinary, code: [*]u8, capacity: u64) callconv(.c) i32;
pub const CompilerV1 = extern struct {
    header: InterfaceHeader,
    compile: CompilerV1CompileFn,
    cache_write: CompilerV1CacheWriteFn,
    cache_read: CompilerV1CacheReadFn,
};

pub const InfoV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !InfoV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, info_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x41434f31,
            .interface_id_hi = 0x52344f53,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 40,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn get_info(self: *const InfoV1Client, output: *R4AcoInfo, output_bytes: u32) i32 {
        const function = r4os.runtime_r4l.functionAt(InfoV1GetInfoFn, self.header, 32) orelse unreachable;
        return function(output, output_bytes);
    }
};

pub const CompilerV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !CompilerV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, compiler_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x41434f32,
            .interface_id_hi = 0x52344f53,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 56,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn compile(self: *const CompilerV1Client, runtime: *const R4AcoRuntime, request: *const R4AcoRequest, output: *R4AcoBinary) i32 {
        const function = r4os.runtime_r4l.functionAt(CompilerV1CompileFn, self.header, 32) orelse unreachable;
        return function(runtime, request, output);
    }

    pub fn cache_write(self: *const CompilerV1Client, key: *const R4AcoCacheKey, binary: *const R4AcoBinary, code: [*]const u8, code_length: u64, bytes: [*]u8, capacity: u64, written: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(CompilerV1CacheWriteFn, self.header, 40) orelse unreachable;
        return function(key, binary, code, code_length, bytes, capacity, written);
    }

    pub fn cache_read(self: *const CompilerV1Client, key: *const R4AcoCacheKey, bytes: [*]const u8, length: u64, output: *R4AcoBinary, code: [*]u8, capacity: u64) i32 {
        const function = r4os.runtime_r4l.functionAt(CompilerV1CacheReadFn, self.header, 48) orelse unreachable;
        return function(key, bytes, length, output, code, capacity);
    }
};
