/*
 * Copyright 2015 Advanced Micro Devices, Inc.
 * Copyright 2024 Valve Corporation
 * Copyright 2026 R4
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * Bounded GFX9 specialization of ac_descriptors.c/ac_formats.c. Register masks
 * are generated by the original Mesa generator from gfx9.json, not hand-sized.
 */
#include "addr_bridge.h"
#include "amdgfx9regs.h"

extern "C" int32_t r4amd_addr_descriptors(const R4AmdImageRequest *r, const R4AmdImageLayout *l,
                                        const R4AmdImageView *v, R4AmdImageDescriptors *out) {
    uint32_t df = 0, cf = 0, nf = V_008F14_IMG_NUM_FORMAT_UNORM;
    uint32_t x = V_008F1C_SQ_SEL_X, y = V_008F1C_SQ_SEL_Y, z = V_008F1C_SQ_SEL_Z, w = V_008F1C_SQ_SEL_W;
    uint32_t swap = V_028C70_SWAP_STD, bc = V_008F20_BC_SWIZZLE_XYZW;
    bool force_alpha = false;
    switch (r->format) {
    case 875713112: case 875713089:
        df = V_008F14_IMG_DATA_FORMAT_8_8_8_8; cf = V_028C70_COLOR_8_8_8_8;
        x = V_008F1C_SQ_SEL_Z; z = V_008F1C_SQ_SEL_X; swap = V_028C70_SWAP_ALT; bc = V_008F20_BC_SWIZZLE_ZYXW;
        force_alpha = r->format == 875713112; break;
    case 808669784: case 808669761:
        df = V_008F14_IMG_DATA_FORMAT_2_10_10_10; cf = V_028C70_COLOR_2_10_10_10;
        x = V_008F1C_SQ_SEL_Z; z = V_008F1C_SQ_SEL_X; swap = V_028C70_SWAP_ALT; bc = V_008F20_BC_SWIZZLE_ZYXW;
        force_alpha = r->format == 808669784; break;
    case 1211384385: case 942948929:
        df = V_008F14_IMG_DATA_FORMAT_16_16_16_16; cf = V_028C70_COLOR_16_16_16_16;
        if (r->format == 1211384385) nf = V_008F14_IMG_NUM_FORMAT_FLOAT;
        break;
    case 538982482:
        df = V_008F14_IMG_DATA_FORMAT_8; cf = V_028C70_COLOR_8;
        y = z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x38385247:
        df = V_008F14_IMG_DATA_FORMAT_8_8; cf = V_028C70_COLOR_8_8;
        z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x20363152:
        df = V_008F14_IMG_DATA_FORMAT_16; cf = V_028C70_COLOR_16;
        y = z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x32335247:
        df = V_008F14_IMG_DATA_FORMAT_16_16; cf = V_028C70_COLOR_16_16;
        z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x01000001:
        df = V_008F14_IMG_DATA_FORMAT_32; nf = V_008F14_IMG_NUM_FORMAT_FLOAT;
        y = z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x01000002:
        df = V_008F14_IMG_DATA_FORMAT_16; y = z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x01000101: df = V_008F14_IMG_DATA_FORMAT_BC1; break;
    case 0x01000103: df = V_008F14_IMG_DATA_FORMAT_BC3; break;
    case 0x01000105: df = V_008F14_IMG_DATA_FORMAT_BC5; z = V_008F1C_SQ_SEL_0; force_alpha = true; break;
    case 0x01000107: df = V_008F14_IMG_DATA_FORMAT_BC7; break;
    default: return R4AMD_STATUS_UNSUPPORTED;
    }
    if (force_alpha) w = V_008F1C_SQ_SEL_1;
    if (v->flags == 1) nf = V_008F14_IMG_NUM_FORMAT_UINT;
    if (v->flags == 2) x = y = z = w = V_008F1C_SQ_SEL_X; // Premultiplied white mask.
    const uint64_t va = v->address + v->offset;
    const uint32_t samples_log2 = __builtin_ctz(r->samples);
    uint32_t type;
    if (r->resource_type == 0) type = r->depth > 1 ? V_008F1C_SQ_RSRC_IMG_1D_ARRAY : V_008F1C_SQ_RSRC_IMG_1D;
    else if (r->resource_type == 2) type = V_008F1C_SQ_RSRC_IMG_3D;
    else if (r->samples > 1) type = r->depth > 1 ? V_008F1C_SQ_RSRC_IMG_2D_MSAA_ARRAY : V_008F1C_SQ_RSRC_IMG_2D_MSAA;
    else type = r->depth > 1 ? V_008F1C_SQ_RSRC_IMG_2D_ARRAY : V_008F1C_SQ_RSRC_IMG_2D;
    R4AmdImageDescriptors d = {}; d.version = 1; d.size = sizeof(d);
    d.texture0 = static_cast<uint32_t>(va >> 8) | r->pipe_xor;
    d.texture1 = S_008F14_BASE_ADDRESS_HI(va >> 40) | S_008F14_DATA_FORMAT(df) | S_008F14_NUM_FORMAT(nf);
    d.texture2 = S_008F18_WIDTH(r->width - 1) | S_008F18_HEIGHT(r->height - 1) | S_008F18_PERF_MOD(4);
    d.texture3 = S_008F1C_DST_SEL_X(x) | S_008F1C_DST_SEL_Y(y) | S_008F1C_DST_SEL_Z(z) | S_008F1C_DST_SEL_W(w) |
                 S_008F1C_BASE_LEVEL(r->samples > 1 ? 0 : v->first_mip) |
                 S_008F1C_LAST_LEVEL(r->samples > 1 ? samples_log2 : v->last_mip) |
                 S_008F1C_TYPE(type) | S_008F1C_SW_MODE(r->swizzle);
    d.texture4 = S_008F20_DEPTH(r->resource_type == 2 ? r->depth - 1 : v->last_layer) | S_008F20_PITCH(l->epitch) | S_008F20_BC_SWIZZLE(bc);
    d.texture5 = S_008F24_BASE_ARRAY(v->first_layer) | S_008F24_MAX_MIP(r->samples > 1 ? samples_log2 : r->mip_count - 1);
    // No metadata address/compression bit. DCC/HTILE queries are not transitions.
    const uint32_t filter = v->sampler | (v->aniso ? 2 : 0);
    d.sampler0 = S_008F30_CLAMP_X(v->wrap_u) | S_008F30_CLAMP_Y(v->wrap_v) | S_008F30_CLAMP_Z(v->wrap_w) |
                 S_008F30_MAX_ANISO_RATIO(v->aniso) | S_008F30_DEPTH_COMPARE_FUNC(v->compare) |
                 S_008F30_ANISO_THRESHOLD(v->aniso >> 1) | S_008F30_ANISO_BIAS(v->aniso) |
                 S_008F30_DISABLE_CUBE_WRAP(1) | S_008F30_COMPAT_MODE(1);
    d.sampler1 = S_008F34_MIN_LOD(v->min_lod) | S_008F34_MAX_LOD(v->max_lod) | S_008F34_PERF_MIP(v->aniso ? v->aniso + 6 : 0);
    d.sampler2 = S_008F38_XY_MAG_FILTER(filter) | S_008F38_XY_MIN_FILTER(filter) |
                 S_008F38_MIP_FILTER(v->first_mip == v->last_mip ? 0 : (v->sampler ? 2 : 1)) |
                 S_008F38_LOD_BIAS(v->lod_bias) | S_008F38_FILTER_PREC_FIX(1) | S_008F38_ANISO_OVERRIDE(1);
    d.sampler3 = S_008F3C_BORDER_COLOR_TYPE(v->border);
    if (r->usage & 2) {
        const uint32_t number = nf == V_008F14_IMG_NUM_FORMAT_FLOAT ? V_028C70_NUMBER_FLOAT : V_028C70_NUMBER_UNORM;
        d.color0 = static_cast<uint32_t>(va >> 8) | r->pipe_xor;
        d.color1 = S_028C64_BASE_256B(va >> 40);
        d.color2 = S_028C68_MIP0_WIDTH(r->width - 1) | S_028C68_MIP0_HEIGHT(r->height - 1) | S_028C68_MAX_MIP(r->mip_count - 1);
        d.color3 = S_028C6C_SLICE_START(v->first_layer) | S_028C6C_SLICE_MAX(v->last_layer) | S_028C6C_MIP_LEVEL(v->first_mip);
        d.color4 = S_028C70_COMP_SWAP(swap) | S_028C70_BLEND_CLAMP(number == V_028C70_NUMBER_UNORM) |
                   S_028C70_SIMPLE_FLOAT(1) | S_028C70_ROUND_MODE(number != V_028C70_NUMBER_UNORM) | S_028C70_NUMBER_TYPE(number) | S_028C70_FORMAT(cf);
        d.color5 = S_028C74_NUM_SAMPLES(samples_log2) | S_028C74_NUM_FRAGMENTS(samples_log2) | S_028C74_FORCE_DST_ALPHA_1(force_alpha) |
                   S_028C74_MIP0_DEPTH(r->depth - 1) | S_028C74_RESOURCE_TYPE(r->resource_type) |
                   S_028C74_COLOR_SW_MODE(r->swizzle) | S_028C74_RB_ALIGNED(1) | S_028C74_PIPE_ALIGNED(1);
        // color6..14 are DCC/control/CMASK/FMASK/clear fields and stay disabled.
        d.color15 = S_0287A0_EPITCH(l->epitch);
    }
    *out = d; return R4AMD_STATUS_OK;
}
