/* Generated by R4LContractGen. Do not edit. */
#ifndef R4ENC_R4L_BINDING_H
#define R4ENC_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4EncRuntime {
    uint64_t address;
    uint64_t generation;
} R4EncRuntime;
_Static_assert(sizeof(R4EncRuntime) == 16u, "R4EncRuntime size mismatch");
_Static_assert(offsetof(R4EncRuntime, address) == 0u, "R4EncRuntime.address offset mismatch");
_Static_assert(offsetof(R4EncRuntime, generation) == 8u, "R4EncRuntime.generation offset mismatch");

typedef struct R4EncEncoder {
    uint64_t address;
    uint64_t generation;
} R4EncEncoder;
_Static_assert(sizeof(R4EncEncoder) == 16u, "R4EncEncoder size mismatch");
_Static_assert(offsetof(R4EncEncoder, address) == 0u, "R4EncEncoder.address offset mismatch");
_Static_assert(offsetof(R4EncEncoder, generation) == 8u, "R4EncEncoder.generation offset mismatch");

typedef struct R4EncStartup {
    uint32_t version;
    uint32_t size;
    uint64_t application;
    uint64_t memory_limit;
    uint32_t max_encoders;
    uint32_t thread_limit;
} R4EncStartup;
_Static_assert(sizeof(R4EncStartup) == 32u, "R4EncStartup size mismatch");
_Static_assert(offsetof(R4EncStartup, version) == 0u, "R4EncStartup.version offset mismatch");
_Static_assert(offsetof(R4EncStartup, size) == 4u, "R4EncStartup.size offset mismatch");
_Static_assert(offsetof(R4EncStartup, application) == 8u, "R4EncStartup.application offset mismatch");
_Static_assert(offsetof(R4EncStartup, memory_limit) == 16u, "R4EncStartup.memory_limit offset mismatch");
_Static_assert(offsetof(R4EncStartup, max_encoders) == 24u, "R4EncStartup.max_encoders offset mismatch");
_Static_assert(offsetof(R4EncStartup, thread_limit) == 28u, "R4EncStartup.thread_limit offset mismatch");

typedef struct R4EncCapsQuery {
    uint32_t version;
    uint32_t size;
    uint32_t backend;
    uint32_t adapter_id;
    uint32_t codec;
    uint32_t profile;
    uint32_t bit_depth;
    uint32_t chroma;
} R4EncCapsQuery;
_Static_assert(sizeof(R4EncCapsQuery) == 32u, "R4EncCapsQuery size mismatch");
_Static_assert(offsetof(R4EncCapsQuery, version) == 0u, "R4EncCapsQuery.version offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, size) == 4u, "R4EncCapsQuery.size offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, backend) == 8u, "R4EncCapsQuery.backend offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, adapter_id) == 12u, "R4EncCapsQuery.adapter_id offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, codec) == 16u, "R4EncCapsQuery.codec offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, profile) == 20u, "R4EncCapsQuery.profile offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, bit_depth) == 24u, "R4EncCapsQuery.bit_depth offset mismatch");
_Static_assert(offsetof(R4EncCapsQuery, chroma) == 28u, "R4EncCapsQuery.chroma offset mismatch");

typedef struct R4EncCaps {
    uint32_t version;
    uint32_t size;
    R4EncCapsQuery query;
    uint32_t min_width;
    uint32_t min_height;
    uint32_t max_width;
    uint32_t max_height;
    uint32_t max_level;
    uint32_t input_formats;
    uint32_t rate_modes;
    uint32_t max_pending_frames;
    uint32_t max_packet_leases;
    uint32_t flags;
    uint64_t max_packet_bytes;
    uint64_t device_generation;
    uint64_t reset_generation;
} R4EncCaps;
_Static_assert(sizeof(R4EncCaps) == 104u, "R4EncCaps size mismatch");
_Static_assert(offsetof(R4EncCaps, version) == 0u, "R4EncCaps.version offset mismatch");
_Static_assert(offsetof(R4EncCaps, size) == 4u, "R4EncCaps.size offset mismatch");
_Static_assert(offsetof(R4EncCaps, query) == 8u, "R4EncCaps.query offset mismatch");
_Static_assert(offsetof(R4EncCaps, min_width) == 40u, "R4EncCaps.min_width offset mismatch");
_Static_assert(offsetof(R4EncCaps, min_height) == 44u, "R4EncCaps.min_height offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_width) == 48u, "R4EncCaps.max_width offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_height) == 52u, "R4EncCaps.max_height offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_level) == 56u, "R4EncCaps.max_level offset mismatch");
_Static_assert(offsetof(R4EncCaps, input_formats) == 60u, "R4EncCaps.input_formats offset mismatch");
_Static_assert(offsetof(R4EncCaps, rate_modes) == 64u, "R4EncCaps.rate_modes offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_pending_frames) == 68u, "R4EncCaps.max_pending_frames offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_packet_leases) == 72u, "R4EncCaps.max_packet_leases offset mismatch");
_Static_assert(offsetof(R4EncCaps, flags) == 76u, "R4EncCaps.flags offset mismatch");
_Static_assert(offsetof(R4EncCaps, max_packet_bytes) == 80u, "R4EncCaps.max_packet_bytes offset mismatch");
_Static_assert(offsetof(R4EncCaps, device_generation) == 88u, "R4EncCaps.device_generation offset mismatch");
_Static_assert(offsetof(R4EncCaps, reset_generation) == 96u, "R4EncCaps.reset_generation offset mismatch");

typedef struct R4EncRate {
    uint32_t version;
    uint32_t size;
    uint32_t mode;
    uint32_t qp;
    uint32_t min_qp;
    uint32_t max_qp;
    uint64_t target_bps;
    uint64_t peak_bps;
    uint64_t buffer_bits;
} R4EncRate;
_Static_assert(sizeof(R4EncRate) == 48u, "R4EncRate size mismatch");
_Static_assert(offsetof(R4EncRate, version) == 0u, "R4EncRate.version offset mismatch");
_Static_assert(offsetof(R4EncRate, size) == 4u, "R4EncRate.size offset mismatch");
_Static_assert(offsetof(R4EncRate, mode) == 8u, "R4EncRate.mode offset mismatch");
_Static_assert(offsetof(R4EncRate, qp) == 12u, "R4EncRate.qp offset mismatch");
_Static_assert(offsetof(R4EncRate, min_qp) == 16u, "R4EncRate.min_qp offset mismatch");
_Static_assert(offsetof(R4EncRate, max_qp) == 20u, "R4EncRate.max_qp offset mismatch");
_Static_assert(offsetof(R4EncRate, target_bps) == 24u, "R4EncRate.target_bps offset mismatch");
_Static_assert(offsetof(R4EncRate, peak_bps) == 32u, "R4EncRate.peak_bps offset mismatch");
_Static_assert(offsetof(R4EncRate, buffer_bits) == 40u, "R4EncRate.buffer_bits offset mismatch");

typedef struct R4EncBuffer {
    uint32_t id;
    uint32_t reserved0;
    uint64_t generation;
} R4EncBuffer;
_Static_assert(sizeof(R4EncBuffer) == 16u, "R4EncBuffer size mismatch");
_Static_assert(offsetof(R4EncBuffer, id) == 0u, "R4EncBuffer.id offset mismatch");
_Static_assert(offsetof(R4EncBuffer, reserved0) == 4u, "R4EncBuffer.reserved0 offset mismatch");
_Static_assert(offsetof(R4EncBuffer, generation) == 8u, "R4EncBuffer.generation offset mismatch");

typedef struct R4EncFence {
    uint32_t slot;
    uint32_t adapter_id;
    uint64_t timeline;
    uint64_t point;
    uint64_t device_generation;
    uint64_t reset_generation;
} R4EncFence;
_Static_assert(sizeof(R4EncFence) == 40u, "R4EncFence size mismatch");
_Static_assert(offsetof(R4EncFence, slot) == 0u, "R4EncFence.slot offset mismatch");
_Static_assert(offsetof(R4EncFence, adapter_id) == 4u, "R4EncFence.adapter_id offset mismatch");
_Static_assert(offsetof(R4EncFence, timeline) == 8u, "R4EncFence.timeline offset mismatch");
_Static_assert(offsetof(R4EncFence, point) == 16u, "R4EncFence.point offset mismatch");
_Static_assert(offsetof(R4EncFence, device_generation) == 24u, "R4EncFence.device_generation offset mismatch");
_Static_assert(offsetof(R4EncFence, reset_generation) == 32u, "R4EncFence.reset_generation offset mismatch");

typedef struct R4EncColor {
    uint32_t version;
    uint32_t size;
    uint32_t primaries;
    uint32_t transfer;
    uint32_t range;
    uint32_t matrix;
    uint32_t chroma_location;
    uint32_t bit_depth;
    uint32_t reference_white;
    uint32_t peak;
    uint32_t black;
    uint32_t flags;
} R4EncColor;
_Static_assert(sizeof(R4EncColor) == 48u, "R4EncColor size mismatch");
_Static_assert(offsetof(R4EncColor, version) == 0u, "R4EncColor.version offset mismatch");
_Static_assert(offsetof(R4EncColor, size) == 4u, "R4EncColor.size offset mismatch");
_Static_assert(offsetof(R4EncColor, primaries) == 8u, "R4EncColor.primaries offset mismatch");
_Static_assert(offsetof(R4EncColor, transfer) == 12u, "R4EncColor.transfer offset mismatch");
_Static_assert(offsetof(R4EncColor, range) == 16u, "R4EncColor.range offset mismatch");
_Static_assert(offsetof(R4EncColor, matrix) == 20u, "R4EncColor.matrix offset mismatch");
_Static_assert(offsetof(R4EncColor, chroma_location) == 24u, "R4EncColor.chroma_location offset mismatch");
_Static_assert(offsetof(R4EncColor, bit_depth) == 28u, "R4EncColor.bit_depth offset mismatch");
_Static_assert(offsetof(R4EncColor, reference_white) == 32u, "R4EncColor.reference_white offset mismatch");
_Static_assert(offsetof(R4EncColor, peak) == 36u, "R4EncColor.peak offset mismatch");
_Static_assert(offsetof(R4EncColor, black) == 40u, "R4EncColor.black offset mismatch");
_Static_assert(offsetof(R4EncColor, flags) == 44u, "R4EncColor.flags offset mismatch");

typedef struct R4EncPlane {
    R4EncBuffer buffer;
    R4EncBuffer reference;
    uint64_t offset;
    uint64_t pitch;
    uint64_t row_bytes;
    uint32_t rows;
    uint32_t reserved;
} R4EncPlane;
_Static_assert(sizeof(R4EncPlane) == 64u, "R4EncPlane size mismatch");
_Static_assert(offsetof(R4EncPlane, buffer) == 0u, "R4EncPlane.buffer offset mismatch");
_Static_assert(offsetof(R4EncPlane, reference) == 16u, "R4EncPlane.reference offset mismatch");
_Static_assert(offsetof(R4EncPlane, offset) == 32u, "R4EncPlane.offset offset mismatch");
_Static_assert(offsetof(R4EncPlane, pitch) == 40u, "R4EncPlane.pitch offset mismatch");
_Static_assert(offsetof(R4EncPlane, row_bytes) == 48u, "R4EncPlane.row_bytes offset mismatch");
_Static_assert(offsetof(R4EncPlane, rows) == 56u, "R4EncPlane.rows offset mismatch");
_Static_assert(offsetof(R4EncPlane, reserved) == 60u, "R4EncPlane.reserved offset mismatch");

typedef struct R4EncConfig {
    uint32_t version;
    uint32_t size;
    R4EncCapsQuery query;
    uint64_t memory_limit;
    uint32_t width;
    uint32_t height;
    uint32_t fps_num;
    uint32_t fps_den;
    uint32_t pending_frames;
    uint32_t packet_leases;
    uint64_t max_packet_bytes;
    uint64_t work_timeout_ns;
    uint32_t gop_frames;
    uint32_t flags;
    R4EncRate rate;
    R4EncColor color;
} R4EncConfig;
_Static_assert(sizeof(R4EncConfig) == 192u, "R4EncConfig size mismatch");
_Static_assert(offsetof(R4EncConfig, version) == 0u, "R4EncConfig.version offset mismatch");
_Static_assert(offsetof(R4EncConfig, size) == 4u, "R4EncConfig.size offset mismatch");
_Static_assert(offsetof(R4EncConfig, query) == 8u, "R4EncConfig.query offset mismatch");
_Static_assert(offsetof(R4EncConfig, memory_limit) == 40u, "R4EncConfig.memory_limit offset mismatch");
_Static_assert(offsetof(R4EncConfig, width) == 48u, "R4EncConfig.width offset mismatch");
_Static_assert(offsetof(R4EncConfig, height) == 52u, "R4EncConfig.height offset mismatch");
_Static_assert(offsetof(R4EncConfig, fps_num) == 56u, "R4EncConfig.fps_num offset mismatch");
_Static_assert(offsetof(R4EncConfig, fps_den) == 60u, "R4EncConfig.fps_den offset mismatch");
_Static_assert(offsetof(R4EncConfig, pending_frames) == 64u, "R4EncConfig.pending_frames offset mismatch");
_Static_assert(offsetof(R4EncConfig, packet_leases) == 68u, "R4EncConfig.packet_leases offset mismatch");
_Static_assert(offsetof(R4EncConfig, max_packet_bytes) == 72u, "R4EncConfig.max_packet_bytes offset mismatch");
_Static_assert(offsetof(R4EncConfig, work_timeout_ns) == 80u, "R4EncConfig.work_timeout_ns offset mismatch");
_Static_assert(offsetof(R4EncConfig, gop_frames) == 88u, "R4EncConfig.gop_frames offset mismatch");
_Static_assert(offsetof(R4EncConfig, flags) == 92u, "R4EncConfig.flags offset mismatch");
_Static_assert(offsetof(R4EncConfig, rate) == 96u, "R4EncConfig.rate offset mismatch");
_Static_assert(offsetof(R4EncConfig, color) == 144u, "R4EncConfig.color offset mismatch");

typedef struct R4EncFrame {
    uint32_t version;
    uint32_t size;
    uint64_t stream_generation;
    uint64_t tag;
    int64_t pts_ns;
    uint64_t duration_ns;
    uint32_t format;
    uint32_t plane_count;
    R4EncPlane plane0;
    R4EncPlane plane1;
    R4EncPlane plane2;
    R4EncFence ready;
    uint32_t flags;
    uint32_t reserved;
} R4EncFrame;
_Static_assert(sizeof(R4EncFrame) == 288u, "R4EncFrame size mismatch");
_Static_assert(offsetof(R4EncFrame, version) == 0u, "R4EncFrame.version offset mismatch");
_Static_assert(offsetof(R4EncFrame, size) == 4u, "R4EncFrame.size offset mismatch");
_Static_assert(offsetof(R4EncFrame, stream_generation) == 8u, "R4EncFrame.stream_generation offset mismatch");
_Static_assert(offsetof(R4EncFrame, tag) == 16u, "R4EncFrame.tag offset mismatch");
_Static_assert(offsetof(R4EncFrame, pts_ns) == 24u, "R4EncFrame.pts_ns offset mismatch");
_Static_assert(offsetof(R4EncFrame, duration_ns) == 32u, "R4EncFrame.duration_ns offset mismatch");
_Static_assert(offsetof(R4EncFrame, format) == 40u, "R4EncFrame.format offset mismatch");
_Static_assert(offsetof(R4EncFrame, plane_count) == 44u, "R4EncFrame.plane_count offset mismatch");
_Static_assert(offsetof(R4EncFrame, plane0) == 48u, "R4EncFrame.plane0 offset mismatch");
_Static_assert(offsetof(R4EncFrame, plane1) == 112u, "R4EncFrame.plane1 offset mismatch");
_Static_assert(offsetof(R4EncFrame, plane2) == 176u, "R4EncFrame.plane2 offset mismatch");
_Static_assert(offsetof(R4EncFrame, ready) == 240u, "R4EncFrame.ready offset mismatch");
_Static_assert(offsetof(R4EncFrame, flags) == 280u, "R4EncFrame.flags offset mismatch");
_Static_assert(offsetof(R4EncFrame, reserved) == 284u, "R4EncFrame.reserved offset mismatch");

typedef struct R4EncLease {
    R4EncEncoder encoder;
    uint64_t token;
    uint64_t stream_generation;
} R4EncLease;
_Static_assert(sizeof(R4EncLease) == 32u, "R4EncLease size mismatch");
_Static_assert(offsetof(R4EncLease, encoder) == 0u, "R4EncLease.encoder offset mismatch");
_Static_assert(offsetof(R4EncLease, token) == 16u, "R4EncLease.token offset mismatch");
_Static_assert(offsetof(R4EncLease, stream_generation) == 24u, "R4EncLease.stream_generation offset mismatch");

typedef struct R4EncPacket {
    uint32_t version;
    uint32_t size;
    R4EncLease lease;
    uint64_t tag;
    int64_t pts_ns;
    int64_t dts_ns;
    uint64_t duration_ns;
    uint64_t data_address;
    uint64_t data_bytes;
    uint32_t flags;
    int32_t result;
} R4EncPacket;
_Static_assert(sizeof(R4EncPacket) == 96u, "R4EncPacket size mismatch");
_Static_assert(offsetof(R4EncPacket, version) == 0u, "R4EncPacket.version offset mismatch");
_Static_assert(offsetof(R4EncPacket, size) == 4u, "R4EncPacket.size offset mismatch");
_Static_assert(offsetof(R4EncPacket, lease) == 8u, "R4EncPacket.lease offset mismatch");
_Static_assert(offsetof(R4EncPacket, tag) == 40u, "R4EncPacket.tag offset mismatch");
_Static_assert(offsetof(R4EncPacket, pts_ns) == 48u, "R4EncPacket.pts_ns offset mismatch");
_Static_assert(offsetof(R4EncPacket, dts_ns) == 56u, "R4EncPacket.dts_ns offset mismatch");
_Static_assert(offsetof(R4EncPacket, duration_ns) == 64u, "R4EncPacket.duration_ns offset mismatch");
_Static_assert(offsetof(R4EncPacket, data_address) == 72u, "R4EncPacket.data_address offset mismatch");
_Static_assert(offsetof(R4EncPacket, data_bytes) == 80u, "R4EncPacket.data_bytes offset mismatch");
_Static_assert(offsetof(R4EncPacket, flags) == 88u, "R4EncPacket.flags offset mismatch");
_Static_assert(offsetof(R4EncPacket, result) == 92u, "R4EncPacket.result offset mismatch");

typedef struct R4EncControl {
    uint32_t version;
    uint32_t size;
    uint64_t request_id;
    uint32_t operation;
    uint32_t reserved;
} R4EncControl;
_Static_assert(sizeof(R4EncControl) == 24u, "R4EncControl size mismatch");
_Static_assert(offsetof(R4EncControl, version) == 0u, "R4EncControl.version offset mismatch");
_Static_assert(offsetof(R4EncControl, size) == 4u, "R4EncControl.size offset mismatch");
_Static_assert(offsetof(R4EncControl, request_id) == 8u, "R4EncControl.request_id offset mismatch");
_Static_assert(offsetof(R4EncControl, operation) == 16u, "R4EncControl.operation offset mismatch");
_Static_assert(offsetof(R4EncControl, reserved) == 20u, "R4EncControl.reserved offset mismatch");

typedef struct R4EncState {
    uint32_t version;
    uint32_t size;
    uint64_t stream_generation;
    uint64_t pending_request;
    uint64_t completed_request;
    uint64_t memory_bytes;
    uint64_t accepted_frames;
    uint64_t encoded_frames;
    uint64_t skipped_frames;
    uint64_t output_bytes;
    uint32_t phase;
    uint32_t queued_frames;
    uint32_t ready_packets;
    uint32_t leased_packets;
    int32_t last_error;
    uint32_t reserved;
} R4EncState;
_Static_assert(sizeof(R4EncState) == 96u, "R4EncState size mismatch");
_Static_assert(offsetof(R4EncState, version) == 0u, "R4EncState.version offset mismatch");
_Static_assert(offsetof(R4EncState, size) == 4u, "R4EncState.size offset mismatch");
_Static_assert(offsetof(R4EncState, stream_generation) == 8u, "R4EncState.stream_generation offset mismatch");
_Static_assert(offsetof(R4EncState, pending_request) == 16u, "R4EncState.pending_request offset mismatch");
_Static_assert(offsetof(R4EncState, completed_request) == 24u, "R4EncState.completed_request offset mismatch");
_Static_assert(offsetof(R4EncState, memory_bytes) == 32u, "R4EncState.memory_bytes offset mismatch");
_Static_assert(offsetof(R4EncState, accepted_frames) == 40u, "R4EncState.accepted_frames offset mismatch");
_Static_assert(offsetof(R4EncState, encoded_frames) == 48u, "R4EncState.encoded_frames offset mismatch");
_Static_assert(offsetof(R4EncState, skipped_frames) == 56u, "R4EncState.skipped_frames offset mismatch");
_Static_assert(offsetof(R4EncState, output_bytes) == 64u, "R4EncState.output_bytes offset mismatch");
_Static_assert(offsetof(R4EncState, phase) == 72u, "R4EncState.phase offset mismatch");
_Static_assert(offsetof(R4EncState, queued_frames) == 76u, "R4EncState.queued_frames offset mismatch");
_Static_assert(offsetof(R4EncState, ready_packets) == 80u, "R4EncState.ready_packets offset mismatch");
_Static_assert(offsetof(R4EncState, leased_packets) == 84u, "R4EncState.leased_packets offset mismatch");
_Static_assert(offsetof(R4EncState, last_error) == 88u, "R4EncState.last_error offset mismatch");
_Static_assert(offsetof(R4EncState, reserved) == 92u, "R4EncState.reserved offset mismatch");

#define R4ENC_OK ((int32_t)0)
#define R4ENC_AGAIN ((int32_t)1)
#define R4ENC_EOS ((int32_t)2)
#define R4ENC_BACKEND_SOFTWARE ((uint32_t)0)
#define R4ENC_BACKEND_NVIDIA ((uint32_t)1)
#define R4ENC_CODEC_H264 ((uint32_t)1)
#define R4ENC_PROFILE_DEFAULT ((uint32_t)0)
#define R4ENC_PROFILE_H264_BASELINE ((uint32_t)66)
#define R4ENC_CHROMA_420 ((uint32_t)1)
#define R4ENC_FORMAT_NV12 ((uint32_t)1)
#define R4ENC_FORMAT_YUV420P ((uint32_t)3)
#define R4ENC_FORMATS_NV12 ((uint32_t)1)
#define R4ENC_FORMATS_YUV420P ((uint32_t)4)
#define R4ENC_RATE_CQP ((uint32_t)0)
#define R4ENC_RATE_CBR ((uint32_t)1)
#define R4ENC_RATE_VBR ((uint32_t)2)
#define R4ENC_RATES_CQP ((uint32_t)1)
#define R4ENC_RATES_CBR ((uint32_t)2)
#define R4ENC_RATES_VBR ((uint32_t)4)
#define R4ENC_CONFIG_ALLOW_SKIP ((uint32_t)1)
#define R4ENC_FRAME_FORCE_IDR ((uint32_t)1)
#define R4ENC_PACKET_KEY ((uint32_t)1)
#define R4ENC_PACKET_CONFIG ((uint32_t)2)
#define R4ENC_PACKET_SKIPPED ((uint32_t)4)
#define R4ENC_SKIP_RATE_CONTROL ((uint32_t)1)
#define R4ENC_PHASE_OPEN ((uint32_t)0)
#define R4ENC_PHASE_DRAINING ((uint32_t)1)
#define R4ENC_PHASE_DRAINED ((uint32_t)2)
#define R4ENC_PHASE_ABORTING ((uint32_t)3)
#define R4ENC_PHASE_CLOSING ((uint32_t)4)
#define R4ENC_PHASE_CLOSED ((uint32_t)5)
#define R4ENC_PHASE_FAILED ((uint32_t)6)
#define R4ENC_CONTROL_QUERY ((uint32_t)0)
#define R4ENC_CONTROL_DRAIN ((uint32_t)1)
#define R4ENC_CONTROL_ABORT ((uint32_t)2)
#define R4ENC_CONTROL_CLOSE ((uint32_t)3)
#define R4ENC_COLOR_REFERENCE_WHITE ((uint32_t)1)
#define R4ENC_COLOR_LUMINANCE ((uint32_t)2)
#define R4ENC_COLOR_UNSPECIFIED ((uint32_t)2)
#define R4ENC_CHROMA_UNSPECIFIED ((uint32_t)0)
#define R4ENC_CHROMA_LEFT ((uint32_t)1)
#define R4ENC_CHROMA_CENTER ((uint32_t)2)
#define R4ENC_CHROMA_TOP_LEFT ((uint32_t)3)
#define R4ENC_ERROR_CANCELLED ((int32_t)-10)
#define R4ENC_BACKEND_AMD ((uint32_t)2)
#define R4ENC_CODEC_HEVC ((uint32_t)2)
#define R4ENC_CODEC_VP9 ((uint32_t)3)
#define R4ENC_CODEC_MPEG2 ((uint32_t)4)
#define R4ENC_CODEC_VC1 ((uint32_t)5)
#define R4ENC_CODEC_JPEG ((uint32_t)6)
#define R4ENC_CODEC_AV1 ((uint32_t)7)
#define R4ENC_CODEC_MPEG4_PART2 ((uint32_t)8)
#define R4ENC_PROFILE_HEVC_MAIN ((uint32_t)1)
#define R4ENC_PROFILE_HEVC_MAIN10 ((uint32_t)2)
#define R4ENC_PROFILE_VP9_0 ((uint32_t)0)
#define R4ENC_PROFILE_VP9_2 ((uint32_t)2)
#define R4ENC_PROFILE_MPEG2_SIMPLE ((uint32_t)5)
#define R4ENC_PROFILE_MPEG2_MAIN ((uint32_t)4)
#define R4ENC_PROFILE_VC1_SIMPLE ((uint32_t)0)
#define R4ENC_PROFILE_VC1_MAIN ((uint32_t)1)
#define R4ENC_PROFILE_VC1_ADVANCED ((uint32_t)3)
#define R4ENC_PROFILE_JPEG_BASELINE ((uint32_t)0)
#define R4ENC_ERROR_INVALID ((int32_t)-1)
#define R4ENC_ERROR_UNSUPPORTED ((int32_t)-2)
#define R4ENC_ERROR_BUSY ((int32_t)-3)
#define R4ENC_ERROR_NO_MEMORY ((int32_t)-4)
#define R4ENC_ERROR_STALE ((int32_t)-5)
#define R4ENC_ERROR_ENCODE ((int32_t)-6)
#define R4ENC_ERROR_DEVICE_LOST ((int32_t)-7)
#define R4ENC_ERROR_CLOSED ((int32_t)-8)
#define R4ENC_ERROR_INTERNAL ((int32_t)-9)

#define R4ENC_ENCODE_V1_EXPORT_NAME "ENCODE_V1"
#define R4ENC_ENCODE_V1_ABI_MAJOR 1u
#define R4ENC_ENCODE_V1_REVISION 1u
#define R4ENC_ENCODE_V1_INTERFACE_ID_LO 0x313030434e453452ull
#define R4ENC_ENCODE_V1_INTERFACE_ID_HI 0x313045444f434e45ull
#define R4ENC_ENCODE_V1_TABLE_SIZE 104u
#define R4ENC_ENCODE_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4ENC_ENCODE_V1_TABLE_SIZE, R4ENC_ENCODE_V1_ABI_MAJOR, R4ENC_ENCODE_V1_REVISION, R4ENC_ENCODE_V1_INTERFACE_ID_LO, R4ENC_ENCODE_V1_INTERFACE_ID_HI }
typedef int32_t (*R4EncEncodeV1OpenFn)(const R4EncStartup * startup, R4EncRuntime * runtime);
typedef int32_t (*R4EncEncodeV1QueryCapsFn)(const R4EncRuntime * runtime, const R4EncCapsQuery * query, R4EncCaps * output);
typedef int32_t (*R4EncEncodeV1CreateFn)(const R4EncRuntime * runtime, const R4EncConfig * config, R4EncEncoder * encoder);
typedef int32_t (*R4EncEncodeV1SendFn)(const R4EncEncoder * encoder, const R4EncFrame * frame);
typedef int32_t (*R4EncEncodeV1ReceiveFn)(const R4EncEncoder * encoder, R4EncPacket * packet);
typedef int32_t (*R4EncEncodeV1ReleaseFn)(const R4EncLease * lease);
typedef int32_t (*R4EncEncodeV1ControlFn)(const R4EncEncoder * encoder, const R4EncControl * request, R4EncState * state);
typedef int32_t (*R4EncEncodeV1DestroyFn)(const R4EncEncoder * encoder);
typedef int32_t (*R4EncEncodeV1FinishFn)(const R4EncRuntime * runtime, uint64_t timeout_ns);
typedef struct R4EncEncodeV1 {
    R4LInterfaceHeader header;
    R4EncEncodeV1OpenFn open;
    R4EncEncodeV1QueryCapsFn query_caps;
    R4EncEncodeV1CreateFn create;
    R4EncEncodeV1SendFn send;
    R4EncEncodeV1ReceiveFn receive;
    R4EncEncodeV1ReleaseFn release;
    R4EncEncodeV1ControlFn control;
    R4EncEncodeV1DestroyFn destroy;
    R4EncEncodeV1FinishFn finish;
} R4EncEncodeV1;
_Static_assert(sizeof(R4EncEncodeV1) == 104u, "R4EncEncodeV1 size mismatch");
_Static_assert(offsetof(R4EncEncodeV1, open) == 32u, "R4EncEncodeV1.open offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, query_caps) == 40u, "R4EncEncodeV1.query_caps offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, create) == 48u, "R4EncEncodeV1.create offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, send) == 56u, "R4EncEncodeV1.send offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, receive) == 64u, "R4EncEncodeV1.receive offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, release) == 72u, "R4EncEncodeV1.release offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, control) == 80u, "R4EncEncodeV1.control offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, destroy) == 88u, "R4EncEncodeV1.destroy offset mismatch");
_Static_assert(offsetof(R4EncEncodeV1, finish) == 96u, "R4EncEncodeV1.finish offset mismatch");
typedef struct R4EncEncodeV1Client { const R4LInterfaceHeader *header; } R4EncEncodeV1Client;

static inline int32_t r4enc_encode_v1_init(const R4XStartContext *ctx, R4EncEncodeV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4ENC", "ENCODE_V1");
    const R4LInterfaceExpectation expected = { 0x313030434e453452ull, 0x313045444f434e45ull, 1u, 1u, 104u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 80u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 88u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 96u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4enc_open(R4EncEncodeV1Client *client, const R4EncStartup * startup, R4EncRuntime * runtime) {
    R4EncEncodeV1OpenFn function = (R4EncEncodeV1OpenFn)r4l_slot_address(client->header, 32u);
    return function(startup, runtime);
}

static inline int32_t r4enc_query_caps(R4EncEncodeV1Client *client, const R4EncRuntime * runtime, const R4EncCapsQuery * query, R4EncCaps * output) {
    R4EncEncodeV1QueryCapsFn function = (R4EncEncodeV1QueryCapsFn)r4l_slot_address(client->header, 40u);
    return function(runtime, query, output);
}

static inline int32_t r4enc_create(R4EncEncodeV1Client *client, const R4EncRuntime * runtime, const R4EncConfig * config, R4EncEncoder * encoder) {
    R4EncEncodeV1CreateFn function = (R4EncEncodeV1CreateFn)r4l_slot_address(client->header, 48u);
    return function(runtime, config, encoder);
}

static inline int32_t r4enc_send(R4EncEncodeV1Client *client, const R4EncEncoder * encoder, const R4EncFrame * frame) {
    R4EncEncodeV1SendFn function = (R4EncEncodeV1SendFn)r4l_slot_address(client->header, 56u);
    return function(encoder, frame);
}

static inline int32_t r4enc_receive(R4EncEncodeV1Client *client, const R4EncEncoder * encoder, R4EncPacket * packet) {
    R4EncEncodeV1ReceiveFn function = (R4EncEncodeV1ReceiveFn)r4l_slot_address(client->header, 64u);
    return function(encoder, packet);
}

static inline int32_t r4enc_release(R4EncEncodeV1Client *client, const R4EncLease * lease) {
    R4EncEncodeV1ReleaseFn function = (R4EncEncodeV1ReleaseFn)r4l_slot_address(client->header, 72u);
    return function(lease);
}

static inline int32_t r4enc_control(R4EncEncodeV1Client *client, const R4EncEncoder * encoder, const R4EncControl * request, R4EncState * state) {
    R4EncEncodeV1ControlFn function = (R4EncEncodeV1ControlFn)r4l_slot_address(client->header, 80u);
    return function(encoder, request, state);
}

static inline int32_t r4enc_destroy(R4EncEncodeV1Client *client, const R4EncEncoder * encoder) {
    R4EncEncodeV1DestroyFn function = (R4EncEncodeV1DestroyFn)r4l_slot_address(client->header, 88u);
    return function(encoder);
}

static inline int32_t r4enc_finish(R4EncEncodeV1Client *client, const R4EncRuntime * runtime, uint64_t timeout_ns) {
    R4EncEncodeV1FinishFn function = (R4EncEncodeV1FinishFn)r4l_slot_address(client->header, 96u);
    return function(runtime, timeout_ns);
}

#endif
