/* Generated by R4LContractGen. Do not edit. */
#ifndef R4STD_R4L_BINDING_H
#define R4STD_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4StdTextInfo {
    uint64_t content_offset;
    uint64_t content_length;
    uint64_t canonical_length;
    uint64_t scalar_count;
    uint32_t encoding;
    uint32_t line_ending;
} R4StdTextInfo;
_Static_assert(sizeof(R4StdTextInfo) == 40u, "R4StdTextInfo size mismatch");
_Static_assert(offsetof(R4StdTextInfo, content_offset) == 0u, "R4StdTextInfo.content_offset offset mismatch");
_Static_assert(offsetof(R4StdTextInfo, content_length) == 8u, "R4StdTextInfo.content_length offset mismatch");
_Static_assert(offsetof(R4StdTextInfo, canonical_length) == 16u, "R4StdTextInfo.canonical_length offset mismatch");
_Static_assert(offsetof(R4StdTextInfo, scalar_count) == 24u, "R4StdTextInfo.scalar_count offset mismatch");
_Static_assert(offsetof(R4StdTextInfo, encoding) == 32u, "R4StdTextInfo.encoding offset mismatch");
_Static_assert(offsetof(R4StdTextInfo, line_ending) == 36u, "R4StdTextInfo.line_ending offset mismatch");

typedef struct R4StdEntryRange {
    uint64_t key_offset;
    uint64_t key_length;
    uint64_t value_offset;
    uint64_t value_length;
} R4StdEntryRange;
_Static_assert(sizeof(R4StdEntryRange) == 32u, "R4StdEntryRange size mismatch");
_Static_assert(offsetof(R4StdEntryRange, key_offset) == 0u, "R4StdEntryRange.key_offset offset mismatch");
_Static_assert(offsetof(R4StdEntryRange, key_length) == 8u, "R4StdEntryRange.key_length offset mismatch");
_Static_assert(offsetof(R4StdEntryRange, value_offset) == 16u, "R4StdEntryRange.value_offset offset mismatch");
_Static_assert(offsetof(R4StdEntryRange, value_length) == 24u, "R4StdEntryRange.value_length offset mismatch");

typedef struct R4StdWritebackPolicy {
    uint32_t durability;
    uint32_t reserved;
    uint64_t save_delay_ticks;
    uint64_t retry_delay_ticks;
} R4StdWritebackPolicy;
_Static_assert(sizeof(R4StdWritebackPolicy) == 24u, "R4StdWritebackPolicy size mismatch");
_Static_assert(offsetof(R4StdWritebackPolicy, durability) == 0u, "R4StdWritebackPolicy.durability offset mismatch");
_Static_assert(offsetof(R4StdWritebackPolicy, reserved) == 4u, "R4StdWritebackPolicy.reserved offset mismatch");
_Static_assert(offsetof(R4StdWritebackPolicy, save_delay_ticks) == 8u, "R4StdWritebackPolicy.save_delay_ticks offset mismatch");
_Static_assert(offsetof(R4StdWritebackPolicy, retry_delay_ticks) == 16u, "R4StdWritebackPolicy.retry_delay_ticks offset mismatch");

typedef struct R4StdWriteback {
    uint32_t durability;
    uint32_t dirty;
    uint64_t save_delay_ticks;
    uint64_t retry_delay_ticks;
    uint64_t due_tick;
    uint32_t failures;
    int32_t last_result;
    uint32_t failure_reported;
    uint32_t reserved;
} R4StdWriteback;
_Static_assert(sizeof(R4StdWriteback) == 48u, "R4StdWriteback size mismatch");
_Static_assert(offsetof(R4StdWriteback, durability) == 0u, "R4StdWriteback.durability offset mismatch");
_Static_assert(offsetof(R4StdWriteback, dirty) == 4u, "R4StdWriteback.dirty offset mismatch");
_Static_assert(offsetof(R4StdWriteback, save_delay_ticks) == 8u, "R4StdWriteback.save_delay_ticks offset mismatch");
_Static_assert(offsetof(R4StdWriteback, retry_delay_ticks) == 16u, "R4StdWriteback.retry_delay_ticks offset mismatch");
_Static_assert(offsetof(R4StdWriteback, due_tick) == 24u, "R4StdWriteback.due_tick offset mismatch");
_Static_assert(offsetof(R4StdWriteback, failures) == 32u, "R4StdWriteback.failures offset mismatch");
_Static_assert(offsetof(R4StdWriteback, last_result) == 36u, "R4StdWriteback.last_result offset mismatch");
_Static_assert(offsetof(R4StdWriteback, failure_reported) == 40u, "R4StdWriteback.failure_reported offset mismatch");
_Static_assert(offsetof(R4StdWriteback, reserved) == 44u, "R4StdWriteback.reserved offset mismatch");

typedef struct R4StdWritebackFlush {
    uint32_t action;
    uint32_t first_failure;
    uint32_t recovered_after_failure;
    int32_t result_code;
} R4StdWritebackFlush;
_Static_assert(sizeof(R4StdWritebackFlush) == 16u, "R4StdWritebackFlush size mismatch");
_Static_assert(offsetof(R4StdWritebackFlush, action) == 0u, "R4StdWritebackFlush.action offset mismatch");
_Static_assert(offsetof(R4StdWritebackFlush, first_failure) == 4u, "R4StdWritebackFlush.first_failure offset mismatch");
_Static_assert(offsetof(R4StdWritebackFlush, recovered_after_failure) == 8u, "R4StdWritebackFlush.recovered_after_failure offset mismatch");
_Static_assert(offsetof(R4StdWritebackFlush, result_code) == 12u, "R4StdWritebackFlush.result_code offset mismatch");

typedef struct R4StdDateTime {
    uint16_t year;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    uint8_t reserved;
} R4StdDateTime;
_Static_assert(sizeof(R4StdDateTime) == 8u, "R4StdDateTime size mismatch");
_Static_assert(offsetof(R4StdDateTime, year) == 0u, "R4StdDateTime.year offset mismatch");
_Static_assert(offsetof(R4StdDateTime, month) == 2u, "R4StdDateTime.month offset mismatch");
_Static_assert(offsetof(R4StdDateTime, day) == 3u, "R4StdDateTime.day offset mismatch");
_Static_assert(offsetof(R4StdDateTime, hour) == 4u, "R4StdDateTime.hour offset mismatch");
_Static_assert(offsetof(R4StdDateTime, minute) == 5u, "R4StdDateTime.minute offset mismatch");
_Static_assert(offsetof(R4StdDateTime, second) == 6u, "R4StdDateTime.second offset mismatch");
_Static_assert(offsetof(R4StdDateTime, reserved) == 7u, "R4StdDateTime.reserved offset mismatch");

typedef struct R4StdShiftedDateTime {
    uint16_t year;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    uint8_t reserved;
    int32_t day_delta;
} R4StdShiftedDateTime;
_Static_assert(sizeof(R4StdShiftedDateTime) == 12u, "R4StdShiftedDateTime size mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, year) == 0u, "R4StdShiftedDateTime.year offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, month) == 2u, "R4StdShiftedDateTime.month offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, day) == 3u, "R4StdShiftedDateTime.day offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, hour) == 4u, "R4StdShiftedDateTime.hour offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, minute) == 5u, "R4StdShiftedDateTime.minute offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, second) == 6u, "R4StdShiftedDateTime.second offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, reserved) == 7u, "R4StdShiftedDateTime.reserved offset mismatch");
_Static_assert(offsetof(R4StdShiftedDateTime, day_delta) == 8u, "R4StdShiftedDateTime.day_delta offset mismatch");

typedef struct R4StdTimeState {
    uint16_t year;
    uint8_t month;
    uint8_t day;
    uint8_t hour;
    uint8_t minute;
    uint8_t second;
    uint8_t weekday;
    uint32_t seconds_since_midnight;
    uint32_t valid;
} R4StdTimeState;
_Static_assert(sizeof(R4StdTimeState) == 16u, "R4StdTimeState size mismatch");
_Static_assert(offsetof(R4StdTimeState, year) == 0u, "R4StdTimeState.year offset mismatch");
_Static_assert(offsetof(R4StdTimeState, month) == 2u, "R4StdTimeState.month offset mismatch");
_Static_assert(offsetof(R4StdTimeState, day) == 3u, "R4StdTimeState.day offset mismatch");
_Static_assert(offsetof(R4StdTimeState, hour) == 4u, "R4StdTimeState.hour offset mismatch");
_Static_assert(offsetof(R4StdTimeState, minute) == 5u, "R4StdTimeState.minute offset mismatch");
_Static_assert(offsetof(R4StdTimeState, second) == 6u, "R4StdTimeState.second offset mismatch");
_Static_assert(offsetof(R4StdTimeState, weekday) == 7u, "R4StdTimeState.weekday offset mismatch");
_Static_assert(offsetof(R4StdTimeState, seconds_since_midnight) == 8u, "R4StdTimeState.seconds_since_midnight offset mismatch");
_Static_assert(offsetof(R4StdTimeState, valid) == 12u, "R4StdTimeState.valid offset mismatch");

typedef struct R4StdUtcTime {
    int64_t seconds_since_unix_epoch;
    uint32_t nanosecond;
    uint32_t reserved;
} R4StdUtcTime;
_Static_assert(sizeof(R4StdUtcTime) == 16u, "R4StdUtcTime size mismatch");
_Static_assert(offsetof(R4StdUtcTime, seconds_since_unix_epoch) == 0u, "R4StdUtcTime.seconds_since_unix_epoch offset mismatch");
_Static_assert(offsetof(R4StdUtcTime, nanosecond) == 8u, "R4StdUtcTime.nanosecond offset mismatch");
_Static_assert(offsetof(R4StdUtcTime, reserved) == 12u, "R4StdUtcTime.reserved offset mismatch");

typedef struct R4StdClockTime {
    uint8_t hours;
    uint8_t minutes;
    uint8_t seconds;
    uint8_t reserved;
} R4StdClockTime;
_Static_assert(sizeof(R4StdClockTime) == 4u, "R4StdClockTime size mismatch");
_Static_assert(offsetof(R4StdClockTime, hours) == 0u, "R4StdClockTime.hours offset mismatch");
_Static_assert(offsetof(R4StdClockTime, minutes) == 1u, "R4StdClockTime.minutes offset mismatch");
_Static_assert(offsetof(R4StdClockTime, seconds) == 2u, "R4StdClockTime.seconds offset mismatch");
_Static_assert(offsetof(R4StdClockTime, reserved) == 3u, "R4StdClockTime.reserved offset mismatch");

typedef struct R4StdTimeConfig {
    uint32_t timezone_index;
    uint32_t clock_format;
} R4StdTimeConfig;
_Static_assert(sizeof(R4StdTimeConfig) == 8u, "R4StdTimeConfig size mismatch");
_Static_assert(offsetof(R4StdTimeConfig, timezone_index) == 0u, "R4StdTimeConfig.timezone_index offset mismatch");
_Static_assert(offsetof(R4StdTimeConfig, clock_format) == 4u, "R4StdTimeConfig.clock_format offset mismatch");

#define R4STD_STATUS_OK ((int32_t)0)
#define R4STD_STATUS_NOT_FOUND ((int32_t)1)
#define R4STD_STATUS_END ((int32_t)2)
#define R4STD_STATUS_ATTEMPT ((int32_t)3)
#define R4STD_TEXT_KIND_UTF8 ((uint32_t)1)
#define R4STD_TEXT_KIND_UI ((uint32_t)2)
#define R4STD_TEXT_KIND_SYSTEM ((uint32_t)3)
#define R4STD_TEXT_KIND_DOCUMENT ((uint32_t)4)
#define R4STD_TEXT_WRITE_CANONICAL ((uint32_t)1)
#define R4STD_TEXT_WRITE_EXACT ((uint32_t)2)
#define R4STD_ENCODING_BYTES ((uint32_t)0)
#define R4STD_ENCODING_UTF8 ((uint32_t)1)
#define R4STD_ENCODING_UTF8_BOM ((uint32_t)2)
#define R4STD_LINE_ENDING_NONE ((uint32_t)0)
#define R4STD_LINE_ENDING_LF ((uint32_t)1)
#define R4STD_LINE_ENDING_CRLF ((uint32_t)2)
#define R4STD_LINE_ENDING_MIXED ((uint32_t)3)
#define R4STD_SCALAR_BOOL ((uint32_t)1)
#define R4STD_SCALAR_U32 ((uint32_t)2)
#define R4STD_SCALAR_I32 ((uint32_t)3)
#define R4STD_SCALAR_RGB24 ((uint32_t)4)
#define R4STD_WRITER_HEADER ((uint32_t)1)
#define R4STD_WRITER_COMMENT ((uint32_t)2)
#define R4STD_WRITER_PAIR ((uint32_t)3)
#define R4STD_WRITER_BOOL ((uint32_t)4)
#define R4STD_WRITER_U32 ((uint32_t)5)
#define R4STD_WRITER_I32 ((uint32_t)6)
#define R4STD_WRITER_RGB24 ((uint32_t)7)
#define R4STD_DURABILITY_LAZY ((uint32_t)0)
#define R4STD_DURABILITY_SOON ((uint32_t)1)
#define R4STD_DURABILITY_SYNC ((uint32_t)2)
#define R4STD_WRITEBACK_IDLE ((uint32_t)0)
#define R4STD_WRITEBACK_DEFERRED ((uint32_t)1)
#define R4STD_WRITEBACK_SAVED ((uint32_t)2)
#define R4STD_WRITEBACK_FAILED ((uint32_t)3)
#define R4STD_DATE_FORMAT_DATE_ISO ((uint32_t)1)
#define R4STD_DATE_FORMAT_DATETIME_ISO ((uint32_t)2)
#define R4STD_DATE_FORMAT_DATETIME_MINUTE ((uint32_t)3)
#define R4STD_DATE_PARSE_DATE ((uint32_t)1)
#define R4STD_DATE_PARSE_TIME ((uint32_t)2)
#define R4STD_DATE_PARSE_DATETIME ((uint32_t)3)
#define R4STD_FAT_DECODE_DATE ((uint32_t)1)
#define R4STD_FAT_DECODE_DATETIME ((uint32_t)2)
#define R4STD_TIME_FORMAT_DISPLAY ((uint32_t)1)
#define R4STD_TIME_FORMAT_HM ((uint32_t)2)
#define R4STD_TIME_FORMAT_24H ((uint32_t)3)
#define R4STD_CONFIG_KIND_STRING ((uint32_t)1)
#define R4STD_CONFIG_KIND_BOOL ((uint32_t)2)
#define R4STD_CONFIG_KIND_U32 ((uint32_t)3)
#define R4STD_CONFIG_KIND_I32 ((uint32_t)4)
#define R4STD_CONFIG_KIND_RGB24 ((uint32_t)5)
#define R4STD_ENSURE_DIRS_SYSTEM ((uint32_t)1)
#define R4STD_ENSURE_DIRS_APPS ((uint32_t)2)
#define R4STD_ENSURE_DIRS_DESKTOP ((uint32_t)3)
#define R4STD_CURRENT_FORMAT_VERSION ((uint32_t)1)
#define R4STD_MAX_FILE_BYTES ((uint32_t)4096)
#define R4STD_MAX_OUTPUT_BYTES ((uint32_t)4096)
#define R4STD_ZONE_COUNT ((uint32_t)38)
#define R4STD_ZONE_ID_MAX ((uint32_t)31)
#define R4STD_ZONE_LABEL_MAX ((uint32_t)39)
#define R4STD_UTC_INDEX ((uint32_t)13)
#define R4STD_SECONDS_PER_DAY ((uint32_t)86400)
#define R4STD_CONFIG_RESULT_OK ((int32_t)0)
#define R4STD_CONFIG_RESULT_DEFAULTED ((int32_t)1)
#define R4STD_CONFIG_RESULT_CREATED ((int32_t)2)
#define R4STD_CONFIG_RESULT_RECOVERED ((int32_t)3)
#define R4STD_STATUS_INVALID_ARGUMENT ((int32_t)-100)
#define R4STD_STATUS_BUFFER_TOO_SMALL ((int32_t)-101)
#define R4STD_STATUS_INVALID_TEXT ((int32_t)-102)
#define R4STD_STATUS_INVALID_VALUE ((int32_t)-103)
#define R4STD_STATUS_UNAVAILABLE ((int32_t)-104)
#define R4STD_CONFIG_ERROR_INVALID_PATH ((int32_t)-1)
#define R4STD_CONFIG_ERROR_INVALID_KEY ((int32_t)-2)
#define R4STD_CONFIG_ERROR_BUFFER_TOO_SMALL ((int32_t)-3)
#define R4STD_CONFIG_ERROR_WRITE_FAILED ((int32_t)-4)
#define R4STD_CONFIG_ERROR_RENAME_FAILED ((int32_t)-5)
#define R4STD_CONFIG_ERROR_INVALID_VALUE ((int32_t)-6)
#define R4STD_CONFIG_ERROR_VERIFY_FAILED ((int32_t)-7)
#define R4STD_CONFIG_ERROR_RECOVERY_FAILED ((int32_t)-8)

#define R4STD_TEXT_V1_EXPORT_NAME "TEXT_V1"
#define R4STD_TEXT_V1_ABI_MAJOR 1u
#define R4STD_TEXT_V1_REVISION 1u
#define R4STD_TEXT_V1_INTERFACE_ID_LO 0x20e30ebdcef27d92ull
#define R4STD_TEXT_V1_INTERFACE_ID_HI 0x4f8b90dbd3e7d113ull
#define R4STD_TEXT_V1_TABLE_SIZE 48u
#define R4STD_TEXT_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4STD_TEXT_V1_TABLE_SIZE, R4STD_TEXT_V1_ABI_MAJOR, R4STD_TEXT_V1_REVISION, R4STD_TEXT_V1_INTERFACE_ID_LO, R4STD_TEXT_V1_INTERFACE_ID_HI }
typedef int32_t (*R4StdTextV1InspectFn)(const uint8_t * input, uint64_t input_length, uint32_t kind, R4StdTextInfo * output);
typedef int32_t (*R4StdTextV1WriteFn)(const uint8_t * input, uint64_t input_length, uint32_t mode, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef struct R4StdTextV1 {
    R4LInterfaceHeader header;
    R4StdTextV1InspectFn inspect;
    R4StdTextV1WriteFn write;
} R4StdTextV1;
_Static_assert(sizeof(R4StdTextV1) == 48u, "R4StdTextV1 size mismatch");
_Static_assert(offsetof(R4StdTextV1, inspect) == 32u, "R4StdTextV1.inspect offset mismatch");
_Static_assert(offsetof(R4StdTextV1, write) == 40u, "R4StdTextV1.write offset mismatch");
typedef struct R4StdTextV1Client { const R4LInterfaceHeader *header; } R4StdTextV1Client;

static inline int32_t r4std_text_v1_init(const R4XStartContext *ctx, R4StdTextV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4STD", "TEXT_V1");
    const R4LInterfaceExpectation expected = { 0x20e30ebdcef27d92ull, 0x4f8b90dbd3e7d113ull, 1u, 1u, 48u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4std_text_inspect(R4StdTextV1Client *client, const uint8_t * input, uint64_t input_length, uint32_t kind, R4StdTextInfo * output) {
    R4StdTextV1InspectFn function = (R4StdTextV1InspectFn)r4l_slot_address(client->header, 32u);
    return function(input, input_length, kind, output);
}

static inline int32_t r4std_text_write(R4StdTextV1Client *client, const uint8_t * input, uint64_t input_length, uint32_t mode, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTextV1WriteFn function = (R4StdTextV1WriteFn)r4l_slot_address(client->header, 40u);
    return function(input, input_length, mode, output, output_capacity, output_length);
}

#define R4STD_SETTINGS_V1_EXPORT_NAME "SETTINGS_V1"
#define R4STD_SETTINGS_V1_ABI_MAJOR 1u
#define R4STD_SETTINGS_V1_REVISION 1u
#define R4STD_SETTINGS_V1_INTERFACE_ID_LO 0xa72d3a94f53635bcull
#define R4STD_SETTINGS_V1_INTERFACE_ID_HI 0xad6417547bbd0509ull
#define R4STD_SETTINGS_V1_TABLE_SIZE 128u
#define R4STD_SETTINGS_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4STD_SETTINGS_V1_TABLE_SIZE, R4STD_SETTINGS_V1_ABI_MAJOR, R4STD_SETTINGS_V1_REVISION, R4STD_SETTINGS_V1_INTERFACE_ID_LO, R4STD_SETTINGS_V1_INTERFACE_ID_HI }
typedef int32_t (*R4StdSettingsV1EntryNextFn)(const uint8_t * input, uint64_t input_length, uint64_t * cursor, R4StdEntryRange * output);
typedef int32_t (*R4StdSettingsV1ValueFn)(const uint8_t * input, uint64_t input_length, const uint8_t * key, uint64_t key_length, R4StdEntryRange * output);
typedef int32_t (*R4StdSettingsV1ParseScalarFn)(const uint8_t * input, uint64_t input_length, uint32_t kind, uint64_t * output);
typedef int32_t (*R4StdSettingsV1WriterAppendFn)(uint8_t * output, uint64_t output_capacity, uint64_t * output_length, uint32_t * truncated, uint32_t kind, const uint8_t * key, uint64_t key_length, const uint8_t * text_value, uint64_t text_value_length, int64_t numeric_value);
typedef uint32_t (*R4StdSettingsV1EqualsKeyFn)(const uint8_t * left, uint64_t left_length, const uint8_t * right, uint64_t right_length);
typedef int32_t (*R4StdSettingsV1WritebackPolicyFn)(uint32_t durability, uint32_t ticks_per_second, R4StdWritebackPolicy * output);
typedef uint32_t (*R4StdSettingsV1WritebackDefaultDelayFn)(uint32_t durability, uint32_t retry);
typedef int32_t (*R4StdSettingsV1WritebackInitFn)(R4StdWriteback * state, const R4StdWritebackPolicy * policy);
typedef int32_t (*R4StdSettingsV1WritebackConfigureFn)(R4StdWriteback * state, const R4StdWritebackPolicy * policy, uint64_t now);
typedef int32_t (*R4StdSettingsV1WritebackMarkDirtyFn)(R4StdWriteback * state, uint64_t now);
typedef int32_t (*R4StdSettingsV1WritebackPrepareFn)(R4StdWriteback * state, uint64_t now, uint32_t force, R4StdWritebackFlush * output);
typedef int32_t (*R4StdSettingsV1WritebackCompleteFn)(R4StdWriteback * state, uint64_t now, int32_t result, R4StdWritebackFlush * output);
typedef struct R4StdSettingsV1 {
    R4LInterfaceHeader header;
    R4StdSettingsV1EntryNextFn entry_next;
    R4StdSettingsV1ValueFn value;
    R4StdSettingsV1ParseScalarFn parse_scalar;
    R4StdSettingsV1WriterAppendFn writer_append;
    R4StdSettingsV1EqualsKeyFn equals_key;
    R4StdSettingsV1WritebackPolicyFn writeback_policy;
    R4StdSettingsV1WritebackDefaultDelayFn writeback_default_delay;
    R4StdSettingsV1WritebackInitFn writeback_init;
    R4StdSettingsV1WritebackConfigureFn writeback_configure;
    R4StdSettingsV1WritebackMarkDirtyFn writeback_mark_dirty;
    R4StdSettingsV1WritebackPrepareFn writeback_prepare;
    R4StdSettingsV1WritebackCompleteFn writeback_complete;
} R4StdSettingsV1;
_Static_assert(sizeof(R4StdSettingsV1) == 128u, "R4StdSettingsV1 size mismatch");
_Static_assert(offsetof(R4StdSettingsV1, entry_next) == 32u, "R4StdSettingsV1.entry_next offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, value) == 40u, "R4StdSettingsV1.value offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, parse_scalar) == 48u, "R4StdSettingsV1.parse_scalar offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writer_append) == 56u, "R4StdSettingsV1.writer_append offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, equals_key) == 64u, "R4StdSettingsV1.equals_key offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_policy) == 72u, "R4StdSettingsV1.writeback_policy offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_default_delay) == 80u, "R4StdSettingsV1.writeback_default_delay offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_init) == 88u, "R4StdSettingsV1.writeback_init offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_configure) == 96u, "R4StdSettingsV1.writeback_configure offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_mark_dirty) == 104u, "R4StdSettingsV1.writeback_mark_dirty offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_prepare) == 112u, "R4StdSettingsV1.writeback_prepare offset mismatch");
_Static_assert(offsetof(R4StdSettingsV1, writeback_complete) == 120u, "R4StdSettingsV1.writeback_complete offset mismatch");
typedef struct R4StdSettingsV1Client { const R4LInterfaceHeader *header; } R4StdSettingsV1Client;

static inline int32_t r4std_settings_v1_init(const R4XStartContext *ctx, R4StdSettingsV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4STD", "SETTINGS_V1");
    const R4LInterfaceExpectation expected = { 0xa72d3a94f53635bcull, 0xad6417547bbd0509ull, 1u, 1u, 128u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 80u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 88u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 96u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 104u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 112u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 120u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4std_settings_entry_next(R4StdSettingsV1Client *client, const uint8_t * input, uint64_t input_length, uint64_t * cursor, R4StdEntryRange * output) {
    R4StdSettingsV1EntryNextFn function = (R4StdSettingsV1EntryNextFn)r4l_slot_address(client->header, 32u);
    return function(input, input_length, cursor, output);
}

static inline int32_t r4std_settings_value(R4StdSettingsV1Client *client, const uint8_t * input, uint64_t input_length, const uint8_t * key, uint64_t key_length, R4StdEntryRange * output) {
    R4StdSettingsV1ValueFn function = (R4StdSettingsV1ValueFn)r4l_slot_address(client->header, 40u);
    return function(input, input_length, key, key_length, output);
}

static inline int32_t r4std_settings_parse_scalar(R4StdSettingsV1Client *client, const uint8_t * input, uint64_t input_length, uint32_t kind, uint64_t * output) {
    R4StdSettingsV1ParseScalarFn function = (R4StdSettingsV1ParseScalarFn)r4l_slot_address(client->header, 48u);
    return function(input, input_length, kind, output);
}

static inline int32_t r4std_settings_writer_append(R4StdSettingsV1Client *client, uint8_t * output, uint64_t output_capacity, uint64_t * output_length, uint32_t * truncated, uint32_t kind, const uint8_t * key, uint64_t key_length, const uint8_t * text_value, uint64_t text_value_length, int64_t numeric_value) {
    R4StdSettingsV1WriterAppendFn function = (R4StdSettingsV1WriterAppendFn)r4l_slot_address(client->header, 56u);
    return function(output, output_capacity, output_length, truncated, kind, key, key_length, text_value, text_value_length, numeric_value);
}

static inline uint32_t r4std_settings_equals_key(R4StdSettingsV1Client *client, const uint8_t * left, uint64_t left_length, const uint8_t * right, uint64_t right_length) {
    R4StdSettingsV1EqualsKeyFn function = (R4StdSettingsV1EqualsKeyFn)r4l_slot_address(client->header, 64u);
    return function(left, left_length, right, right_length);
}

static inline int32_t r4std_settings_writeback_policy(R4StdSettingsV1Client *client, uint32_t durability, uint32_t ticks_per_second, R4StdWritebackPolicy * output) {
    R4StdSettingsV1WritebackPolicyFn function = (R4StdSettingsV1WritebackPolicyFn)r4l_slot_address(client->header, 72u);
    return function(durability, ticks_per_second, output);
}

static inline uint32_t r4std_settings_writeback_default_delay(R4StdSettingsV1Client *client, uint32_t durability, uint32_t retry) {
    R4StdSettingsV1WritebackDefaultDelayFn function = (R4StdSettingsV1WritebackDefaultDelayFn)r4l_slot_address(client->header, 80u);
    return function(durability, retry);
}

static inline int32_t r4std_settings_writeback_init(R4StdSettingsV1Client *client, R4StdWriteback * state, const R4StdWritebackPolicy * policy) {
    R4StdSettingsV1WritebackInitFn function = (R4StdSettingsV1WritebackInitFn)r4l_slot_address(client->header, 88u);
    return function(state, policy);
}

static inline int32_t r4std_settings_writeback_configure(R4StdSettingsV1Client *client, R4StdWriteback * state, const R4StdWritebackPolicy * policy, uint64_t now) {
    R4StdSettingsV1WritebackConfigureFn function = (R4StdSettingsV1WritebackConfigureFn)r4l_slot_address(client->header, 96u);
    return function(state, policy, now);
}

static inline int32_t r4std_settings_writeback_mark_dirty(R4StdSettingsV1Client *client, R4StdWriteback * state, uint64_t now) {
    R4StdSettingsV1WritebackMarkDirtyFn function = (R4StdSettingsV1WritebackMarkDirtyFn)r4l_slot_address(client->header, 104u);
    return function(state, now);
}

static inline int32_t r4std_settings_writeback_prepare(R4StdSettingsV1Client *client, R4StdWriteback * state, uint64_t now, uint32_t force, R4StdWritebackFlush * output) {
    R4StdSettingsV1WritebackPrepareFn function = (R4StdSettingsV1WritebackPrepareFn)r4l_slot_address(client->header, 112u);
    return function(state, now, force, output);
}

static inline int32_t r4std_settings_writeback_complete(R4StdSettingsV1Client *client, R4StdWriteback * state, uint64_t now, int32_t result, R4StdWritebackFlush * output) {
    R4StdSettingsV1WritebackCompleteFn function = (R4StdSettingsV1WritebackCompleteFn)r4l_slot_address(client->header, 120u);
    return function(state, now, result, output);
}

#define R4STD_DATE_V1_EXPORT_NAME "DATE_V1"
#define R4STD_DATE_V1_ABI_MAJOR 1u
#define R4STD_DATE_V1_REVISION 1u
#define R4STD_DATE_V1_INTERFACE_ID_LO 0x114c12ba386e91b3ull
#define R4STD_DATE_V1_INTERFACE_ID_HI 0xbb8b0547d242bbc4ull
#define R4STD_DATE_V1_TABLE_SIZE 128u
#define R4STD_DATE_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4STD_DATE_V1_TABLE_SIZE, R4STD_DATE_V1_ABI_MAJOR, R4STD_DATE_V1_REVISION, R4STD_DATE_V1_INTERFACE_ID_LO, R4STD_DATE_V1_INTERFACE_ID_HI }
typedef uint8_t (*R4StdDateV1DaysInMonthFn)(uint16_t year, uint8_t month);
typedef uint32_t (*R4StdDateV1ValidDateFn)(uint16_t year, uint8_t month, uint8_t day);
typedef int32_t (*R4StdDateV1CompareDateTimeFn)(const R4StdDateTime * left, const R4StdDateTime * right);
typedef uint8_t (*R4StdDateV1WeekdayNumberFn)(uint16_t year, uint8_t month, uint8_t day);
typedef int32_t (*R4StdDateV1ShiftMinutesFn)(const R4StdDateTime * input, int32_t delta_minutes, R4StdShiftedDateTime * output);
typedef int32_t (*R4StdDateV1FromTimeStateFn)(const R4StdTimeState * input, R4StdDateTime * output);
typedef int32_t (*R4StdDateV1ToTimeStateFn)(const R4StdDateTime * input, R4StdTimeState * output);
typedef int32_t (*R4StdDateV1UtcFromDateTimeFn)(const R4StdDateTime * input, uint32_t nanosecond, R4StdUtcTime * output);
typedef int32_t (*R4StdDateV1DateTimeFromUtcFn)(const R4StdUtcTime * input, R4StdDateTime * output);
typedef int32_t (*R4StdDateV1FormatFn)(const R4StdDateTime * input, uint32_t mode, uint32_t clock_format, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef int32_t (*R4StdDateV1ParseFn)(const uint8_t * input, uint64_t input_length, uint32_t mode, R4StdDateTime * output);
typedef int32_t (*R4StdDateV1DecodeFatFn)(uint16_t date_raw, uint16_t time_raw, uint32_t mode, R4StdDateTime * output);
typedef struct R4StdDateV1 {
    R4LInterfaceHeader header;
    R4StdDateV1DaysInMonthFn days_in_month;
    R4StdDateV1ValidDateFn valid_date;
    R4StdDateV1CompareDateTimeFn compare_date_time;
    R4StdDateV1WeekdayNumberFn weekday_number;
    R4StdDateV1ShiftMinutesFn shift_minutes;
    R4StdDateV1FromTimeStateFn from_time_state;
    R4StdDateV1ToTimeStateFn to_time_state;
    R4StdDateV1UtcFromDateTimeFn utc_from_date_time;
    R4StdDateV1DateTimeFromUtcFn date_time_from_utc;
    R4StdDateV1FormatFn format;
    R4StdDateV1ParseFn parse;
    R4StdDateV1DecodeFatFn decode_fat;
} R4StdDateV1;
_Static_assert(sizeof(R4StdDateV1) == 128u, "R4StdDateV1 size mismatch");
_Static_assert(offsetof(R4StdDateV1, days_in_month) == 32u, "R4StdDateV1.days_in_month offset mismatch");
_Static_assert(offsetof(R4StdDateV1, valid_date) == 40u, "R4StdDateV1.valid_date offset mismatch");
_Static_assert(offsetof(R4StdDateV1, compare_date_time) == 48u, "R4StdDateV1.compare_date_time offset mismatch");
_Static_assert(offsetof(R4StdDateV1, weekday_number) == 56u, "R4StdDateV1.weekday_number offset mismatch");
_Static_assert(offsetof(R4StdDateV1, shift_minutes) == 64u, "R4StdDateV1.shift_minutes offset mismatch");
_Static_assert(offsetof(R4StdDateV1, from_time_state) == 72u, "R4StdDateV1.from_time_state offset mismatch");
_Static_assert(offsetof(R4StdDateV1, to_time_state) == 80u, "R4StdDateV1.to_time_state offset mismatch");
_Static_assert(offsetof(R4StdDateV1, utc_from_date_time) == 88u, "R4StdDateV1.utc_from_date_time offset mismatch");
_Static_assert(offsetof(R4StdDateV1, date_time_from_utc) == 96u, "R4StdDateV1.date_time_from_utc offset mismatch");
_Static_assert(offsetof(R4StdDateV1, format) == 104u, "R4StdDateV1.format offset mismatch");
_Static_assert(offsetof(R4StdDateV1, parse) == 112u, "R4StdDateV1.parse offset mismatch");
_Static_assert(offsetof(R4StdDateV1, decode_fat) == 120u, "R4StdDateV1.decode_fat offset mismatch");
typedef struct R4StdDateV1Client { const R4LInterfaceHeader *header; } R4StdDateV1Client;

static inline int32_t r4std_date_v1_init(const R4XStartContext *ctx, R4StdDateV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4STD", "DATE_V1");
    const R4LInterfaceExpectation expected = { 0x114c12ba386e91b3ull, 0xbb8b0547d242bbc4ull, 1u, 1u, 128u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 80u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 88u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 96u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 104u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 112u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 120u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline uint8_t r4std_date_days_in_month(R4StdDateV1Client *client, uint16_t year, uint8_t month) {
    R4StdDateV1DaysInMonthFn function = (R4StdDateV1DaysInMonthFn)r4l_slot_address(client->header, 32u);
    return function(year, month);
}

static inline uint32_t r4std_date_valid_date(R4StdDateV1Client *client, uint16_t year, uint8_t month, uint8_t day) {
    R4StdDateV1ValidDateFn function = (R4StdDateV1ValidDateFn)r4l_slot_address(client->header, 40u);
    return function(year, month, day);
}

static inline int32_t r4std_date_compare_date_time(R4StdDateV1Client *client, const R4StdDateTime * left, const R4StdDateTime * right) {
    R4StdDateV1CompareDateTimeFn function = (R4StdDateV1CompareDateTimeFn)r4l_slot_address(client->header, 48u);
    return function(left, right);
}

static inline uint8_t r4std_date_weekday_number(R4StdDateV1Client *client, uint16_t year, uint8_t month, uint8_t day) {
    R4StdDateV1WeekdayNumberFn function = (R4StdDateV1WeekdayNumberFn)r4l_slot_address(client->header, 56u);
    return function(year, month, day);
}

static inline int32_t r4std_date_shift_minutes(R4StdDateV1Client *client, const R4StdDateTime * input, int32_t delta_minutes, R4StdShiftedDateTime * output) {
    R4StdDateV1ShiftMinutesFn function = (R4StdDateV1ShiftMinutesFn)r4l_slot_address(client->header, 64u);
    return function(input, delta_minutes, output);
}

static inline int32_t r4std_date_from_time_state(R4StdDateV1Client *client, const R4StdTimeState * input, R4StdDateTime * output) {
    R4StdDateV1FromTimeStateFn function = (R4StdDateV1FromTimeStateFn)r4l_slot_address(client->header, 72u);
    return function(input, output);
}

static inline int32_t r4std_date_to_time_state(R4StdDateV1Client *client, const R4StdDateTime * input, R4StdTimeState * output) {
    R4StdDateV1ToTimeStateFn function = (R4StdDateV1ToTimeStateFn)r4l_slot_address(client->header, 80u);
    return function(input, output);
}

static inline int32_t r4std_date_utc_from_date_time(R4StdDateV1Client *client, const R4StdDateTime * input, uint32_t nanosecond, R4StdUtcTime * output) {
    R4StdDateV1UtcFromDateTimeFn function = (R4StdDateV1UtcFromDateTimeFn)r4l_slot_address(client->header, 88u);
    return function(input, nanosecond, output);
}

static inline int32_t r4std_date_date_time_from_utc(R4StdDateV1Client *client, const R4StdUtcTime * input, R4StdDateTime * output) {
    R4StdDateV1DateTimeFromUtcFn function = (R4StdDateV1DateTimeFromUtcFn)r4l_slot_address(client->header, 96u);
    return function(input, output);
}

static inline int32_t r4std_date_format(R4StdDateV1Client *client, const R4StdDateTime * input, uint32_t mode, uint32_t clock_format, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdDateV1FormatFn function = (R4StdDateV1FormatFn)r4l_slot_address(client->header, 104u);
    return function(input, mode, clock_format, output, output_capacity, output_length);
}

static inline int32_t r4std_date_parse(R4StdDateV1Client *client, const uint8_t * input, uint64_t input_length, uint32_t mode, R4StdDateTime * output) {
    R4StdDateV1ParseFn function = (R4StdDateV1ParseFn)r4l_slot_address(client->header, 112u);
    return function(input, input_length, mode, output);
}

static inline int32_t r4std_date_decode_fat(R4StdDateV1Client *client, uint16_t date_raw, uint16_t time_raw, uint32_t mode, R4StdDateTime * output) {
    R4StdDateV1DecodeFatFn function = (R4StdDateV1DecodeFatFn)r4l_slot_address(client->header, 120u);
    return function(date_raw, time_raw, mode, output);
}

#define R4STD_TIME_V1_EXPORT_NAME "TIME_V1"
#define R4STD_TIME_V1_ABI_MAJOR 1u
#define R4STD_TIME_V1_REVISION 1u
#define R4STD_TIME_V1_INTERFACE_ID_LO 0x968f346a4240a924ull
#define R4STD_TIME_V1_INTERFACE_ID_HI 0x288ef4aa6232d1c7ull
#define R4STD_TIME_V1_TABLE_SIZE 152u
#define R4STD_TIME_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4STD_TIME_V1_TABLE_SIZE, R4STD_TIME_V1_ABI_MAJOR, R4STD_TIME_V1_REVISION, R4STD_TIME_V1_INTERFACE_ID_LO, R4STD_TIME_V1_INTERFACE_ID_HI }
typedef uint32_t (*R4StdTimeV1ZoneCountFn)(void);
typedef int32_t (*R4StdTimeV1CopyZoneIdFn)(uint32_t index, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef int32_t (*R4StdTimeV1CopyZoneLabelFn)(uint32_t index, const R4StdTimeState * state, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef int32_t (*R4StdTimeV1IndexForIdFn)(const uint8_t * input, uint64_t input_length, uint32_t * output_index);
typedef int32_t (*R4StdTimeV1OffsetAtStateFn)(uint32_t index, const R4StdTimeState * state);
typedef uint32_t (*R4StdTimeV1SecondsInZoneFn)(uint32_t seconds_utc, int32_t offset_minutes);
typedef int32_t (*R4StdTimeV1SplitTimeFn)(uint32_t seconds, R4StdClockTime * output);
typedef int32_t (*R4StdTimeV1LocalDateTimeFn)(uint32_t index, const R4StdTimeState * state, R4StdDateTime * output);
typedef int32_t (*R4StdTimeV1FormatClockFn)(const R4StdClockTime * input, uint32_t mode, uint32_t clock_format, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef int32_t (*R4StdTimeV1FormatOffsetFn)(int32_t offset_minutes, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef uint32_t (*R4StdTimeV1ConfigLoadFn)(R4StdTimeConfig * config, const uint8_t * input, uint64_t input_length);
typedef int32_t (*R4StdTimeV1ConfigWriteFn)(const R4StdTimeConfig * config, const R4StdTimeState * state, uint32_t with_state, uint8_t * output, uint64_t output_capacity, uint64_t * output_length);
typedef int32_t (*R4StdTimeV1ConfigNormalizeFn)(R4StdTimeConfig * config);
typedef int32_t (*R4StdTimeV1ConfigOffsetFn)(const R4StdTimeConfig * config, const R4StdTimeState * state);
typedef int32_t (*R4StdTimeV1StandardOffsetFn)(uint32_t index);
typedef struct R4StdTimeV1 {
    R4LInterfaceHeader header;
    R4StdTimeV1ZoneCountFn zone_count;
    R4StdTimeV1CopyZoneIdFn copy_zone_id;
    R4StdTimeV1CopyZoneLabelFn copy_zone_label;
    R4StdTimeV1IndexForIdFn index_for_id;
    R4StdTimeV1OffsetAtStateFn offset_at_state;
    R4StdTimeV1SecondsInZoneFn seconds_in_zone;
    R4StdTimeV1SplitTimeFn split_time;
    R4StdTimeV1LocalDateTimeFn local_date_time;
    R4StdTimeV1FormatClockFn format_clock;
    R4StdTimeV1FormatOffsetFn format_offset;
    R4StdTimeV1ConfigLoadFn config_load;
    R4StdTimeV1ConfigWriteFn config_write;
    R4StdTimeV1ConfigNormalizeFn config_normalize;
    R4StdTimeV1ConfigOffsetFn config_offset;
    R4StdTimeV1StandardOffsetFn standard_offset;
} R4StdTimeV1;
_Static_assert(sizeof(R4StdTimeV1) == 152u, "R4StdTimeV1 size mismatch");
_Static_assert(offsetof(R4StdTimeV1, zone_count) == 32u, "R4StdTimeV1.zone_count offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, copy_zone_id) == 40u, "R4StdTimeV1.copy_zone_id offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, copy_zone_label) == 48u, "R4StdTimeV1.copy_zone_label offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, index_for_id) == 56u, "R4StdTimeV1.index_for_id offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, offset_at_state) == 64u, "R4StdTimeV1.offset_at_state offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, seconds_in_zone) == 72u, "R4StdTimeV1.seconds_in_zone offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, split_time) == 80u, "R4StdTimeV1.split_time offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, local_date_time) == 88u, "R4StdTimeV1.local_date_time offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, format_clock) == 96u, "R4StdTimeV1.format_clock offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, format_offset) == 104u, "R4StdTimeV1.format_offset offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, config_load) == 112u, "R4StdTimeV1.config_load offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, config_write) == 120u, "R4StdTimeV1.config_write offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, config_normalize) == 128u, "R4StdTimeV1.config_normalize offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, config_offset) == 136u, "R4StdTimeV1.config_offset offset mismatch");
_Static_assert(offsetof(R4StdTimeV1, standard_offset) == 144u, "R4StdTimeV1.standard_offset offset mismatch");
typedef struct R4StdTimeV1Client { const R4LInterfaceHeader *header; } R4StdTimeV1Client;

static inline int32_t r4std_time_v1_init(const R4XStartContext *ctx, R4StdTimeV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4STD", "TIME_V1");
    const R4LInterfaceExpectation expected = { 0x968f346a4240a924ull, 0x288ef4aa6232d1c7ull, 1u, 1u, 152u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 80u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 88u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 96u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 104u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 112u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 120u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 128u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 136u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 144u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline uint32_t r4std_time_zone_count(R4StdTimeV1Client *client) {
    R4StdTimeV1ZoneCountFn function = (R4StdTimeV1ZoneCountFn)r4l_slot_address(client->header, 32u);
    return function();
}

static inline int32_t r4std_time_copy_zone_id(R4StdTimeV1Client *client, uint32_t index, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTimeV1CopyZoneIdFn function = (R4StdTimeV1CopyZoneIdFn)r4l_slot_address(client->header, 40u);
    return function(index, output, output_capacity, output_length);
}

static inline int32_t r4std_time_copy_zone_label(R4StdTimeV1Client *client, uint32_t index, const R4StdTimeState * state, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTimeV1CopyZoneLabelFn function = (R4StdTimeV1CopyZoneLabelFn)r4l_slot_address(client->header, 48u);
    return function(index, state, output, output_capacity, output_length);
}

static inline int32_t r4std_time_index_for_id(R4StdTimeV1Client *client, const uint8_t * input, uint64_t input_length, uint32_t * output_index) {
    R4StdTimeV1IndexForIdFn function = (R4StdTimeV1IndexForIdFn)r4l_slot_address(client->header, 56u);
    return function(input, input_length, output_index);
}

static inline int32_t r4std_time_offset_at_state(R4StdTimeV1Client *client, uint32_t index, const R4StdTimeState * state) {
    R4StdTimeV1OffsetAtStateFn function = (R4StdTimeV1OffsetAtStateFn)r4l_slot_address(client->header, 64u);
    return function(index, state);
}

static inline uint32_t r4std_time_seconds_in_zone(R4StdTimeV1Client *client, uint32_t seconds_utc, int32_t offset_minutes) {
    R4StdTimeV1SecondsInZoneFn function = (R4StdTimeV1SecondsInZoneFn)r4l_slot_address(client->header, 72u);
    return function(seconds_utc, offset_minutes);
}

static inline int32_t r4std_time_split_time(R4StdTimeV1Client *client, uint32_t seconds, R4StdClockTime * output) {
    R4StdTimeV1SplitTimeFn function = (R4StdTimeV1SplitTimeFn)r4l_slot_address(client->header, 80u);
    return function(seconds, output);
}

static inline int32_t r4std_time_local_date_time(R4StdTimeV1Client *client, uint32_t index, const R4StdTimeState * state, R4StdDateTime * output) {
    R4StdTimeV1LocalDateTimeFn function = (R4StdTimeV1LocalDateTimeFn)r4l_slot_address(client->header, 88u);
    return function(index, state, output);
}

static inline int32_t r4std_time_format_clock(R4StdTimeV1Client *client, const R4StdClockTime * input, uint32_t mode, uint32_t clock_format, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTimeV1FormatClockFn function = (R4StdTimeV1FormatClockFn)r4l_slot_address(client->header, 96u);
    return function(input, mode, clock_format, output, output_capacity, output_length);
}

static inline int32_t r4std_time_format_offset(R4StdTimeV1Client *client, int32_t offset_minutes, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTimeV1FormatOffsetFn function = (R4StdTimeV1FormatOffsetFn)r4l_slot_address(client->header, 104u);
    return function(offset_minutes, output, output_capacity, output_length);
}

static inline uint32_t r4std_time_config_load(R4StdTimeV1Client *client, R4StdTimeConfig * config, const uint8_t * input, uint64_t input_length) {
    R4StdTimeV1ConfigLoadFn function = (R4StdTimeV1ConfigLoadFn)r4l_slot_address(client->header, 112u);
    return function(config, input, input_length);
}

static inline int32_t r4std_time_config_write(R4StdTimeV1Client *client, const R4StdTimeConfig * config, const R4StdTimeState * state, uint32_t with_state, uint8_t * output, uint64_t output_capacity, uint64_t * output_length) {
    R4StdTimeV1ConfigWriteFn function = (R4StdTimeV1ConfigWriteFn)r4l_slot_address(client->header, 120u);
    return function(config, state, with_state, output, output_capacity, output_length);
}

static inline int32_t r4std_time_config_normalize(R4StdTimeV1Client *client, R4StdTimeConfig * config) {
    R4StdTimeV1ConfigNormalizeFn function = (R4StdTimeV1ConfigNormalizeFn)r4l_slot_address(client->header, 128u);
    return function(config);
}

static inline int32_t r4std_time_config_offset(R4StdTimeV1Client *client, const R4StdTimeConfig * config, const R4StdTimeState * state) {
    R4StdTimeV1ConfigOffsetFn function = (R4StdTimeV1ConfigOffsetFn)r4l_slot_address(client->header, 136u);
    return function(config, state);
}

static inline int32_t r4std_time_standard_offset(R4StdTimeV1Client *client, uint32_t index) {
    R4StdTimeV1StandardOffsetFn function = (R4StdTimeV1StandardOffsetFn)r4l_slot_address(client->header, 144u);
    return function(index);
}

#define R4STD_CONFIG_V1_EXPORT_NAME "CONFIG_V1"
#define R4STD_CONFIG_V1_ABI_MAJOR 1u
#define R4STD_CONFIG_V1_REVISION 1u
#define R4STD_CONFIG_V1_INTERFACE_ID_LO 0x8fd66db6fcbe1c43ull
#define R4STD_CONFIG_V1_INTERFACE_ID_HI 0xfca1d800ccd28cbcull
#define R4STD_CONFIG_V1_TABLE_SIZE 80u
#define R4STD_CONFIG_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4STD_CONFIG_V1_TABLE_SIZE, R4STD_CONFIG_V1_ABI_MAJOR, R4STD_CONFIG_V1_REVISION, R4STD_CONFIG_V1_INTERFACE_ID_LO, R4STD_CONFIG_V1_INTERFACE_ID_HI }
typedef int32_t (*R4StdConfigV1ReadFn)(uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * key, uint64_t key_length, uint32_t kind, const uint8_t * fallback, uint64_t fallback_length, int64_t fallback_scalar, uint8_t * output, uint64_t output_capacity, uint64_t * output_scalar);
typedef int32_t (*R4StdConfigV1WriteFn)(uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * key, uint64_t key_length, uint32_t kind, const uint8_t * value, uint64_t value_length, int64_t scalar_value);
typedef int32_t (*R4StdConfigV1SaveDocumentFn)(uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * input, uint64_t input_length);
typedef int32_t (*R4StdConfigV1RecoverDocumentFn)(uint64_t caller_context, const uint8_t * path, uint64_t path_length);
typedef uint32_t (*R4StdConfigV1HasLeftoversFn)(uint64_t caller_context, const uint8_t * path, uint64_t path_length);
typedef int32_t (*R4StdConfigV1EnsureDirsFn)(uint64_t caller_context, uint32_t kind);
typedef struct R4StdConfigV1 {
    R4LInterfaceHeader header;
    R4StdConfigV1ReadFn read;
    R4StdConfigV1WriteFn write;
    R4StdConfigV1SaveDocumentFn save_document;
    R4StdConfigV1RecoverDocumentFn recover_document;
    R4StdConfigV1HasLeftoversFn has_leftovers;
    R4StdConfigV1EnsureDirsFn ensure_dirs;
} R4StdConfigV1;
_Static_assert(sizeof(R4StdConfigV1) == 80u, "R4StdConfigV1 size mismatch");
_Static_assert(offsetof(R4StdConfigV1, read) == 32u, "R4StdConfigV1.read offset mismatch");
_Static_assert(offsetof(R4StdConfigV1, write) == 40u, "R4StdConfigV1.write offset mismatch");
_Static_assert(offsetof(R4StdConfigV1, save_document) == 48u, "R4StdConfigV1.save_document offset mismatch");
_Static_assert(offsetof(R4StdConfigV1, recover_document) == 56u, "R4StdConfigV1.recover_document offset mismatch");
_Static_assert(offsetof(R4StdConfigV1, has_leftovers) == 64u, "R4StdConfigV1.has_leftovers offset mismatch");
_Static_assert(offsetof(R4StdConfigV1, ensure_dirs) == 72u, "R4StdConfigV1.ensure_dirs offset mismatch");
typedef struct R4StdConfigV1Client { const R4LInterfaceHeader *header; } R4StdConfigV1Client;

static inline int32_t r4std_config_v1_init(const R4XStartContext *ctx, R4StdConfigV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4STD", "CONFIG_V1");
    const R4LInterfaceExpectation expected = { 0x8fd66db6fcbe1c43ull, 0xfca1d800ccd28cbcull, 1u, 1u, 80u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4std_config_read(R4StdConfigV1Client *client, uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * key, uint64_t key_length, uint32_t kind, const uint8_t * fallback, uint64_t fallback_length, int64_t fallback_scalar, uint8_t * output, uint64_t output_capacity, uint64_t * output_scalar) {
    R4StdConfigV1ReadFn function = (R4StdConfigV1ReadFn)r4l_slot_address(client->header, 32u);
    return function(caller_context, path, path_length, key, key_length, kind, fallback, fallback_length, fallback_scalar, output, output_capacity, output_scalar);
}

static inline int32_t r4std_config_write(R4StdConfigV1Client *client, uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * key, uint64_t key_length, uint32_t kind, const uint8_t * value, uint64_t value_length, int64_t scalar_value) {
    R4StdConfigV1WriteFn function = (R4StdConfigV1WriteFn)r4l_slot_address(client->header, 40u);
    return function(caller_context, path, path_length, key, key_length, kind, value, value_length, scalar_value);
}

static inline int32_t r4std_config_save_document(R4StdConfigV1Client *client, uint64_t caller_context, const uint8_t * path, uint64_t path_length, const uint8_t * input, uint64_t input_length) {
    R4StdConfigV1SaveDocumentFn function = (R4StdConfigV1SaveDocumentFn)r4l_slot_address(client->header, 48u);
    return function(caller_context, path, path_length, input, input_length);
}

static inline int32_t r4std_config_recover_document(R4StdConfigV1Client *client, uint64_t caller_context, const uint8_t * path, uint64_t path_length) {
    R4StdConfigV1RecoverDocumentFn function = (R4StdConfigV1RecoverDocumentFn)r4l_slot_address(client->header, 56u);
    return function(caller_context, path, path_length);
}

static inline uint32_t r4std_config_has_leftovers(R4StdConfigV1Client *client, uint64_t caller_context, const uint8_t * path, uint64_t path_length) {
    R4StdConfigV1HasLeftoversFn function = (R4StdConfigV1HasLeftoversFn)r4l_slot_address(client->header, 64u);
    return function(caller_context, path, path_length);
}

static inline int32_t r4std_config_ensure_dirs(R4StdConfigV1Client *client, uint64_t caller_context, uint32_t kind) {
    R4StdConfigV1EnsureDirsFn function = (R4StdConfigV1EnsureDirsFn)r4l_slot_address(client->header, 72u);
    return function(caller_context, kind);
}

#endif
