// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4GL";

pub const R4GlRuntime = extern struct {
    version: u32,
    size: u32,
    application: u64,
    profile: u32,
    reserved: u32,
};

pub const R4GlLoader = extern struct {
    version: u32,
    size: u32,
    get_proc_address: u64,
};
pub const success: i32 = 0;
pub const error_initialization: i32 = -1;
pub const error_busy: i32 = -2;
pub const error_io: i32 = -3;

pub const egl_v1_export_name = "EGL_V1";
pub const egl_v1_revision: u16 = 1;
pub const egl_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 56,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x314c4745523448,
    .interface_id_hi = 0x314c4734534f,
};
pub const EglV1OpenFn = *const fn (input: *const R4GlRuntime, output: *R4GlLoader) callconv(.c) i32;
pub const EglV1ReleaseThreadFn = *const fn () callconv(.c) i32;
pub const EglV1FinishFn = *const fn (timeout_ns: u64) callconv(.c) i32;
pub const EglV1 = extern struct {
    header: InterfaceHeader,
    open: EglV1OpenFn,
    release_thread: EglV1ReleaseThreadFn,
    finish: EglV1FinishFn,
};

pub const EglV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !EglV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, egl_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x314c4745523448,
            .interface_id_hi = 0x314c4734534f,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 56,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn open(self: *const EglV1Client, input: *const R4GlRuntime, output: *R4GlLoader) i32 {
        const function = r4os.runtime_r4l.functionAt(EglV1OpenFn, self.header, 32) orelse unreachable;
        return function(input, output);
    }

    pub fn release_thread(self: *const EglV1Client) i32 {
        const function = r4os.runtime_r4l.functionAt(EglV1ReleaseThreadFn, self.header, 40) orelse unreachable;
        return function();
    }

    pub fn finish(self: *const EglV1Client, timeout_ns: u64) i32 {
        const function = r4os.runtime_r4l.functionAt(EglV1FinishFn, self.header, 48) orelse unreachable;
        return function(timeout_ns);
    }
};
