// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4IMG";

pub const R4ImgInfo = extern struct {
    format: u32,
    width: u32,
    height: u32,
    channels: u32,
};

pub const R4ImgSvgOptions = extern struct {
    flags: u32,
    background: u32,
    glyph_context: u64,
    glyph_row: u64,
    link_context: u64,
    link_record: u64,
    glyph_width: u16,
    glyph_height: u16,
    glyph_advance: u16,
    glyph_baseline: i16,
    reserved: u64,
};

pub const R4ImgDecoderDiagnostic = extern struct {
    scratch_peak: u64,
    allocation_failed: u32,
    reserved: u32,
};
pub const status_ok: i32 = 0;
pub const format_png: u32 = 0;
pub const format_jpeg: u32 = 1;
pub const format_bmp: u32 = 2;
pub const format_svg: u32 = 3;
pub const svg_flag_glyphs: u32 = 1;
pub const svg_flag_links: u32 = 2;
pub const svg_flag_background: u32 = 4;
pub const max_dimension: u32 = 4096;
pub const max_pixels: u64 = 8847360;
pub const max_scratch_bytes: u64 = 234881024;
pub const max_svg_source_bytes: u64 = 262144;
pub const status_empty: i32 = -1;
pub const status_unsupported_format: i32 = -2;
pub const status_invalid_image: i32 = -3;
pub const status_invalid_dimensions: i32 = -4;
pub const status_too_large: i32 = -5;
pub const status_pixel_buffer_too_small: i32 = -6;
pub const status_scratch_buffer_too_small: i32 = -7;
pub const status_decode_failed: i32 = -8;
pub const status_unsupported_feature: i32 = -9;
pub const status_invalid_argument: i32 = -10;

pub const api_v1_export_name = "API_V1";
pub const api_v1_revision: u16 = 1;
pub const api_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 80,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x5233f7f0fb63b451,
    .interface_id_hi = 0x315346a3a7ea4152,
};
pub const ApiV1ProbeFn = *const fn (encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, output: *R4ImgInfo) callconv(.c) i32;
pub const ApiV1ScratchBytesFn = *const fn (info: *const R4ImgInfo, encoded_length: u64, output_bytes: *u64) callconv(.c) i32;
pub const ApiV1DecodeFn = *const fn (encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, pixels: [*]u32, pixel_capacity: u64, scratch: [*]u8, scratch_length: u64, output_info: *R4ImgInfo, output_pixel_count: *u64) callconv(.c) i32;
pub const ApiV1DecodeSvgAtFn = *const fn (encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, pixels: [*]u32, pixel_capacity: u64, scratch: [*]u8, scratch_length: u64, width: u32, height: u32, options: *const R4ImgSvgOptions, output_info: *R4ImgInfo, output_pixel_count: *u64) callconv(.c) i32;
pub const ApiV1ScaleCompositeFn = *const fn (source_info: *const R4ImgInfo, source_pixels: [*]const u32, source_pixel_count: u64, destination: [*]u32, destination_capacity: u64, width: u32, height: u32, background: u32, output_pixel_count: *u64) callconv(.c) i32;
pub const ApiV1DecoderDiagnosticFn = *const fn (output: *R4ImgDecoderDiagnostic) callconv(.c) i32;
pub const ApiV1 = extern struct {
    header: InterfaceHeader,
    probe: ApiV1ProbeFn,
    scratch_bytes: ApiV1ScratchBytesFn,
    decode: ApiV1DecodeFn,
    decode_svg_at: ApiV1DecodeSvgAtFn,
    scale_composite: ApiV1ScaleCompositeFn,
    decoder_diagnostic: ApiV1DecoderDiagnosticFn,
};

pub const ApiV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !ApiV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, api_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x5233f7f0fb63b451,
            .interface_id_hi = 0x315346a3a7ea4152,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 80,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 56) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 64) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 72) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn probe(self: *const ApiV1Client, encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, output: *R4ImgInfo) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1ProbeFn, self.header, 32) orelse unreachable;
        return function(encoded, encoded_length, content_type, content_type_length, output);
    }

    pub fn scratch_bytes(self: *const ApiV1Client, info: *const R4ImgInfo, encoded_length: u64, output_bytes: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1ScratchBytesFn, self.header, 40) orelse unreachable;
        return function(info, encoded_length, output_bytes);
    }

    pub fn decode(self: *const ApiV1Client, encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, pixels: [*]u32, pixel_capacity: u64, scratch: [*]u8, scratch_length: u64, output_info: *R4ImgInfo, output_pixel_count: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecodeFn, self.header, 48) orelse unreachable;
        return function(encoded, encoded_length, content_type, content_type_length, pixels, pixel_capacity, scratch, scratch_length, output_info, output_pixel_count);
    }

    pub fn decode_svg_at(self: *const ApiV1Client, encoded: [*]const u8, encoded_length: u64, content_type: [*]const u8, content_type_length: u64, pixels: [*]u32, pixel_capacity: u64, scratch: [*]u8, scratch_length: u64, width: u32, height: u32, options: *const R4ImgSvgOptions, output_info: *R4ImgInfo, output_pixel_count: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecodeSvgAtFn, self.header, 56) orelse unreachable;
        return function(encoded, encoded_length, content_type, content_type_length, pixels, pixel_capacity, scratch, scratch_length, width, height, options, output_info, output_pixel_count);
    }

    pub fn scale_composite(self: *const ApiV1Client, source_info: *const R4ImgInfo, source_pixels: [*]const u32, source_pixel_count: u64, destination: [*]u32, destination_capacity: u64, width: u32, height: u32, background: u32, output_pixel_count: *u64) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1ScaleCompositeFn, self.header, 64) orelse unreachable;
        return function(source_info, source_pixels, source_pixel_count, destination, destination_capacity, width, height, background, output_pixel_count);
    }

    pub fn decoder_diagnostic(self: *const ApiV1Client, output: *R4ImgDecoderDiagnostic) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1DecoderDiagnosticFn, self.header, 72) orelse unreachable;
        return function(output);
    }
};
