# Copyright 2026 R4. SPDX-License-Identifier: Apache-2.0
param([switch]$Write)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$unit=[IO.Path]::GetFullPath('..',$PSScriptRoot)
$manifest=Get-Content -Raw (Join-Path $PSScriptRoot 'ShaderFixtures.json')|ConvertFrom-Json
$lines=[Collections.Generic.List[string]]::new()
$lines.Add('// Copyright 2026 R4. SPDX-License-Identifier: Apache-2.0')
$lines.Add('// Generated by Tools/Shaders.ps1 from the checksum-pinned self-authored SPIR-V fixtures.')
$lines.Add('// These bytes are compiled on a worker during preparation; they contain no GFX9 machine code.')
foreach($fixture in $manifest.fixtures){
   $source=Join-Path $unit ('Tests/Fixtures/'+$fixture.source)
   $spirv=Join-Path $unit ('Tests/Fixtures/'+$fixture.name+'.spv')
   if((Get-FileHash $source).Hash.ToLowerInvariant() -ne $fixture.source_sha256 -or
      (Get-FileHash $spirv).Hash.ToLowerInvariant() -ne $fixture.spirv_sha256){throw "Shader fixture drift: $($fixture.name)"}
   $bytes=[IO.File]::ReadAllBytes($spirv)
   if($bytes.Length -ne $fixture.word_count*4 -or [BitConverter]::ToUInt32($bytes,0) -ne 0x07230203){throw 'Invalid SPIR-V fixture.'}
   $lines.Add('pub const '+$fixture.name+' = [_]u32{')
   for($i=0;$i -lt $fixture.word_count;$i+=8){
      $words=@(for($n=$i;$n -lt [Math]::Min($i+8,$fixture.word_count);$n++){'0x'+[BitConverter]::ToUInt32($bytes,$n*4).ToString('x8')})
      $lines.Add('    '+($words -join ', ')+',')
   }
   $lines.Add('};')
}
$text=($lines -join "`n")+"`n"
$destination=Join-Path $unit 'Bindings/Zig/shaders.zig'
if($Write){[IO.File]::WriteAllText($destination,$text,[Text.UTF8Encoding]::new($false))}
elseif([IO.File]::ReadAllText($destination) -cne $text){throw 'Generated shader binding differs; run Tools/Shaders.ps1 -Write.'}
Write-Host "R4ACO shader fixtures: $($manifest.fixtures.Count) source/SPIR-V hashes and generated bindings verified."
