# Copyright 2026 R4. SPDX-License-Identifier: Apache-2.0
[CmdletBinding()]
param([switch]$Write,[string]$CompilerPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$unit=[IO.Path]::GetFullPath('..',$PSScriptRoot)
$libraries=[IO.Path]::GetFullPath('..',$unit)
$source=Join-Path $unit 'Source/Shaders'
$output=Join-Path $unit 'Source/Generated/Shaders'
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function Run([string]$Tool,[string[]]$Arguments){& $Tool @Arguments;if($LASTEXITCODE){throw "Shader tool failed: $Tool"}}
$profiles=@('fullscreen.vert','pull.vert','fill.frag','sample.frag','color.frag','yuv.frag')
$inputs=@(Get-ChildItem $source -File|Sort-Object Name|ForEach-Object {[ordered]@{path=('Source/Shaders/'+$_.Name);sha256=(Hash $_.FullName)}})
$recordPath=Join-Path $output 'shaders.json'
if($Write){
    # Ordinary Windows and Linux builds verify the exact committed programs.
    # Regeneration uses the executable CPU compiler, never a fabricated ISA.
    if(!$CompilerPath){
        if(!$IsLinux){throw 'Shader regeneration requires a compatible offline R4ACO compiler via -CompilerPath. The bundled host frontend is Linux; normal Windows builds verify the committed programs.'}
        $CompilerPath=Join-Path $libraries 'R4ACO/zig-out/bin/r4aco-compiler'
    }
    $CompilerPath=[IO.Path]::GetFullPath($CompilerPath)
    $glsl=(Get-Command glslangValidator -CommandType Application -ErrorAction Stop|Select-Object -First 1).Source
    $version=@(& $glsl --version)
    if($LASTEXITCODE -or $version[0] -notmatch '15\.2\.0'){throw 'Pinned glslangValidator15.2.0 required.'}
    $settings=@{}
    foreach($line in Get-Content (Join-Path $libraries 'Settings.R4S')){if($line -match '^([A-Z_]+)=(.+)$'){$settings[$Matches[1]]=$Matches[2]}}
    $workspace=[IO.Path]::GetFullPath($settings.WORKSPACE_ROOT.Replace('\','/'),$libraries)
    $temp=Join-Path $workspace 'Temp/AMDShaders08014'
    [IO.Directory]::CreateDirectory($temp)|Out-Null
    [IO.Directory]::CreateDirectory($output)|Out-Null
    $results=@();$text=[Text.StringBuilder]::new()
    [void]$text.AppendLine('// Generated by Tools/Shaders.ps1 from actual R4ACO compilation; do not edit.')
    [void]$text.AppendLine('pub fn Programs(comptime c: type) type { return struct {')
    [void]$text.AppendLine('pub const Profile = struct { code: []const u8, metadata: c.R4AmdShader };')
    [void]$text.AppendLine('pub const profiles = [_]Profile{')
    foreach($index in 0..5){
        $name=$profiles[$index];$stage=if($index -lt 2){0}else{4};$abi=if($index -lt 3){1}else{2}
        $spv=Join-Path $temp ($name+'.spv');$bin=Join-Path $temp ($name+'.bin');$meta=Join-Path $temp ($name+'.json')
        Run $glsl @('-V','--target-env','vulkan1.0','-o',$spv,(Join-Path $source $name))
        Run $CompilerPath @($spv,[string]$stage,[string]$abi,$bin,$meta)
        Run $CompilerPath @($spv,[string]$stage,[string]$abi,($bin+'.repeat'),($meta+'.repeat'))
        $data=Get-Content -Raw $meta|ConvertFrom-Json;$m=$data.binary
        if($data.schema -ne 1 -or $m.status -ne 0 -or $m.stage -ne $stage -or $m.gfx_profile -ne 902 -or $m.resource_abi -ne $abi -or
           $m.code_bytes -ne (Get-Item $bin).Length -or $m.code_bytes -gt 65536 -or $m.exec_bytes -le 0 -or $m.exec_bytes -gt $m.code_bytes -or
           $m.scratch_bytes_per_wave -ne 0 -or $m.lds_bytes -ne 0 -or $m.symbol_count -ne 0 -or $m.inputs_read -ne 0 -or
           $m.outputs_written -ne $(if($stage -eq 0){1}else{16}) -or $data.code_sha256 -cne (Hash $bin) -or (Hash $bin) -cne (Hash ($bin+'.repeat'))){throw "Unsupported/non-reproducible shader: $name"}
        $repeat=Get-Content -Raw ($meta+'.repeat')|ConvertFrom-Json
        foreach($value in @($data,$repeat)){$value.binary.elapsed_ns=0;$value.binary.peak_bytes=0;$value.binary.log_length=0}
        if(($data|ConvertTo-Json -Depth 10 -Compress) -cne ($repeat|ConvertTo-Json -Depth 10 -Compress)){throw "Non-reproducible metadata: $name"}
        Copy-Item $spv (Join-Path $output ($name+'.spv')) -Force
        Copy-Item $bin (Join-Path $output ($name+'.bin')) -Force
        $data|ConvertTo-Json -Depth 10|Set-Content (Join-Path $output ($name+'.json')) -Encoding utf8NoBOM
        $fields=@('stage','resource_abi','code_bytes','exec_bytes','sgprs','vgprs','float_mode','user_sgprs','input_vgprs','spi_ps_input_ena','spi_ps_input_addr')
        [void]$text.AppendLine(('    .{ .code = @embedFile("'+$name+'.bin"), .metadata = .{ .version = 1, .size = @sizeOf(c.R4AmdShader), .code_address = 0, .reserved = 0,'))
        foreach($field in $fields){[void]$text.AppendLine(('        .'+$field+' = '+$m.$field+','))}
        [void]$text.AppendLine('    } },')
        $results+=[ordered]@{id=$index;name=$name;stage=$stage;resource_abi=$abi;spirv_sha256=(Hash (Join-Path $output ($name+'.spv')));code_sha256=(Hash (Join-Path $output ($name+'.bin')));metadata_sha256=(Hash (Join-Path $output ($name+'.json')))}
    }
    [void]$text.AppendLine('};')
    [void]$text.AppendLine('}; }')
    [IO.File]::WriteAllText((Join-Path $output 'shaders.zig'),$text.ToString().Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))
    [ordered]@{schema=1;gfx_profile=902;mesa='26.2.2';glslang=$version[0];compiler_executable_sha256=(Hash $CompilerPath);recipe_sha256=(Hash $PSCommandPath);
        inputs=$inputs;profiles=$results;generated_zig_sha256=(Hash (Join-Path $output 'shaders.zig'));reproducible=$true}|ConvertTo-Json -Depth 10|Set-Content $recordPath -Encoding utf8NoBOM
}
$record=Get-Content -Raw $recordPath|ConvertFrom-Json
if($record.schema -ne 1 -or $record.gfx_profile -ne 902 -or $record.mesa -cne '26.2.2' -or !$record.reproducible -or $record.profiles.Count -ne 6 -or
   $record.recipe_sha256 -cne (Hash $PSCommandPath) -or ($inputs|ConvertTo-Json -Compress) -cne ($record.inputs|ConvertTo-Json -Compress) -or
   $record.generated_zig_sha256 -cne (Hash (Join-Path $output 'shaders.zig'))){throw 'AMD shader source/recipe drift; regenerate the real programs.'}
foreach($index in 0..5){
    $profile=$record.profiles[$index];$name=$profiles[$index]
    if($profile.id -ne $index -or $profile.name -cne $name){throw 'Shader profile order changed.'}
    foreach($pair in @(@('.spv','spirv_sha256'),@('.bin','code_sha256'),@('.json','metadata_sha256'))){
        if((Hash (Join-Path $output ($name+$pair[0]))) -cne $profile.($pair[1])){throw "Shader artifact drift: $name$($pair[0])"}
    }
}
Write-Host 'AMD fixed shaders: six real GFX902 programs, reproducible code/metadata, source and artifact hashes verified.'
