// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4VIDEO";

pub const R4VideoRuntime = extern struct {
    address: u64,
    generation: u64,
};

pub const R4VideoDecoder = extern struct {
    address: u64,
    generation: u64,
};

pub const R4VideoStartup = extern struct {
    version: u32,
    size: u32,
    application: u64,
    memory_limit: u64,
    max_decoders: u32,
    thread_limit: u32,
};

pub const R4VideoCapsQuery = extern struct {
    version: u32,
    size: u32,
    backend: u32,
    adapter_id: u32,
    codec: u32,
    profile: u32,
    bit_depth: u32,
    chroma: u32,
};

pub const R4VideoCaps = extern struct {
    version: u32,
    size: u32,
    query: R4VideoCapsQuery,
    min_width: u32,
    min_height: u32,
    max_width: u32,
    max_height: u32,
    max_level: u32,
    output_formats: u32,
    max_packet_bytes: u64,
    max_pending_packets: u32,
    max_frame_leases: u32,
    device_generation: u64,
    reset_generation: u64,
    flags: u32,
    reserved: u32,
};

pub const R4VideoConfig = extern struct {
    version: u32,
    size: u32,
    query: R4VideoCapsQuery,
    memory_limit: u64,
    max_width: u32,
    max_height: u32,
    pending_packets: u32,
    frame_leases: u32,
    threads: u32,
    flags: u32,
};

pub const R4VideoPacket = extern struct {
    version: u32,
    size: u32,
    data_address: u64,
    data_bytes: u64,
    stream_generation: u64,
    tag: u64,
    pts_ns: i64,
    dts_ns: i64,
    duration_ns: u64,
    flags: u32,
    reserved: u32,
};

pub const R4VideoBuffer = extern struct {
    id: u32,
    reserved0: u32,
    generation: u64,
};

pub const R4VideoFence = extern struct {
    slot: u32,
    adapter_id: u32,
    timeline: u64,
    point: u64,
    device_generation: u64,
    reset_generation: u64,
};

pub const R4VideoPlane = extern struct {
    buffer: R4VideoBuffer,
    reference: R4VideoBuffer,
    offset: u64,
    pitch: u64,
    row_bytes: u64,
    rows: u32,
    reserved: u32,
};

pub const R4VideoColor = extern struct {
    version: u32,
    size: u32,
    primaries: u32,
    transfer: u32,
    range: u32,
    matrix: u32,
    chroma_location: u32,
    bit_depth: u32,
    reference_white: u32,
    peak: u32,
    black: u32,
    flags: u32,
};

pub const R4VideoLease = extern struct {
    decoder: R4VideoDecoder,
    token: u64,
    stream_generation: u64,
};

pub const R4VideoFrame = extern struct {
    version: u32,
    size: u32,
    lease: R4VideoLease,
    tag: u64,
    pts_ns: i64,
    dts_ns: i64,
    duration_ns: u64,
    coded_width: u32,
    coded_height: u32,
    crop_x: u32,
    crop_y: u32,
    crop_width: u32,
    crop_height: u32,
    sar_num: u32,
    sar_den: u32,
    format: u32,
    plane_count: u32,
    color: R4VideoColor,
    plane0: R4VideoPlane,
    plane1: R4VideoPlane,
    plane2: R4VideoPlane,
    ready: R4VideoFence,
    flags: u32,
    reserved: u32,
};

pub const R4VideoReceipt = extern struct {
    version: u32,
    size: u32,
    fence: R4VideoFence,
    result: i32,
    reserved: u32,
};

pub const R4VideoControl = extern struct {
    version: u32,
    size: u32,
    request_id: u64,
    operation: u32,
    reserved: u32,
};

pub const R4VideoState = extern struct {
    version: u32,
    size: u32,
    stream_generation: u64,
    pending_request: u64,
    completed_request: u64,
    memory_bytes: u64,
    phase: u32,
    queued_packets: u32,
    ready_frames: u32,
    leased_frames: u32,
    last_error: i32,
    reserved: u32,
};
pub const ok: i32 = 0;
pub const again: i32 = 1;
pub const eos: i32 = 2;
pub const backend_software: u32 = 0;
pub const backend_nvidia: u32 = 1;
pub const codec_h264: u32 = 1;
pub const profile_default: u32 = 0;
pub const profile_h264_baseline: u32 = 66;
pub const profile_h264_main: u32 = 77;
pub const profile_h264_high: u32 = 100;
pub const chroma_420: u32 = 1;
pub const format_nv12: u32 = 1;
pub const format_p010: u32 = 2;
pub const format_yuv420p: u32 = 3;
pub const formats_nv12: u32 = 1;
pub const formats_p010: u32 = 2;
pub const formats_yuv420p: u32 = 4;
pub const matrix_unspecified: u32 = 2;
pub const matrix_bt470bg: u32 = 5;
pub const matrix_bt709: u32 = 1;
pub const matrix_bt2020_ncl: u32 = 9;
pub const chroma_unspecified: u32 = 0;
pub const chroma_left: u32 = 1;
pub const chroma_center: u32 = 2;
pub const chroma_top_left: u32 = 3;
pub const packet_pts: u32 = 1;
pub const packet_dts: u32 = 2;
pub const packet_duration: u32 = 4;
pub const frame_key: u32 = 8;
pub const phase_open: u32 = 0;
pub const phase_draining: u32 = 1;
pub const phase_drained: u32 = 2;
pub const phase_flushing: u32 = 3;
pub const phase_closing: u32 = 4;
pub const phase_closed: u32 = 5;
pub const phase_failed: u32 = 6;
pub const control_query: u32 = 0;
pub const control_drain: u32 = 1;
pub const control_flush: u32 = 2;
pub const control_close: u32 = 3;
pub const matrix_smpte170m: u32 = 6;
pub const color_reference_white: u32 = 1;
pub const color_luminance: u32 = 2;
pub const color_unspecified: u32 = 2;
pub const error_invalid: i32 = -1;
pub const error_unsupported: i32 = -2;
pub const error_busy: i32 = -3;
pub const error_no_memory: i32 = -4;
pub const error_stale: i32 = -5;
pub const error_decode: i32 = -6;
pub const error_device_lost: i32 = -7;
pub const error_closed: i32 = -8;
pub const error_internal: i32 = -9;

pub const video_v1_export_name = "VIDEO_V1";
pub const video_v1_revision: u16 = 1;
pub const video_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 104,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x314f454449563452,
    .interface_id_hi = 0x313045444f434544,
};
pub const VideoV1OpenFn = *const fn (startup: *const R4VideoStartup, runtime: *R4VideoRuntime) callconv(.c) i32;
pub const VideoV1QueryCapsFn = *const fn (runtime: *const R4VideoRuntime, query: *const R4VideoCapsQuery, output: *R4VideoCaps) callconv(.c) i32;
pub const VideoV1CreateFn = *const fn (runtime: *const R4VideoRuntime, config: *const R4VideoConfig, decoder: *R4VideoDecoder) callconv(.c) i32;
pub const VideoV1SendFn = *const fn (decoder: *const R4VideoDecoder, packet: *const R4VideoPacket) callconv(.c) i32;
pub const VideoV1ReceiveFn = *const fn (decoder: *const R4VideoDecoder, frame: *R4VideoFrame) callconv(.c) i32;
pub const VideoV1ReleaseFn = *const fn (lease: *const R4VideoLease, receipt: *const R4VideoReceipt) callconv(.c) i32;
pub const VideoV1ControlFn = *const fn (decoder: *const R4VideoDecoder, request: *const R4VideoControl, state: *R4VideoState) callconv(.c) i32;
pub const VideoV1DestroyFn = *const fn (decoder: *const R4VideoDecoder) callconv(.c) i32;
pub const VideoV1FinishFn = *const fn (runtime: *const R4VideoRuntime, timeout_ns: u64) callconv(.c) i32;
pub const VideoV1 = extern struct {
    header: InterfaceHeader,
    open: VideoV1OpenFn,
    query_caps: VideoV1QueryCapsFn,
    create: VideoV1CreateFn,
    send: VideoV1SendFn,
    receive: VideoV1ReceiveFn,
    release: VideoV1ReleaseFn,
    control: VideoV1ControlFn,
    destroy: VideoV1DestroyFn,
    finish: VideoV1FinishFn,
};

pub const VideoV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !VideoV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, video_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x314f454449563452,
            .interface_id_hi = 0x313045444f434544,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 104,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 56) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 64) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 72) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 80) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 88) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 96) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn open(self: *const VideoV1Client, startup: *const R4VideoStartup, runtime: *R4VideoRuntime) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1OpenFn, self.header, 32) orelse unreachable;
        return function(startup, runtime);
    }

    pub fn query_caps(self: *const VideoV1Client, runtime: *const R4VideoRuntime, query: *const R4VideoCapsQuery, output: *R4VideoCaps) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1QueryCapsFn, self.header, 40) orelse unreachable;
        return function(runtime, query, output);
    }

    pub fn create(self: *const VideoV1Client, runtime: *const R4VideoRuntime, config: *const R4VideoConfig, decoder: *R4VideoDecoder) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1CreateFn, self.header, 48) orelse unreachable;
        return function(runtime, config, decoder);
    }

    pub fn send(self: *const VideoV1Client, decoder: *const R4VideoDecoder, packet: *const R4VideoPacket) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1SendFn, self.header, 56) orelse unreachable;
        return function(decoder, packet);
    }

    pub fn receive(self: *const VideoV1Client, decoder: *const R4VideoDecoder, frame: *R4VideoFrame) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1ReceiveFn, self.header, 64) orelse unreachable;
        return function(decoder, frame);
    }

    pub fn release(self: *const VideoV1Client, lease: *const R4VideoLease, receipt: *const R4VideoReceipt) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1ReleaseFn, self.header, 72) orelse unreachable;
        return function(lease, receipt);
    }

    pub fn control(self: *const VideoV1Client, decoder: *const R4VideoDecoder, request: *const R4VideoControl, state: *R4VideoState) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1ControlFn, self.header, 80) orelse unreachable;
        return function(decoder, request, state);
    }

    pub fn destroy(self: *const VideoV1Client, decoder: *const R4VideoDecoder) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1DestroyFn, self.header, 88) orelse unreachable;
        return function(decoder);
    }

    pub fn finish(self: *const VideoV1Client, runtime: *const R4VideoRuntime, timeout_ns: u64) i32 {
        const function = r4os.runtime_r4l.functionAt(VideoV1FinishFn, self.header, 96) orelse unreachable;
        return function(runtime, timeout_ns);
    }
};
