// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4VK";

pub const R4VkRuntime = extern struct {
    version: u32,
    size: u32,
    sys: u64,
    draw: u64,
    dev: u64,
};

pub const R4VkLoader = extern struct {
    version: u32,
    size: u32,
    negotiate_loader_icd: u64,
    get_instance_proc_addr: u64,
    get_physical_device_proc_addr: u64,
};
pub const success: i32 = 0;
pub const error_initialization_failed: i32 = -3;

pub const vulkan_v1_export_name = "VULKAN_V1";
pub const vulkan_v1_revision: u16 = 1;
pub const vulkan_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 40,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x4e414b4c55563452,
    .interface_id_hi = 0x31494241534f3452,
};
pub const VulkanV1OpenFn = *const fn (runtime: *const R4VkRuntime, output: *R4VkLoader) callconv(.c) i32;
pub const VulkanV1 = extern struct {
    header: InterfaceHeader,
    open: VulkanV1OpenFn,
};

pub const VulkanV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !VulkanV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, vulkan_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x4e414b4c55563452,
            .interface_id_hi = 0x31494241534f3452,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 40,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn open(self: *const VulkanV1Client, runtime: *const R4VkRuntime, output: *R4VkLoader) i32 {
        const function = r4os.runtime_r4l.functionAt(VulkanV1OpenFn, self.header, 32) orelse unreachable;
        return function(runtime, output);
    }
};
