// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4AMD";

pub const R4AmdInfo = extern struct {
    version: u32,
    size: u32,
    mesa_major: u32,
    mesa_minor: u32,
    mesa_patch: u32,
    implementation_stage: u32,
    capability_flags: u32,
    reserved: u32,
};
pub const info_version: u32 = 1;
pub const status_ok: i32 = 0;
pub const status_invalid: i32 = -1;

pub const info_v1_export_name = "INFO_V1";
pub const info_v1_revision: u16 = 1;
pub const info_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 40,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x414d4431,
    .interface_id_hi = 0x52344f53,
};
pub const InfoV1GetInfoFn = *const fn (output: *R4AmdInfo, output_bytes: u32) callconv(.c) i32;
pub const InfoV1 = extern struct {
    header: InterfaceHeader,
    get_info: InfoV1GetInfoFn,
};

pub const InfoV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !InfoV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, info_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x414d4431,
            .interface_id_hi = 0x52344f53,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 40,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn get_info(self: *const InfoV1Client, output: *R4AmdInfo, output_bytes: u32) i32 {
        const function = r4os.runtime_r4l.functionAt(InfoV1GetInfoFn, self.header, 32) orelse unreachable;
        return function(output, output_bytes);
    }
};
