// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4AMD";

pub const R4AmdInfo = extern struct {
    version: u32,
    size: u32,
    mesa_major: u32,
    mesa_minor: u32,
    mesa_patch: u32,
    implementation_stage: u32,
    capability_flags: u32,
    reserved: u32,
};

pub const R4AmdDriverProfile = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    device_id: u32,
    gc_version: u32,
    sdma_version: u32,
    command_abi: u32,
    reserved: u32,
};

pub const R4AmdDeviceProfile = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    device_id: u32,
    gc_version: u32,
    sdma_version: u32,
    command_abi: u32,
    flags: u32,
    adapter_id: u32,
    reserved: u32,
    device_generation: u64,
    reset_generation: u64,
};

pub const R4AmdFeatures = extern struct {
    version: u32,
    size: u32,
    command_abi: u32,
    features: u32,
    gpu_address_bits: u32,
    max_command_words: u32,
    reserved0: u32,
    reserved1: u32,
};

pub const R4AmdCopy = extern struct {
    version: u32,
    size: u32,
    source: u64,
    target: u64,
    byte_length: u64,
    source_pitch: u64,
    target_pitch: u64,
    source_modifier: u64,
    target_modifier: u64,
    row_count: u32,
    reserved: u32,
};

pub const R4AmdFill = extern struct {
    version: u32,
    size: u32,
    target: u64,
    byte_length: u64,
    value: u32,
    reserved: u32,
};

pub const R4AmdPm4Frame = extern struct {
    version: u32,
    size: u32,
    engine: u32,
    flags: u32,
    indirect_address: u64,
    fence_address: u64,
    eop_scratch: u64,
    fence_sequence: u64,
    command_dwords: u32,
    reserved0: u32,
    reserved1: u64,
};
pub const info_version: u32 = 1;
pub const status_ok: i32 = 0;
pub const profile_version: u32 = 1;
pub const command_abi: u32 = 1;
pub const vendor_id: u32 = 4098;
pub const gc_9_1_0: u32 = 590080;
pub const sdma_4_1_0: u32 = 262400;
pub const feature_copy_linear: u32 = 1;
pub const feature_copy_rows: u32 = 2;
pub const feature_copy_layout: u32 = 4;
pub const feature_fill: u32 = 8;
pub const feature_pm4: u32 = 16;
pub const status_invalid: i32 = -1;
pub const status_unsupported: i32 = -2;

pub const info_v1_export_name = "INFO_V1";
pub const info_v1_revision: u16 = 1;
pub const info_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 40,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x414d4431,
    .interface_id_hi = 0x52344f53,
};
pub const InfoV1GetInfoFn = *const fn (output: *R4AmdInfo, output_bytes: u32) callconv(.c) i32;
pub const InfoV1 = extern struct {
    header: InterfaceHeader,
    get_info: InfoV1GetInfoFn,
};

pub const backend_v1_export_name = "BACKEND_V1";
pub const backend_v1_revision: u16 = 3;
pub const backend_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 64,
    .abi_major = 1,
    .abi_minor = 3,
    .interface_id_lo = 0x414d4432,
    .interface_id_hi = 0x52344f53,
};
pub const BackendV1NegotiateFn = *const fn (profile: *const R4AmdDeviceProfile, output: *R4AmdFeatures) callconv(.c) i32;
pub const BackendV1EncodeCopyFn = *const fn (request: *const R4AmdCopy, commands: [*]u32, capacity: u32, written: *u32) callconv(.c) i32;
pub const BackendV1EncodeFillFn = *const fn (request: *const R4AmdFill, commands: [*]u32, capacity: u32, written: *u32) callconv(.c) i32;
pub const BackendV1EncodePm4FrameFn = *const fn (request: *const R4AmdPm4Frame, commands: [*]u32, capacity: u32, written: *u32) callconv(.c) i32;
pub const BackendV1 = extern struct {
    header: InterfaceHeader,
    negotiate: BackendV1NegotiateFn,
    encode_copy: BackendV1EncodeCopyFn,
    encode_fill: BackendV1EncodeFillFn,
    encode_pm4_frame: BackendV1EncodePm4FrameFn,
};

pub const InfoV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !InfoV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, info_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x414d4431,
            .interface_id_hi = 0x52344f53,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 40,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn get_info(self: *const InfoV1Client, output: *R4AmdInfo, output_bytes: u32) i32 {
        const function = r4os.runtime_r4l.functionAt(InfoV1GetInfoFn, self.header, 32) orelse unreachable;
        return function(output, output_bytes);
    }
};

pub const BackendV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !BackendV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, backend_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x414d4432,
            .interface_id_hi = 0x52344f53,
            .abi_major = 1,
            .min_revision = 3,
            .required_size = 64,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 56) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn negotiate(self: *const BackendV1Client, profile: *const R4AmdDeviceProfile, output: *R4AmdFeatures) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1NegotiateFn, self.header, 32) orelse unreachable;
        return function(profile, output);
    }

    pub fn encode_copy(self: *const BackendV1Client, request: *const R4AmdCopy, commands: [*]u32, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1EncodeCopyFn, self.header, 40) orelse unreachable;
        return function(request, commands, capacity, written);
    }

    pub fn encode_fill(self: *const BackendV1Client, request: *const R4AmdFill, commands: [*]u32, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1EncodeFillFn, self.header, 48) orelse unreachable;
        return function(request, commands, capacity, written);
    }

    pub fn encode_pm4_frame(self: *const BackendV1Client, request: *const R4AmdPm4Frame, commands: [*]u32, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1EncodePm4FrameFn, self.header, 56) orelse unreachable;
        return function(request, commands, capacity, written);
    }
};
