/* Generated by R4LContractGen. Do not edit. */
#ifndef R4ACO_R4L_BINDING_H
#define R4ACO_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4AcoInfo {
    uint32_t version;
    uint32_t size;
    uint32_t mesa_major;
    uint32_t mesa_minor;
    uint32_t mesa_patch;
    uint32_t implementation_stage;
    uint32_t capability_flags;
    uint32_t reserved;
} R4AcoInfo;
_Static_assert(sizeof(R4AcoInfo) == 32u, "R4AcoInfo size mismatch");
_Static_assert(offsetof(R4AcoInfo, version) == 0u, "R4AcoInfo.version offset mismatch");
_Static_assert(offsetof(R4AcoInfo, size) == 4u, "R4AcoInfo.size offset mismatch");
_Static_assert(offsetof(R4AcoInfo, mesa_major) == 8u, "R4AcoInfo.mesa_major offset mismatch");
_Static_assert(offsetof(R4AcoInfo, mesa_minor) == 12u, "R4AcoInfo.mesa_minor offset mismatch");
_Static_assert(offsetof(R4AcoInfo, mesa_patch) == 16u, "R4AcoInfo.mesa_patch offset mismatch");
_Static_assert(offsetof(R4AcoInfo, implementation_stage) == 20u, "R4AcoInfo.implementation_stage offset mismatch");
_Static_assert(offsetof(R4AcoInfo, capability_flags) == 24u, "R4AcoInfo.capability_flags offset mismatch");
_Static_assert(offsetof(R4AcoInfo, reserved) == 28u, "R4AcoInfo.reserved offset mismatch");

typedef struct R4AcoDigest {
    uint64_t h0;
    uint64_t h1;
    uint64_t h2;
    uint64_t h3;
} R4AcoDigest;
_Static_assert(sizeof(R4AcoDigest) == 32u, "R4AcoDigest size mismatch");
_Static_assert(offsetof(R4AcoDigest, h0) == 0u, "R4AcoDigest.h0 offset mismatch");
_Static_assert(offsetof(R4AcoDigest, h1) == 8u, "R4AcoDigest.h1 offset mismatch");
_Static_assert(offsetof(R4AcoDigest, h2) == 16u, "R4AcoDigest.h2 offset mismatch");
_Static_assert(offsetof(R4AcoDigest, h3) == 24u, "R4AcoDigest.h3 offset mismatch");

typedef struct R4AcoRuntime {
    uint32_t version;
    uint32_t size;
    uint64_t user;
    uint64_t owner_generation;
    uint64_t allocate;
    uint64_t release;
    uint64_t clock_ns;
    uint64_t abort_worker;
    uint64_t owner_retired;
    uint64_t cancelled;
} R4AcoRuntime;
_Static_assert(sizeof(R4AcoRuntime) == 72u, "R4AcoRuntime size mismatch");
_Static_assert(offsetof(R4AcoRuntime, version) == 0u, "R4AcoRuntime.version offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, size) == 4u, "R4AcoRuntime.size offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, user) == 8u, "R4AcoRuntime.user offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, owner_generation) == 16u, "R4AcoRuntime.owner_generation offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, allocate) == 24u, "R4AcoRuntime.allocate offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, release) == 32u, "R4AcoRuntime.release offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, clock_ns) == 40u, "R4AcoRuntime.clock_ns offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, abort_worker) == 48u, "R4AcoRuntime.abort_worker offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, owner_retired) == 56u, "R4AcoRuntime.owner_retired offset mismatch");
_Static_assert(offsetof(R4AcoRuntime, cancelled) == 64u, "R4AcoRuntime.cancelled offset mismatch");

typedef struct R4AcoRequest {
    uint32_t version;
    uint32_t size;
    uint32_t stage;
    uint32_t device_id;
    uint32_t chip_revision;
    uint32_t flags;
    uint32_t word_count;
    uint32_t entry_length;
    uint64_t words;
    uint64_t entry;
    uint64_t budget_bytes;
    uint64_t deadline_ns;
    uint64_t code;
    uint32_t code_capacity;
    uint32_t log_capacity;
    uint64_t log;
} R4AcoRequest;
_Static_assert(sizeof(R4AcoRequest) == 88u, "R4AcoRequest size mismatch");
_Static_assert(offsetof(R4AcoRequest, version) == 0u, "R4AcoRequest.version offset mismatch");
_Static_assert(offsetof(R4AcoRequest, size) == 4u, "R4AcoRequest.size offset mismatch");
_Static_assert(offsetof(R4AcoRequest, stage) == 8u, "R4AcoRequest.stage offset mismatch");
_Static_assert(offsetof(R4AcoRequest, device_id) == 12u, "R4AcoRequest.device_id offset mismatch");
_Static_assert(offsetof(R4AcoRequest, chip_revision) == 16u, "R4AcoRequest.chip_revision offset mismatch");
_Static_assert(offsetof(R4AcoRequest, flags) == 20u, "R4AcoRequest.flags offset mismatch");
_Static_assert(offsetof(R4AcoRequest, word_count) == 24u, "R4AcoRequest.word_count offset mismatch");
_Static_assert(offsetof(R4AcoRequest, entry_length) == 28u, "R4AcoRequest.entry_length offset mismatch");
_Static_assert(offsetof(R4AcoRequest, words) == 32u, "R4AcoRequest.words offset mismatch");
_Static_assert(offsetof(R4AcoRequest, entry) == 40u, "R4AcoRequest.entry offset mismatch");
_Static_assert(offsetof(R4AcoRequest, budget_bytes) == 48u, "R4AcoRequest.budget_bytes offset mismatch");
_Static_assert(offsetof(R4AcoRequest, deadline_ns) == 56u, "R4AcoRequest.deadline_ns offset mismatch");
_Static_assert(offsetof(R4AcoRequest, code) == 64u, "R4AcoRequest.code offset mismatch");
_Static_assert(offsetof(R4AcoRequest, code_capacity) == 72u, "R4AcoRequest.code_capacity offset mismatch");
_Static_assert(offsetof(R4AcoRequest, log_capacity) == 76u, "R4AcoRequest.log_capacity offset mismatch");
_Static_assert(offsetof(R4AcoRequest, log) == 80u, "R4AcoRequest.log offset mismatch");

typedef struct R4AcoSymbols {
    uint64_t s0;
    uint64_t s1;
    uint64_t s2;
    uint64_t s3;
    uint64_t s4;
    uint64_t s5;
    uint64_t s6;
    uint64_t s7;
    uint64_t s8;
    uint64_t s9;
    uint64_t s10;
    uint64_t s11;
    uint64_t s12;
    uint64_t s13;
    uint64_t s14;
    uint64_t s15;
    uint64_t s16;
    uint64_t s17;
    uint64_t s18;
    uint64_t s19;
    uint64_t s20;
    uint64_t s21;
    uint64_t s22;
    uint64_t s23;
    uint64_t s24;
    uint64_t s25;
    uint64_t s26;
    uint64_t s27;
    uint64_t s28;
    uint64_t s29;
    uint64_t s30;
    uint64_t s31;
} R4AcoSymbols;
_Static_assert(sizeof(R4AcoSymbols) == 256u, "R4AcoSymbols size mismatch");
_Static_assert(offsetof(R4AcoSymbols, s0) == 0u, "R4AcoSymbols.s0 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s1) == 8u, "R4AcoSymbols.s1 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s2) == 16u, "R4AcoSymbols.s2 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s3) == 24u, "R4AcoSymbols.s3 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s4) == 32u, "R4AcoSymbols.s4 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s5) == 40u, "R4AcoSymbols.s5 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s6) == 48u, "R4AcoSymbols.s6 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s7) == 56u, "R4AcoSymbols.s7 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s8) == 64u, "R4AcoSymbols.s8 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s9) == 72u, "R4AcoSymbols.s9 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s10) == 80u, "R4AcoSymbols.s10 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s11) == 88u, "R4AcoSymbols.s11 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s12) == 96u, "R4AcoSymbols.s12 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s13) == 104u, "R4AcoSymbols.s13 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s14) == 112u, "R4AcoSymbols.s14 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s15) == 120u, "R4AcoSymbols.s15 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s16) == 128u, "R4AcoSymbols.s16 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s17) == 136u, "R4AcoSymbols.s17 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s18) == 144u, "R4AcoSymbols.s18 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s19) == 152u, "R4AcoSymbols.s19 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s20) == 160u, "R4AcoSymbols.s20 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s21) == 168u, "R4AcoSymbols.s21 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s22) == 176u, "R4AcoSymbols.s22 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s23) == 184u, "R4AcoSymbols.s23 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s24) == 192u, "R4AcoSymbols.s24 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s25) == 200u, "R4AcoSymbols.s25 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s26) == 208u, "R4AcoSymbols.s26 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s27) == 216u, "R4AcoSymbols.s27 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s28) == 224u, "R4AcoSymbols.s28 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s29) == 232u, "R4AcoSymbols.s29 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s30) == 240u, "R4AcoSymbols.s30 offset mismatch");
_Static_assert(offsetof(R4AcoSymbols, s31) == 248u, "R4AcoSymbols.s31 offset mismatch");

typedef struct R4AcoBinary {
    uint32_t version;
    uint32_t size;
    int32_t status;
    uint32_t stage;
    uint32_t device_id;
    uint32_t chip_revision;
    uint32_t gfx_profile;
    uint32_t resource_abi;
    uint32_t code_bytes;
    uint32_t exec_bytes;
    uint32_t sgprs;
    uint32_t vgprs;
    uint32_t lds_bytes;
    uint32_t scratch_bytes_per_wave;
    uint32_t float_mode;
    uint32_t user_sgprs;
    uint32_t input_vgprs;
    uint32_t workgroup_x;
    uint32_t workgroup_y;
    uint32_t workgroup_z;
    uint32_t spi_ps_input_ena;
    uint32_t spi_ps_input_addr;
    uint32_t spi_shader_col_format;
    uint32_t symbol_count;
    uint64_t inputs_read;
    uint64_t outputs_written;
    R4AcoDigest source_hash;
    R4AcoSymbols symbols;
    uint64_t peak_bytes;
    uint64_t elapsed_ns;
    uint32_t log_length;
    uint32_t reserved;
} R4AcoBinary;
_Static_assert(sizeof(R4AcoBinary) == 424u, "R4AcoBinary size mismatch");
_Static_assert(offsetof(R4AcoBinary, version) == 0u, "R4AcoBinary.version offset mismatch");
_Static_assert(offsetof(R4AcoBinary, size) == 4u, "R4AcoBinary.size offset mismatch");
_Static_assert(offsetof(R4AcoBinary, status) == 8u, "R4AcoBinary.status offset mismatch");
_Static_assert(offsetof(R4AcoBinary, stage) == 12u, "R4AcoBinary.stage offset mismatch");
_Static_assert(offsetof(R4AcoBinary, device_id) == 16u, "R4AcoBinary.device_id offset mismatch");
_Static_assert(offsetof(R4AcoBinary, chip_revision) == 20u, "R4AcoBinary.chip_revision offset mismatch");
_Static_assert(offsetof(R4AcoBinary, gfx_profile) == 24u, "R4AcoBinary.gfx_profile offset mismatch");
_Static_assert(offsetof(R4AcoBinary, resource_abi) == 28u, "R4AcoBinary.resource_abi offset mismatch");
_Static_assert(offsetof(R4AcoBinary, code_bytes) == 32u, "R4AcoBinary.code_bytes offset mismatch");
_Static_assert(offsetof(R4AcoBinary, exec_bytes) == 36u, "R4AcoBinary.exec_bytes offset mismatch");
_Static_assert(offsetof(R4AcoBinary, sgprs) == 40u, "R4AcoBinary.sgprs offset mismatch");
_Static_assert(offsetof(R4AcoBinary, vgprs) == 44u, "R4AcoBinary.vgprs offset mismatch");
_Static_assert(offsetof(R4AcoBinary, lds_bytes) == 48u, "R4AcoBinary.lds_bytes offset mismatch");
_Static_assert(offsetof(R4AcoBinary, scratch_bytes_per_wave) == 52u, "R4AcoBinary.scratch_bytes_per_wave offset mismatch");
_Static_assert(offsetof(R4AcoBinary, float_mode) == 56u, "R4AcoBinary.float_mode offset mismatch");
_Static_assert(offsetof(R4AcoBinary, user_sgprs) == 60u, "R4AcoBinary.user_sgprs offset mismatch");
_Static_assert(offsetof(R4AcoBinary, input_vgprs) == 64u, "R4AcoBinary.input_vgprs offset mismatch");
_Static_assert(offsetof(R4AcoBinary, workgroup_x) == 68u, "R4AcoBinary.workgroup_x offset mismatch");
_Static_assert(offsetof(R4AcoBinary, workgroup_y) == 72u, "R4AcoBinary.workgroup_y offset mismatch");
_Static_assert(offsetof(R4AcoBinary, workgroup_z) == 76u, "R4AcoBinary.workgroup_z offset mismatch");
_Static_assert(offsetof(R4AcoBinary, spi_ps_input_ena) == 80u, "R4AcoBinary.spi_ps_input_ena offset mismatch");
_Static_assert(offsetof(R4AcoBinary, spi_ps_input_addr) == 84u, "R4AcoBinary.spi_ps_input_addr offset mismatch");
_Static_assert(offsetof(R4AcoBinary, spi_shader_col_format) == 88u, "R4AcoBinary.spi_shader_col_format offset mismatch");
_Static_assert(offsetof(R4AcoBinary, symbol_count) == 92u, "R4AcoBinary.symbol_count offset mismatch");
_Static_assert(offsetof(R4AcoBinary, inputs_read) == 96u, "R4AcoBinary.inputs_read offset mismatch");
_Static_assert(offsetof(R4AcoBinary, outputs_written) == 104u, "R4AcoBinary.outputs_written offset mismatch");
_Static_assert(offsetof(R4AcoBinary, source_hash) == 112u, "R4AcoBinary.source_hash offset mismatch");
_Static_assert(offsetof(R4AcoBinary, symbols) == 144u, "R4AcoBinary.symbols offset mismatch");
_Static_assert(offsetof(R4AcoBinary, peak_bytes) == 400u, "R4AcoBinary.peak_bytes offset mismatch");
_Static_assert(offsetof(R4AcoBinary, elapsed_ns) == 408u, "R4AcoBinary.elapsed_ns offset mismatch");
_Static_assert(offsetof(R4AcoBinary, log_length) == 416u, "R4AcoBinary.log_length offset mismatch");
_Static_assert(offsetof(R4AcoBinary, reserved) == 420u, "R4AcoBinary.reserved offset mismatch");

typedef struct R4AcoCacheKey {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t chip_revision;
    uint32_t gfx_profile;
    uint32_t stage;
    uint32_t resource_abi;
    uint32_t command_abi;
    uint32_t driver_version;
    uint32_t format;
    uint32_t reserved;
    uint64_t device_generation;
    uint64_t reset_generation;
    uint64_t pipeline_layout;
    R4AcoDigest source_hash;
    R4AcoDigest pipeline_hash;
} R4AcoCacheKey;
_Static_assert(sizeof(R4AcoCacheKey) == 136u, "R4AcoCacheKey size mismatch");
_Static_assert(offsetof(R4AcoCacheKey, version) == 0u, "R4AcoCacheKey.version offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, size) == 4u, "R4AcoCacheKey.size offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, vendor_id) == 8u, "R4AcoCacheKey.vendor_id offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, device_id) == 12u, "R4AcoCacheKey.device_id offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, chip_revision) == 16u, "R4AcoCacheKey.chip_revision offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, gfx_profile) == 20u, "R4AcoCacheKey.gfx_profile offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, stage) == 24u, "R4AcoCacheKey.stage offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, resource_abi) == 28u, "R4AcoCacheKey.resource_abi offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, command_abi) == 32u, "R4AcoCacheKey.command_abi offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, driver_version) == 36u, "R4AcoCacheKey.driver_version offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, format) == 40u, "R4AcoCacheKey.format offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, reserved) == 44u, "R4AcoCacheKey.reserved offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, device_generation) == 48u, "R4AcoCacheKey.device_generation offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, reset_generation) == 56u, "R4AcoCacheKey.reset_generation offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, pipeline_layout) == 64u, "R4AcoCacheKey.pipeline_layout offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, source_hash) == 72u, "R4AcoCacheKey.source_hash offset mismatch");
_Static_assert(offsetof(R4AcoCacheKey, pipeline_hash) == 104u, "R4AcoCacheKey.pipeline_hash offset mismatch");

#define R4ACO_INFO_VERSION ((uint32_t)1)
#define R4ACO_STATUS_OK ((int32_t)0)
#define R4ACO_COMPILER_REVISION ((uint32_t)1)
#define R4ACO_CAPABILITY_CPU_COMPILE ((uint32_t)1)
#define R4ACO_STATUS_INVALID ((int32_t)-1)
#define R4ACO_STATUS_UNSUPPORTED ((int32_t)-2)
#define R4ACO_STATUS_BUSY ((int32_t)-3)
#define R4ACO_STATUS_MEMORY ((int32_t)-4)
#define R4ACO_STATUS_CANCELLED ((int32_t)-5)
#define R4ACO_STATUS_COMPILER ((int32_t)-6)
#define R4ACO_STATUS_CAPACITY ((int32_t)-7)
#define R4ACO_STATUS_CACHE_MISS ((int32_t)-8)

#define R4ACO_INFO_V1_EXPORT_NAME "INFO_V1"
#define R4ACO_INFO_V1_ABI_MAJOR 1u
#define R4ACO_INFO_V1_REVISION 1u
#define R4ACO_INFO_V1_INTERFACE_ID_LO 0x41434f31ull
#define R4ACO_INFO_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4ACO_INFO_V1_TABLE_SIZE 40u
#define R4ACO_INFO_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4ACO_INFO_V1_TABLE_SIZE, R4ACO_INFO_V1_ABI_MAJOR, R4ACO_INFO_V1_REVISION, R4ACO_INFO_V1_INTERFACE_ID_LO, R4ACO_INFO_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AcoInfoV1GetInfoFn)(R4AcoInfo * output, uint32_t output_bytes);
typedef struct R4AcoInfoV1 {
    R4LInterfaceHeader header;
    R4AcoInfoV1GetInfoFn get_info;
} R4AcoInfoV1;
_Static_assert(sizeof(R4AcoInfoV1) == 40u, "R4AcoInfoV1 size mismatch");
_Static_assert(offsetof(R4AcoInfoV1, get_info) == 32u, "R4AcoInfoV1.get_info offset mismatch");
typedef struct R4AcoInfoV1Client { const R4LInterfaceHeader *header; } R4AcoInfoV1Client;

static inline int32_t r4aco_info_v1_init(const R4XStartContext *ctx, R4AcoInfoV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4ACO", "INFO_V1");
    const R4LInterfaceExpectation expected = { 0x41434f31ull, 0x52344f53ull, 1u, 1u, 40u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4aco_get_info(R4AcoInfoV1Client *client, R4AcoInfo * output, uint32_t output_bytes) {
    R4AcoInfoV1GetInfoFn function = (R4AcoInfoV1GetInfoFn)r4l_slot_address(client->header, 32u);
    return function(output, output_bytes);
}

#define R4ACO_COMPILER_V1_EXPORT_NAME "COMPILER_V1"
#define R4ACO_COMPILER_V1_ABI_MAJOR 1u
#define R4ACO_COMPILER_V1_REVISION 1u
#define R4ACO_COMPILER_V1_INTERFACE_ID_LO 0x41434f32ull
#define R4ACO_COMPILER_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4ACO_COMPILER_V1_TABLE_SIZE 56u
#define R4ACO_COMPILER_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4ACO_COMPILER_V1_TABLE_SIZE, R4ACO_COMPILER_V1_ABI_MAJOR, R4ACO_COMPILER_V1_REVISION, R4ACO_COMPILER_V1_INTERFACE_ID_LO, R4ACO_COMPILER_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AcoCompilerV1CompileFn)(const R4AcoRuntime * runtime, const R4AcoRequest * request, R4AcoBinary * output);
typedef int32_t (*R4AcoCompilerV1CacheWriteFn)(const R4AcoCacheKey * key, const R4AcoBinary * binary, const uint8_t * code, uint64_t code_length, uint8_t * bytes, uint64_t capacity, uint64_t * written);
typedef int32_t (*R4AcoCompilerV1CacheReadFn)(const R4AcoCacheKey * key, const uint8_t * bytes, uint64_t length, R4AcoBinary * output, uint8_t * code, uint64_t capacity);
typedef struct R4AcoCompilerV1 {
    R4LInterfaceHeader header;
    R4AcoCompilerV1CompileFn compile;
    R4AcoCompilerV1CacheWriteFn cache_write;
    R4AcoCompilerV1CacheReadFn cache_read;
} R4AcoCompilerV1;
_Static_assert(sizeof(R4AcoCompilerV1) == 56u, "R4AcoCompilerV1 size mismatch");
_Static_assert(offsetof(R4AcoCompilerV1, compile) == 32u, "R4AcoCompilerV1.compile offset mismatch");
_Static_assert(offsetof(R4AcoCompilerV1, cache_write) == 40u, "R4AcoCompilerV1.cache_write offset mismatch");
_Static_assert(offsetof(R4AcoCompilerV1, cache_read) == 48u, "R4AcoCompilerV1.cache_read offset mismatch");
typedef struct R4AcoCompilerV1Client { const R4LInterfaceHeader *header; } R4AcoCompilerV1Client;

static inline int32_t r4aco_compiler_v1_init(const R4XStartContext *ctx, R4AcoCompilerV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4ACO", "COMPILER_V1");
    const R4LInterfaceExpectation expected = { 0x41434f32ull, 0x52344f53ull, 1u, 1u, 56u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4aco_compile(R4AcoCompilerV1Client *client, const R4AcoRuntime * runtime, const R4AcoRequest * request, R4AcoBinary * output) {
    R4AcoCompilerV1CompileFn function = (R4AcoCompilerV1CompileFn)r4l_slot_address(client->header, 32u);
    return function(runtime, request, output);
}

static inline int32_t r4aco_cache_write(R4AcoCompilerV1Client *client, const R4AcoCacheKey * key, const R4AcoBinary * binary, const uint8_t * code, uint64_t code_length, uint8_t * bytes, uint64_t capacity, uint64_t * written) {
    R4AcoCompilerV1CacheWriteFn function = (R4AcoCompilerV1CacheWriteFn)r4l_slot_address(client->header, 40u);
    return function(key, binary, code, code_length, bytes, capacity, written);
}

static inline int32_t r4aco_cache_read(R4AcoCompilerV1Client *client, const R4AcoCacheKey * key, const uint8_t * bytes, uint64_t length, R4AcoBinary * output, uint8_t * code, uint64_t capacity) {
    R4AcoCompilerV1CacheReadFn function = (R4AcoCompilerV1CacheReadFn)r4l_slot_address(client->header, 48u);
    return function(key, bytes, length, output, code, capacity);
}

#endif
