const std = @import("std");

pub fn build(b: *std.Build) void {
    b.addNamedLazyPath("binding", b.path("Bindings/Zig/r4enc.zig"));
    b.addNamedLazyPath("c_include", b.path("Bindings/C"));
    b.addNamedLazyPath("recording_mux", b.path("Bindings/Zig/recording_mux.zig"));
    b.addNamedLazyPath("recording_pixels", b.path("Bindings/Zig/recording_pixels.zig"));
    const sdk_build = b.lazyImport(@This(), "r4os_sdk") orelse return;
    const sdk = sdk_build.sdk(b, b.dependencyFromBuildZig(sdk_build, .{}), .{});
    const host = sdk.createR4osModule(b.graph.host, .ReleaseSafe);
    const implementation = b.createModule(.{ .root_source_file = b.path("Contract/Generated/implementation_abi.zig"), .target = b.graph.host });
    implementation.addImport("r4os", host);
    const binding = b.createModule(.{ .root_source_file = b.path("Bindings/Zig/r4enc.zig"), .target = b.graph.host });
    binding.addImport("r4os", host);
    const conformance = b.createModule(.{ .root_source_file = b.path("Tests/Generated/contract_conformance.zig"), .target = b.graph.host });
    conformance.addImport("implementation", implementation);
    conformance.addImport("binding", binding);
    conformance.addIncludePath(b.path("Bindings/C"));
    conformance.addIncludePath(sdk.profile.c_include_root);
    conformance.addIncludePath(sdk.profile.contract_c_include_root);
    conformance.addCSourceFile(.{ .file = b.path("Tests/Generated/contract_conformance.c"), .flags = &.{ "-std=c11", "-Wall", "-Wextra", "-Werror" } });
    const parity = b.createModule(.{ .root_source_file = b.path("Tests/graphics_parity.zig"), .target = b.graph.host });
    parity.addImport("r4os", host);
    parity.addImport("binding", binding);
    const allocations = b.createModule(.{ .root_source_file = b.path("../Shared/Native/budgeted_allocation.zig"), .target = b.graph.host });
    const input = b.createModule(.{ .root_source_file = b.path("Source/input.zig"), .target = b.graph.host });
    input.addImport("r4os", host);
    input.addImport("native_allocation", allocations);
    parity.addImport("encode_input", input);
    parity.addImport("native_allocation", allocations);
    parity.addImport("encode_flow", b.createModule(.{ .root_source_file = b.path("Source/flow.zig"), .target = b.graph.host }));
    const nv = b.createModule(.{ .root_source_file = b.path("../R4NV/Bindings/Zig/r4nv.zig"), .target = b.graph.host });
    nv.addImport("r4os", host);
    const amd = b.createModule(.{ .root_source_file = b.path("../R4AMD/Bindings/Zig/r4amd.zig"), .target = b.graph.host });
    amd.addImport("r4os", host);
    const amd_media = b.createModule(.{ .root_source_file = b.path("../R4AMD/Source/media.zig"), .target = b.graph.host });
    const gpu = b.createModule(.{ .root_source_file = b.path("../Shared/Native/gpu_resources.zig"), .target = b.graph.host });
    gpu.addImport("r4os", host);
    gpu.addImport("r4nv_binding", nv);
    gpu.addImport("r4amd", amd);
    gpu.addImport("r4amd_media", amd_media);
    gpu.addImport("native_allocation", allocations);
    const gpu_model = b.createModule(.{ .root_source_file = b.path("../Shared/Native/Tests/gpu_model.zig"), .target = b.graph.host });
    gpu_model.addImport("r4os", host);
    gpu_model.addImport("r4nv_binding", nv);
    gpu_model.addImport("gpu_resources", gpu);
    gpu_model.addImport("r4amd", amd);
    gpu_model.addImport("r4amd_media", amd_media);
    const encoder = b.createModule(.{ .root_source_file = b.path("Source/gpu_encoder.zig"), .target = b.graph.host });
    const encode = b.createModule(.{ .root_source_file = b.path("../R4NV/Source/encode.zig"), .target = b.graph.host });
    encoder.addImport("r4os", host);
    encoder.addImport("gpu_resources", gpu);
    encoder.addImport("r4nv_encode", encode);
    parity.addImport("gpu_resources", gpu);
    parity.addImport("gpu_model", gpu_model);
    parity.addImport("gpu_encoder", encoder);
    parity.addImport("r4nv_encode", encode);
    const render = b.createModule(.{ .root_source_file = b.path("../R4NV/Source/render.zig"), .target = b.graph.host });
    const preparer = b.createModule(.{ .root_source_file = b.path("Source/gpu_input.zig"), .target = b.graph.host });
    preparer.addImport("r4os", host);
    preparer.addImport("gpu_resources", gpu);
    preparer.addImport("r4nv_render", render);
    preparer.addImport("gpu_encoder", encoder);
    preparer.addImport("encode_input", input);
    parity.addImport("gpu_input", preparer);
    parity.addImport("r4nv_render", render);
    const backend = b.createModule(.{ .root_source_file = b.path("Source/gpu_backend.zig"), .target = b.graph.host });
    backend.addImport("r4os", host);
    backend.addImport("gpu_resources", gpu);
    backend.addImport("r4nv_encode", encode);
    backend.addImport("gpu_encoder", encoder);
    backend.addImport("gpu_input", preparer);
    backend.addImport("native_allocation", allocations);
    parity.addImport("gpu_backend", backend);
    const amd_encoder = b.createModule(.{ .root_source_file = b.path("Source/amd_encoder.zig"), .target = b.graph.host });
    amd_encoder.addImport("r4os", host);
    amd_encoder.addImport("gpu_resources", gpu);
    amd_encoder.addImport("native_allocation", allocations);
    amd_encoder.addIncludePath(b.path("../R4AMD/Port"));
    parity.addImport("amd_encoder", amd_encoder);
    parity.addIncludePath(b.path("../R4AMD/Port"));
    parity.addCSourceFile(.{ .file = b.path("../R4AMD/Port/vcn_encode.c"), .flags = &.{"-std=c17"} });
    parity.link_libc = true;
    parity.addImport("recording_mux", b.createModule(.{ .root_source_file = b.path("Bindings/Zig/recording_mux.zig"), .target = b.graph.host }));
    parity.addImport("recording_pixels", b.createModule(.{ .root_source_file = b.path("Bindings/Zig/recording_pixels.zig"), .target = b.graph.host }));
    const check = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    check.addFileArg(b.path("Tools/Contract.ps1"));
    check.has_side_effects = true;
    const tests = b.step("test", "ENCODE_V1 ABI and canonical graphics identities");
    tests.dependOn(&check.step);
    const vcn = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    vcn.addFileArg(b.path("../R4AMD/Tools/VcnEncode.ps1"));
    vcn.has_side_effects = true;
    tests.dependOn(&vcn.step);
    for ([_]*std.Build.Module{ conformance, parity }) |module| {
        const run = b.addRunArtifact(b.addTest(.{ .root_module = module }));
        tests.dependOn(&run.step);
    }
    const native = b.addSystemCommand(&.{ "pwsh", "-NoLogo", "-NoProfile", "-File" });
    native.addFileArg(b.path("Tools/Build.ps1"));
    native.addArg("-OutputRoot");
    const archives = native.addOutputDirectoryArg("native");
    if (b.option(bool, "offline", "Require cached source archives") orelse false) native.addArg("-Offline");
    native.has_side_effects = true;
    _ = sdk.addR4MFWithOptions(b.path("module.R4MF"), .{ .native_archives = &.{
        archives.path(b, "R4ENC-OpenH264.a"), archives.path(b, "R4NativeMath.a"),
    } });
    b.getInstallStep().dependOn(tests);
}
