/* Generated by R4LContractGen. Do not edit. */
#ifndef R4AMD_R4L_BINDING_H
#define R4AMD_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4AmdInfo {
    uint32_t version;
    uint32_t size;
    uint32_t mesa_major;
    uint32_t mesa_minor;
    uint32_t mesa_patch;
    uint32_t implementation_stage;
    uint32_t capability_flags;
    uint32_t reserved;
} R4AmdInfo;
_Static_assert(sizeof(R4AmdInfo) == 32u, "R4AmdInfo size mismatch");
_Static_assert(offsetof(R4AmdInfo, version) == 0u, "R4AmdInfo.version offset mismatch");
_Static_assert(offsetof(R4AmdInfo, size) == 4u, "R4AmdInfo.size offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_major) == 8u, "R4AmdInfo.mesa_major offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_minor) == 12u, "R4AmdInfo.mesa_minor offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_patch) == 16u, "R4AmdInfo.mesa_patch offset mismatch");
_Static_assert(offsetof(R4AmdInfo, implementation_stage) == 20u, "R4AmdInfo.implementation_stage offset mismatch");
_Static_assert(offsetof(R4AmdInfo, capability_flags) == 24u, "R4AmdInfo.capability_flags offset mismatch");
_Static_assert(offsetof(R4AmdInfo, reserved) == 28u, "R4AmdInfo.reserved offset mismatch");

#define R4AMD_INFO_VERSION ((uint32_t)1)
#define R4AMD_STATUS_OK ((int32_t)0)
#define R4AMD_STATUS_INVALID ((int32_t)-1)

#define R4AMD_INFO_V1_EXPORT_NAME "INFO_V1"
#define R4AMD_INFO_V1_ABI_MAJOR 1u
#define R4AMD_INFO_V1_REVISION 1u
#define R4AMD_INFO_V1_INTERFACE_ID_LO 0x414d4431ull
#define R4AMD_INFO_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4AMD_INFO_V1_TABLE_SIZE 40u
#define R4AMD_INFO_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4AMD_INFO_V1_TABLE_SIZE, R4AMD_INFO_V1_ABI_MAJOR, R4AMD_INFO_V1_REVISION, R4AMD_INFO_V1_INTERFACE_ID_LO, R4AMD_INFO_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AmdInfoV1GetInfoFn)(R4AmdInfo * output, uint32_t output_bytes);
typedef struct R4AmdInfoV1 {
    R4LInterfaceHeader header;
    R4AmdInfoV1GetInfoFn get_info;
} R4AmdInfoV1;
_Static_assert(sizeof(R4AmdInfoV1) == 40u, "R4AmdInfoV1 size mismatch");
_Static_assert(offsetof(R4AmdInfoV1, get_info) == 32u, "R4AmdInfoV1.get_info offset mismatch");
typedef struct R4AmdInfoV1Client { const R4LInterfaceHeader *header; } R4AmdInfoV1Client;

static inline int32_t r4amd_info_v1_init(const R4XStartContext *ctx, R4AmdInfoV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4AMD", "INFO_V1");
    const R4LInterfaceExpectation expected = { 0x414d4431ull, 0x52344f53ull, 1u, 1u, 40u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4amd_get_info(R4AmdInfoV1Client *client, R4AmdInfo * output, uint32_t output_bytes) {
    R4AmdInfoV1GetInfoFn function = (R4AmdInfoV1GetInfoFn)r4l_slot_address(client->header, 32u);
    return function(output, output_bytes);
}

#endif
