/* Generated by R4LContractGen. Do not edit. */
#ifndef R4AMD_R4L_BINDING_H
#define R4AMD_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4AmdInfo {
    uint32_t version;
    uint32_t size;
    uint32_t mesa_major;
    uint32_t mesa_minor;
    uint32_t mesa_patch;
    uint32_t implementation_stage;
    uint32_t capability_flags;
    uint32_t reserved;
} R4AmdInfo;
_Static_assert(sizeof(R4AmdInfo) == 32u, "R4AmdInfo size mismatch");
_Static_assert(offsetof(R4AmdInfo, version) == 0u, "R4AmdInfo.version offset mismatch");
_Static_assert(offsetof(R4AmdInfo, size) == 4u, "R4AmdInfo.size offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_major) == 8u, "R4AmdInfo.mesa_major offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_minor) == 12u, "R4AmdInfo.mesa_minor offset mismatch");
_Static_assert(offsetof(R4AmdInfo, mesa_patch) == 16u, "R4AmdInfo.mesa_patch offset mismatch");
_Static_assert(offsetof(R4AmdInfo, implementation_stage) == 20u, "R4AmdInfo.implementation_stage offset mismatch");
_Static_assert(offsetof(R4AmdInfo, capability_flags) == 24u, "R4AmdInfo.capability_flags offset mismatch");
_Static_assert(offsetof(R4AmdInfo, reserved) == 28u, "R4AmdInfo.reserved offset mismatch");

typedef struct R4AmdDriverProfile {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t gc_version;
    uint32_t sdma_version;
    uint32_t command_abi;
    uint32_t reserved;
} R4AmdDriverProfile;
_Static_assert(sizeof(R4AmdDriverProfile) == 32u, "R4AmdDriverProfile size mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, version) == 0u, "R4AmdDriverProfile.version offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, size) == 4u, "R4AmdDriverProfile.size offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, vendor_id) == 8u, "R4AmdDriverProfile.vendor_id offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, device_id) == 12u, "R4AmdDriverProfile.device_id offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, gc_version) == 16u, "R4AmdDriverProfile.gc_version offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, sdma_version) == 20u, "R4AmdDriverProfile.sdma_version offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, command_abi) == 24u, "R4AmdDriverProfile.command_abi offset mismatch");
_Static_assert(offsetof(R4AmdDriverProfile, reserved) == 28u, "R4AmdDriverProfile.reserved offset mismatch");

typedef struct R4AmdDeviceProfile {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t gc_version;
    uint32_t sdma_version;
    uint32_t command_abi;
    uint32_t flags;
    uint32_t adapter_id;
    uint32_t reserved;
    uint64_t device_generation;
    uint64_t reset_generation;
} R4AmdDeviceProfile;
_Static_assert(sizeof(R4AmdDeviceProfile) == 56u, "R4AmdDeviceProfile size mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, version) == 0u, "R4AmdDeviceProfile.version offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, size) == 4u, "R4AmdDeviceProfile.size offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, vendor_id) == 8u, "R4AmdDeviceProfile.vendor_id offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, device_id) == 12u, "R4AmdDeviceProfile.device_id offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, gc_version) == 16u, "R4AmdDeviceProfile.gc_version offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, sdma_version) == 20u, "R4AmdDeviceProfile.sdma_version offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, command_abi) == 24u, "R4AmdDeviceProfile.command_abi offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, flags) == 28u, "R4AmdDeviceProfile.flags offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, adapter_id) == 32u, "R4AmdDeviceProfile.adapter_id offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, reserved) == 36u, "R4AmdDeviceProfile.reserved offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, device_generation) == 40u, "R4AmdDeviceProfile.device_generation offset mismatch");
_Static_assert(offsetof(R4AmdDeviceProfile, reset_generation) == 48u, "R4AmdDeviceProfile.reset_generation offset mismatch");

typedef struct R4AmdFeatures {
    uint32_t version;
    uint32_t size;
    uint32_t command_abi;
    uint32_t features;
    uint32_t gpu_address_bits;
    uint32_t max_command_words;
    uint32_t reserved0;
    uint32_t reserved1;
} R4AmdFeatures;
_Static_assert(sizeof(R4AmdFeatures) == 32u, "R4AmdFeatures size mismatch");
_Static_assert(offsetof(R4AmdFeatures, version) == 0u, "R4AmdFeatures.version offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, size) == 4u, "R4AmdFeatures.size offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, command_abi) == 8u, "R4AmdFeatures.command_abi offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, features) == 12u, "R4AmdFeatures.features offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, gpu_address_bits) == 16u, "R4AmdFeatures.gpu_address_bits offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, max_command_words) == 20u, "R4AmdFeatures.max_command_words offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, reserved0) == 24u, "R4AmdFeatures.reserved0 offset mismatch");
_Static_assert(offsetof(R4AmdFeatures, reserved1) == 28u, "R4AmdFeatures.reserved1 offset mismatch");

typedef struct R4AmdCopy {
    uint32_t version;
    uint32_t size;
    uint64_t source;
    uint64_t target;
    uint64_t byte_length;
    uint64_t source_pitch;
    uint64_t target_pitch;
    uint64_t source_modifier;
    uint64_t target_modifier;
    uint32_t row_count;
    uint32_t reserved;
} R4AmdCopy;
_Static_assert(sizeof(R4AmdCopy) == 72u, "R4AmdCopy size mismatch");
_Static_assert(offsetof(R4AmdCopy, version) == 0u, "R4AmdCopy.version offset mismatch");
_Static_assert(offsetof(R4AmdCopy, size) == 4u, "R4AmdCopy.size offset mismatch");
_Static_assert(offsetof(R4AmdCopy, source) == 8u, "R4AmdCopy.source offset mismatch");
_Static_assert(offsetof(R4AmdCopy, target) == 16u, "R4AmdCopy.target offset mismatch");
_Static_assert(offsetof(R4AmdCopy, byte_length) == 24u, "R4AmdCopy.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdCopy, source_pitch) == 32u, "R4AmdCopy.source_pitch offset mismatch");
_Static_assert(offsetof(R4AmdCopy, target_pitch) == 40u, "R4AmdCopy.target_pitch offset mismatch");
_Static_assert(offsetof(R4AmdCopy, source_modifier) == 48u, "R4AmdCopy.source_modifier offset mismatch");
_Static_assert(offsetof(R4AmdCopy, target_modifier) == 56u, "R4AmdCopy.target_modifier offset mismatch");
_Static_assert(offsetof(R4AmdCopy, row_count) == 64u, "R4AmdCopy.row_count offset mismatch");
_Static_assert(offsetof(R4AmdCopy, reserved) == 68u, "R4AmdCopy.reserved offset mismatch");

typedef struct R4AmdFill {
    uint32_t version;
    uint32_t size;
    uint64_t target;
    uint64_t byte_length;
    uint32_t value;
    uint32_t reserved;
} R4AmdFill;
_Static_assert(sizeof(R4AmdFill) == 32u, "R4AmdFill size mismatch");
_Static_assert(offsetof(R4AmdFill, version) == 0u, "R4AmdFill.version offset mismatch");
_Static_assert(offsetof(R4AmdFill, size) == 4u, "R4AmdFill.size offset mismatch");
_Static_assert(offsetof(R4AmdFill, target) == 8u, "R4AmdFill.target offset mismatch");
_Static_assert(offsetof(R4AmdFill, byte_length) == 16u, "R4AmdFill.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdFill, value) == 24u, "R4AmdFill.value offset mismatch");
_Static_assert(offsetof(R4AmdFill, reserved) == 28u, "R4AmdFill.reserved offset mismatch");

typedef struct R4AmdPm4Frame {
    uint32_t version;
    uint32_t size;
    uint32_t engine;
    uint32_t flags;
    uint64_t indirect_address;
    uint64_t fence_address;
    uint64_t eop_scratch;
    uint64_t fence_sequence;
    uint32_t command_dwords;
    uint32_t reserved0;
    uint64_t reserved1;
} R4AmdPm4Frame;
_Static_assert(sizeof(R4AmdPm4Frame) == 64u, "R4AmdPm4Frame size mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, version) == 0u, "R4AmdPm4Frame.version offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, size) == 4u, "R4AmdPm4Frame.size offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, engine) == 8u, "R4AmdPm4Frame.engine offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, flags) == 12u, "R4AmdPm4Frame.flags offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, indirect_address) == 16u, "R4AmdPm4Frame.indirect_address offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, fence_address) == 24u, "R4AmdPm4Frame.fence_address offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, eop_scratch) == 32u, "R4AmdPm4Frame.eop_scratch offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, fence_sequence) == 40u, "R4AmdPm4Frame.fence_sequence offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, command_dwords) == 48u, "R4AmdPm4Frame.command_dwords offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, reserved0) == 52u, "R4AmdPm4Frame.reserved0 offset mismatch");
_Static_assert(offsetof(R4AmdPm4Frame, reserved1) == 56u, "R4AmdPm4Frame.reserved1 offset mismatch");

typedef struct R4AmdImageRequest {
    uint32_t version;
    uint32_t size;
    uint32_t gb_addr_config;
    uint32_t chip_revision;
    uint32_t device_id;
    uint32_t gc_version;
    uint32_t resource_type;
    uint32_t format;
    uint32_t width;
    uint32_t height;
    uint32_t depth;
    uint32_t mip_count;
    uint32_t samples;
    uint32_t usage;
    uint32_t swizzle;
    uint32_t pipe_xor;
    uint32_t pitch;
    uint32_t reserved;
    uint64_t modifier;
} R4AmdImageRequest;
_Static_assert(sizeof(R4AmdImageRequest) == 80u, "R4AmdImageRequest size mismatch");
_Static_assert(offsetof(R4AmdImageRequest, version) == 0u, "R4AmdImageRequest.version offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, size) == 4u, "R4AmdImageRequest.size offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, gb_addr_config) == 8u, "R4AmdImageRequest.gb_addr_config offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, chip_revision) == 12u, "R4AmdImageRequest.chip_revision offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, device_id) == 16u, "R4AmdImageRequest.device_id offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, gc_version) == 20u, "R4AmdImageRequest.gc_version offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, resource_type) == 24u, "R4AmdImageRequest.resource_type offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, format) == 28u, "R4AmdImageRequest.format offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, width) == 32u, "R4AmdImageRequest.width offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, height) == 36u, "R4AmdImageRequest.height offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, depth) == 40u, "R4AmdImageRequest.depth offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, mip_count) == 44u, "R4AmdImageRequest.mip_count offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, samples) == 48u, "R4AmdImageRequest.samples offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, usage) == 52u, "R4AmdImageRequest.usage offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, swizzle) == 56u, "R4AmdImageRequest.swizzle offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, pipe_xor) == 60u, "R4AmdImageRequest.pipe_xor offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, pitch) == 64u, "R4AmdImageRequest.pitch offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, reserved) == 68u, "R4AmdImageRequest.reserved offset mismatch");
_Static_assert(offsetof(R4AmdImageRequest, modifier) == 72u, "R4AmdImageRequest.modifier offset mismatch");

typedef struct R4AmdImageLayout {
    uint32_t version;
    uint32_t size;
    uint64_t byte_length;
    uint64_t slice_bytes;
    uint64_t alignment;
    uint64_t modifier;
    uint32_t pitch;
    uint32_t height;
    uint32_t depth;
    uint32_t epitch;
    uint32_t block_width;
    uint32_t block_height;
    uint32_t block_depth;
    uint32_t first_mip_tail;
    uint32_t mip_count;
    uint32_t pixel_bits;
    uint32_t element_bits;
    uint32_t resource_type;
    uint32_t swizzle;
    uint32_t flags;
    uint32_t gb_addr_config;
    uint32_t reserved;
} R4AmdImageLayout;
_Static_assert(sizeof(R4AmdImageLayout) == 104u, "R4AmdImageLayout size mismatch");
_Static_assert(offsetof(R4AmdImageLayout, version) == 0u, "R4AmdImageLayout.version offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, size) == 4u, "R4AmdImageLayout.size offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, byte_length) == 8u, "R4AmdImageLayout.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, slice_bytes) == 16u, "R4AmdImageLayout.slice_bytes offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, alignment) == 24u, "R4AmdImageLayout.alignment offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, modifier) == 32u, "R4AmdImageLayout.modifier offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, pitch) == 40u, "R4AmdImageLayout.pitch offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, height) == 44u, "R4AmdImageLayout.height offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, depth) == 48u, "R4AmdImageLayout.depth offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, epitch) == 52u, "R4AmdImageLayout.epitch offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, block_width) == 56u, "R4AmdImageLayout.block_width offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, block_height) == 60u, "R4AmdImageLayout.block_height offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, block_depth) == 64u, "R4AmdImageLayout.block_depth offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, first_mip_tail) == 68u, "R4AmdImageLayout.first_mip_tail offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, mip_count) == 72u, "R4AmdImageLayout.mip_count offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, pixel_bits) == 76u, "R4AmdImageLayout.pixel_bits offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, element_bits) == 80u, "R4AmdImageLayout.element_bits offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, resource_type) == 84u, "R4AmdImageLayout.resource_type offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, swizzle) == 88u, "R4AmdImageLayout.swizzle offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, flags) == 92u, "R4AmdImageLayout.flags offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, gb_addr_config) == 96u, "R4AmdImageLayout.gb_addr_config offset mismatch");
_Static_assert(offsetof(R4AmdImageLayout, reserved) == 100u, "R4AmdImageLayout.reserved offset mismatch");

typedef struct R4AmdMip {
    uint32_t pitch;
    uint32_t height;
    uint32_t depth;
    uint32_t pixel_pitch;
    uint32_t pixel_height;
    uint32_t equation_index;
    uint64_t offset;
    uint64_t macro_offset;
    uint32_t tail_offset;
    uint32_t tail_x;
    uint32_t tail_y;
    uint32_t tail_z;
    uint64_t reserved;
} R4AmdMip;
_Static_assert(sizeof(R4AmdMip) == 64u, "R4AmdMip size mismatch");
_Static_assert(offsetof(R4AmdMip, pitch) == 0u, "R4AmdMip.pitch offset mismatch");
_Static_assert(offsetof(R4AmdMip, height) == 4u, "R4AmdMip.height offset mismatch");
_Static_assert(offsetof(R4AmdMip, depth) == 8u, "R4AmdMip.depth offset mismatch");
_Static_assert(offsetof(R4AmdMip, pixel_pitch) == 12u, "R4AmdMip.pixel_pitch offset mismatch");
_Static_assert(offsetof(R4AmdMip, pixel_height) == 16u, "R4AmdMip.pixel_height offset mismatch");
_Static_assert(offsetof(R4AmdMip, equation_index) == 20u, "R4AmdMip.equation_index offset mismatch");
_Static_assert(offsetof(R4AmdMip, offset) == 24u, "R4AmdMip.offset offset mismatch");
_Static_assert(offsetof(R4AmdMip, macro_offset) == 32u, "R4AmdMip.macro_offset offset mismatch");
_Static_assert(offsetof(R4AmdMip, tail_offset) == 40u, "R4AmdMip.tail_offset offset mismatch");
_Static_assert(offsetof(R4AmdMip, tail_x) == 44u, "R4AmdMip.tail_x offset mismatch");
_Static_assert(offsetof(R4AmdMip, tail_y) == 48u, "R4AmdMip.tail_y offset mismatch");
_Static_assert(offsetof(R4AmdMip, tail_z) == 52u, "R4AmdMip.tail_z offset mismatch");
_Static_assert(offsetof(R4AmdMip, reserved) == 56u, "R4AmdMip.reserved offset mismatch");

typedef struct R4AmdCoordinate {
    uint32_t version;
    uint32_t size;
    uint32_t x;
    uint32_t y;
    uint32_t slice;
    uint32_t sample;
    uint32_t mip;
    uint32_t reserved;
} R4AmdCoordinate;
_Static_assert(sizeof(R4AmdCoordinate) == 32u, "R4AmdCoordinate size mismatch");
_Static_assert(offsetof(R4AmdCoordinate, version) == 0u, "R4AmdCoordinate.version offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, size) == 4u, "R4AmdCoordinate.size offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, x) == 8u, "R4AmdCoordinate.x offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, y) == 12u, "R4AmdCoordinate.y offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, slice) == 16u, "R4AmdCoordinate.slice offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, sample) == 20u, "R4AmdCoordinate.sample offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, mip) == 24u, "R4AmdCoordinate.mip offset mismatch");
_Static_assert(offsetof(R4AmdCoordinate, reserved) == 28u, "R4AmdCoordinate.reserved offset mismatch");

typedef struct R4AmdImageAddress {
    uint32_t version;
    uint32_t size;
    uint64_t offset;
    uint32_t bit_position;
    uint32_t prt_block;
} R4AmdImageAddress;
_Static_assert(sizeof(R4AmdImageAddress) == 24u, "R4AmdImageAddress size mismatch");
_Static_assert(offsetof(R4AmdImageAddress, version) == 0u, "R4AmdImageAddress.version offset mismatch");
_Static_assert(offsetof(R4AmdImageAddress, size) == 4u, "R4AmdImageAddress.size offset mismatch");
_Static_assert(offsetof(R4AmdImageAddress, offset) == 8u, "R4AmdImageAddress.offset offset mismatch");
_Static_assert(offsetof(R4AmdImageAddress, bit_position) == 16u, "R4AmdImageAddress.bit_position offset mismatch");
_Static_assert(offsetof(R4AmdImageAddress, prt_block) == 20u, "R4AmdImageAddress.prt_block offset mismatch");

typedef struct R4AmdMetadata {
    uint32_t version;
    uint32_t size;
    uint32_t kind;
    uint32_t flags;
    uint64_t byte_length;
    uint64_t alignment;
    uint64_t slice_bytes;
    uint32_t block_width;
    uint32_t block_height;
    uint32_t block_depth;
    uint32_t compress_width;
    uint32_t compress_height;
    uint32_t compress_depth;
    uint64_t fast_clear_bytes;
} R4AmdMetadata;
_Static_assert(sizeof(R4AmdMetadata) == 72u, "R4AmdMetadata size mismatch");
_Static_assert(offsetof(R4AmdMetadata, version) == 0u, "R4AmdMetadata.version offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, size) == 4u, "R4AmdMetadata.size offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, kind) == 8u, "R4AmdMetadata.kind offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, flags) == 12u, "R4AmdMetadata.flags offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, byte_length) == 16u, "R4AmdMetadata.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, alignment) == 24u, "R4AmdMetadata.alignment offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, slice_bytes) == 32u, "R4AmdMetadata.slice_bytes offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, block_width) == 40u, "R4AmdMetadata.block_width offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, block_height) == 44u, "R4AmdMetadata.block_height offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, block_depth) == 48u, "R4AmdMetadata.block_depth offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, compress_width) == 52u, "R4AmdMetadata.compress_width offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, compress_height) == 56u, "R4AmdMetadata.compress_height offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, compress_depth) == 60u, "R4AmdMetadata.compress_depth offset mismatch");
_Static_assert(offsetof(R4AmdMetadata, fast_clear_bytes) == 64u, "R4AmdMetadata.fast_clear_bytes offset mismatch");

typedef struct R4AmdImageImport {
    uint32_t version;
    uint32_t size;
    uint64_t byte_length;
    uint64_t alignment;
    uint64_t offset;
    uint64_t modifier;
    uint32_t adapter_id;
    uint32_t reserved;
    uint64_t memory_generation;
    uint32_t expected_adapter;
    uint32_t metadata_state;
    uint64_t expected_memory_generation;
    uint32_t pitch;
    uint32_t usage;
} R4AmdImageImport;
_Static_assert(sizeof(R4AmdImageImport) == 80u, "R4AmdImageImport size mismatch");
_Static_assert(offsetof(R4AmdImageImport, version) == 0u, "R4AmdImageImport.version offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, size) == 4u, "R4AmdImageImport.size offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, byte_length) == 8u, "R4AmdImageImport.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, alignment) == 16u, "R4AmdImageImport.alignment offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, offset) == 24u, "R4AmdImageImport.offset offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, modifier) == 32u, "R4AmdImageImport.modifier offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, adapter_id) == 40u, "R4AmdImageImport.adapter_id offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, reserved) == 44u, "R4AmdImageImport.reserved offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, memory_generation) == 48u, "R4AmdImageImport.memory_generation offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, expected_adapter) == 56u, "R4AmdImageImport.expected_adapter offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, metadata_state) == 60u, "R4AmdImageImport.metadata_state offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, expected_memory_generation) == 64u, "R4AmdImageImport.expected_memory_generation offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, pitch) == 72u, "R4AmdImageImport.pitch offset mismatch");
_Static_assert(offsetof(R4AmdImageImport, usage) == 76u, "R4AmdImageImport.usage offset mismatch");

typedef struct R4AmdImageView {
    uint32_t version;
    uint32_t size;
    uint64_t address;
    uint64_t byte_length;
    uint64_t offset;
    uint32_t first_layer;
    uint32_t last_layer;
    uint32_t first_mip;
    uint32_t last_mip;
    uint32_t sampler;
    uint32_t min_lod;
    uint32_t max_lod;
    int32_t lod_bias;
    uint32_t wrap_u;
    uint32_t wrap_v;
    uint32_t wrap_w;
    uint32_t compare;
    uint32_t aniso;
    uint32_t border;
    uint32_t flags;
    uint32_t reserved;
} R4AmdImageView;
_Static_assert(sizeof(R4AmdImageView) == 96u, "R4AmdImageView size mismatch");
_Static_assert(offsetof(R4AmdImageView, version) == 0u, "R4AmdImageView.version offset mismatch");
_Static_assert(offsetof(R4AmdImageView, size) == 4u, "R4AmdImageView.size offset mismatch");
_Static_assert(offsetof(R4AmdImageView, address) == 8u, "R4AmdImageView.address offset mismatch");
_Static_assert(offsetof(R4AmdImageView, byte_length) == 16u, "R4AmdImageView.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdImageView, offset) == 24u, "R4AmdImageView.offset offset mismatch");
_Static_assert(offsetof(R4AmdImageView, first_layer) == 32u, "R4AmdImageView.first_layer offset mismatch");
_Static_assert(offsetof(R4AmdImageView, last_layer) == 36u, "R4AmdImageView.last_layer offset mismatch");
_Static_assert(offsetof(R4AmdImageView, first_mip) == 40u, "R4AmdImageView.first_mip offset mismatch");
_Static_assert(offsetof(R4AmdImageView, last_mip) == 44u, "R4AmdImageView.last_mip offset mismatch");
_Static_assert(offsetof(R4AmdImageView, sampler) == 48u, "R4AmdImageView.sampler offset mismatch");
_Static_assert(offsetof(R4AmdImageView, min_lod) == 52u, "R4AmdImageView.min_lod offset mismatch");
_Static_assert(offsetof(R4AmdImageView, max_lod) == 56u, "R4AmdImageView.max_lod offset mismatch");
_Static_assert(offsetof(R4AmdImageView, lod_bias) == 60u, "R4AmdImageView.lod_bias offset mismatch");
_Static_assert(offsetof(R4AmdImageView, wrap_u) == 64u, "R4AmdImageView.wrap_u offset mismatch");
_Static_assert(offsetof(R4AmdImageView, wrap_v) == 68u, "R4AmdImageView.wrap_v offset mismatch");
_Static_assert(offsetof(R4AmdImageView, wrap_w) == 72u, "R4AmdImageView.wrap_w offset mismatch");
_Static_assert(offsetof(R4AmdImageView, compare) == 76u, "R4AmdImageView.compare offset mismatch");
_Static_assert(offsetof(R4AmdImageView, aniso) == 80u, "R4AmdImageView.aniso offset mismatch");
_Static_assert(offsetof(R4AmdImageView, border) == 84u, "R4AmdImageView.border offset mismatch");
_Static_assert(offsetof(R4AmdImageView, flags) == 88u, "R4AmdImageView.flags offset mismatch");
_Static_assert(offsetof(R4AmdImageView, reserved) == 92u, "R4AmdImageView.reserved offset mismatch");

typedef struct R4AmdImageDescriptors {
    uint32_t version;
    uint32_t size;
    uint32_t texture0;
    uint32_t texture1;
    uint32_t texture2;
    uint32_t texture3;
    uint32_t texture4;
    uint32_t texture5;
    uint32_t texture6;
    uint32_t texture7;
    uint32_t sampler0;
    uint32_t sampler1;
    uint32_t sampler2;
    uint32_t sampler3;
    uint32_t color0;
    uint32_t color1;
    uint32_t color2;
    uint32_t color3;
    uint32_t color4;
    uint32_t color5;
    uint32_t color6;
    uint32_t color7;
    uint32_t color8;
    uint32_t color9;
    uint32_t color10;
    uint32_t color11;
    uint32_t color12;
    uint32_t color13;
    uint32_t color14;
    uint32_t color15;
} R4AmdImageDescriptors;
_Static_assert(sizeof(R4AmdImageDescriptors) == 120u, "R4AmdImageDescriptors size mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, version) == 0u, "R4AmdImageDescriptors.version offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, size) == 4u, "R4AmdImageDescriptors.size offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture0) == 8u, "R4AmdImageDescriptors.texture0 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture1) == 12u, "R4AmdImageDescriptors.texture1 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture2) == 16u, "R4AmdImageDescriptors.texture2 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture3) == 20u, "R4AmdImageDescriptors.texture3 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture4) == 24u, "R4AmdImageDescriptors.texture4 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture5) == 28u, "R4AmdImageDescriptors.texture5 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture6) == 32u, "R4AmdImageDescriptors.texture6 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, texture7) == 36u, "R4AmdImageDescriptors.texture7 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, sampler0) == 40u, "R4AmdImageDescriptors.sampler0 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, sampler1) == 44u, "R4AmdImageDescriptors.sampler1 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, sampler2) == 48u, "R4AmdImageDescriptors.sampler2 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, sampler3) == 52u, "R4AmdImageDescriptors.sampler3 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color0) == 56u, "R4AmdImageDescriptors.color0 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color1) == 60u, "R4AmdImageDescriptors.color1 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color2) == 64u, "R4AmdImageDescriptors.color2 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color3) == 68u, "R4AmdImageDescriptors.color3 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color4) == 72u, "R4AmdImageDescriptors.color4 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color5) == 76u, "R4AmdImageDescriptors.color5 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color6) == 80u, "R4AmdImageDescriptors.color6 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color7) == 84u, "R4AmdImageDescriptors.color7 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color8) == 88u, "R4AmdImageDescriptors.color8 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color9) == 92u, "R4AmdImageDescriptors.color9 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color10) == 96u, "R4AmdImageDescriptors.color10 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color11) == 100u, "R4AmdImageDescriptors.color11 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color12) == 104u, "R4AmdImageDescriptors.color12 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color13) == 108u, "R4AmdImageDescriptors.color13 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color14) == 112u, "R4AmdImageDescriptors.color14 offset mismatch");
_Static_assert(offsetof(R4AmdImageDescriptors, color15) == 116u, "R4AmdImageDescriptors.color15 offset mismatch");

typedef struct R4AmdArchitecture {
    uint32_t version;
    uint32_t size;
    uint32_t vendor_id;
    uint32_t device_id;
    uint32_t gc_version;
    uint32_t sdma_version;
    uint32_t gb_addr_config;
    uint32_t chip_revision;
    uint64_t bind_alignment;
    uint64_t memory_generation;
    uint32_t flags;
    uint32_t reserved;
    uint64_t max_image_bytes;
} R4AmdArchitecture;
_Static_assert(sizeof(R4AmdArchitecture) == 64u, "R4AmdArchitecture size mismatch");
_Static_assert(offsetof(R4AmdArchitecture, version) == 0u, "R4AmdArchitecture.version offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, size) == 4u, "R4AmdArchitecture.size offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, vendor_id) == 8u, "R4AmdArchitecture.vendor_id offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, device_id) == 12u, "R4AmdArchitecture.device_id offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, gc_version) == 16u, "R4AmdArchitecture.gc_version offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, sdma_version) == 20u, "R4AmdArchitecture.sdma_version offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, gb_addr_config) == 24u, "R4AmdArchitecture.gb_addr_config offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, chip_revision) == 28u, "R4AmdArchitecture.chip_revision offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, bind_alignment) == 32u, "R4AmdArchitecture.bind_alignment offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, memory_generation) == 40u, "R4AmdArchitecture.memory_generation offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, flags) == 48u, "R4AmdArchitecture.flags offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, reserved) == 52u, "R4AmdArchitecture.reserved offset mismatch");
_Static_assert(offsetof(R4AmdArchitecture, max_image_bytes) == 56u, "R4AmdArchitecture.max_image_bytes offset mismatch");

typedef struct R4AmdShader {
    uint32_t version;
    uint32_t size;
    uint32_t stage;
    uint32_t resource_abi;
    uint64_t code_address;
    uint32_t code_bytes;
    uint32_t exec_bytes;
    uint32_t sgprs;
    uint32_t vgprs;
    uint32_t float_mode;
    uint32_t user_sgprs;
    uint32_t input_vgprs;
    uint32_t spi_ps_input_ena;
    uint32_t spi_ps_input_addr;
    uint32_t reserved;
} R4AmdShader;
_Static_assert(sizeof(R4AmdShader) == 64u, "R4AmdShader size mismatch");
_Static_assert(offsetof(R4AmdShader, version) == 0u, "R4AmdShader.version offset mismatch");
_Static_assert(offsetof(R4AmdShader, size) == 4u, "R4AmdShader.size offset mismatch");
_Static_assert(offsetof(R4AmdShader, stage) == 8u, "R4AmdShader.stage offset mismatch");
_Static_assert(offsetof(R4AmdShader, resource_abi) == 12u, "R4AmdShader.resource_abi offset mismatch");
_Static_assert(offsetof(R4AmdShader, code_address) == 16u, "R4AmdShader.code_address offset mismatch");
_Static_assert(offsetof(R4AmdShader, code_bytes) == 24u, "R4AmdShader.code_bytes offset mismatch");
_Static_assert(offsetof(R4AmdShader, exec_bytes) == 28u, "R4AmdShader.exec_bytes offset mismatch");
_Static_assert(offsetof(R4AmdShader, sgprs) == 32u, "R4AmdShader.sgprs offset mismatch");
_Static_assert(offsetof(R4AmdShader, vgprs) == 36u, "R4AmdShader.vgprs offset mismatch");
_Static_assert(offsetof(R4AmdShader, float_mode) == 40u, "R4AmdShader.float_mode offset mismatch");
_Static_assert(offsetof(R4AmdShader, user_sgprs) == 44u, "R4AmdShader.user_sgprs offset mismatch");
_Static_assert(offsetof(R4AmdShader, input_vgprs) == 48u, "R4AmdShader.input_vgprs offset mismatch");
_Static_assert(offsetof(R4AmdShader, spi_ps_input_ena) == 52u, "R4AmdShader.spi_ps_input_ena offset mismatch");
_Static_assert(offsetof(R4AmdShader, spi_ps_input_addr) == 56u, "R4AmdShader.spi_ps_input_addr offset mismatch");
_Static_assert(offsetof(R4AmdShader, reserved) == 60u, "R4AmdShader.reserved offset mismatch");

typedef struct R4AmdPipeline {
    uint32_t version;
    uint32_t size;
    uint32_t blend_enable;
    uint32_t src_rgb;
    uint32_t dst_rgb;
    uint32_t rgb_func;
    uint32_t src_alpha;
    uint32_t dst_alpha;
    uint32_t alpha_func;
    uint32_t write_mask;
    uint32_t rop;
    uint32_t blend_r;
    uint32_t blend_g;
    uint32_t blend_b;
    uint32_t blend_a;
    uint32_t cull;
    uint32_t front_face;
    uint32_t polygon;
    uint32_t primitive;
    uint32_t depth_test;
    uint32_t depth_write;
    uint32_t depth_compare;
    uint32_t depth_clip;
    uint32_t depth_bounds;
    uint32_t depth_min;
    uint32_t depth_max;
    uint32_t stencil_test;
    uint32_t stencil_compare;
    uint32_t stencil_fail;
    uint32_t stencil_pass;
    uint32_t stencil_depth_fail;
    uint32_t stencil_read_mask;
    uint32_t stencil_write_mask;
    uint32_t stencil_ref;
    uint32_t back_compare;
    uint32_t back_fail;
    uint32_t back_pass;
    uint32_t back_depth_fail;
    uint32_t back_read_mask;
    uint32_t back_write_mask;
    uint32_t back_ref;
    uint32_t line_width;
    uint32_t gb_addr_config;
    uint32_t reserved1;
} R4AmdPipeline;
_Static_assert(sizeof(R4AmdPipeline) == 176u, "R4AmdPipeline size mismatch");
_Static_assert(offsetof(R4AmdPipeline, version) == 0u, "R4AmdPipeline.version offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, size) == 4u, "R4AmdPipeline.size offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, blend_enable) == 8u, "R4AmdPipeline.blend_enable offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, src_rgb) == 12u, "R4AmdPipeline.src_rgb offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, dst_rgb) == 16u, "R4AmdPipeline.dst_rgb offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, rgb_func) == 20u, "R4AmdPipeline.rgb_func offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, src_alpha) == 24u, "R4AmdPipeline.src_alpha offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, dst_alpha) == 28u, "R4AmdPipeline.dst_alpha offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, alpha_func) == 32u, "R4AmdPipeline.alpha_func offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, write_mask) == 36u, "R4AmdPipeline.write_mask offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, rop) == 40u, "R4AmdPipeline.rop offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, blend_r) == 44u, "R4AmdPipeline.blend_r offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, blend_g) == 48u, "R4AmdPipeline.blend_g offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, blend_b) == 52u, "R4AmdPipeline.blend_b offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, blend_a) == 56u, "R4AmdPipeline.blend_a offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, cull) == 60u, "R4AmdPipeline.cull offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, front_face) == 64u, "R4AmdPipeline.front_face offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, polygon) == 68u, "R4AmdPipeline.polygon offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, primitive) == 72u, "R4AmdPipeline.primitive offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_test) == 76u, "R4AmdPipeline.depth_test offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_write) == 80u, "R4AmdPipeline.depth_write offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_compare) == 84u, "R4AmdPipeline.depth_compare offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_clip) == 88u, "R4AmdPipeline.depth_clip offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_bounds) == 92u, "R4AmdPipeline.depth_bounds offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_min) == 96u, "R4AmdPipeline.depth_min offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, depth_max) == 100u, "R4AmdPipeline.depth_max offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_test) == 104u, "R4AmdPipeline.stencil_test offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_compare) == 108u, "R4AmdPipeline.stencil_compare offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_fail) == 112u, "R4AmdPipeline.stencil_fail offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_pass) == 116u, "R4AmdPipeline.stencil_pass offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_depth_fail) == 120u, "R4AmdPipeline.stencil_depth_fail offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_read_mask) == 124u, "R4AmdPipeline.stencil_read_mask offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_write_mask) == 128u, "R4AmdPipeline.stencil_write_mask offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, stencil_ref) == 132u, "R4AmdPipeline.stencil_ref offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_compare) == 136u, "R4AmdPipeline.back_compare offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_fail) == 140u, "R4AmdPipeline.back_fail offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_pass) == 144u, "R4AmdPipeline.back_pass offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_depth_fail) == 148u, "R4AmdPipeline.back_depth_fail offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_read_mask) == 152u, "R4AmdPipeline.back_read_mask offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_write_mask) == 156u, "R4AmdPipeline.back_write_mask offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, back_ref) == 160u, "R4AmdPipeline.back_ref offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, line_width) == 164u, "R4AmdPipeline.line_width offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, gb_addr_config) == 168u, "R4AmdPipeline.gb_addr_config offset mismatch");
_Static_assert(offsetof(R4AmdPipeline, reserved1) == 172u, "R4AmdPipeline.reserved1 offset mismatch");

typedef struct R4AmdDepth {
    uint32_t version;
    uint32_t size;
    uint64_t depth_address;
    uint64_t depth_bytes;
    uint64_t stencil_address;
    uint64_t stencil_bytes;
    uint32_t width;
    uint32_t height;
    uint32_t depth_format;
    uint32_t depth_swizzle;
    uint32_t depth_epitch;
    uint32_t stencil_swizzle;
    uint32_t stencil_epitch;
    uint32_t reserved;
} R4AmdDepth;
_Static_assert(sizeof(R4AmdDepth) == 72u, "R4AmdDepth size mismatch");
_Static_assert(offsetof(R4AmdDepth, version) == 0u, "R4AmdDepth.version offset mismatch");
_Static_assert(offsetof(R4AmdDepth, size) == 4u, "R4AmdDepth.size offset mismatch");
_Static_assert(offsetof(R4AmdDepth, depth_address) == 8u, "R4AmdDepth.depth_address offset mismatch");
_Static_assert(offsetof(R4AmdDepth, depth_bytes) == 16u, "R4AmdDepth.depth_bytes offset mismatch");
_Static_assert(offsetof(R4AmdDepth, stencil_address) == 24u, "R4AmdDepth.stencil_address offset mismatch");
_Static_assert(offsetof(R4AmdDepth, stencil_bytes) == 32u, "R4AmdDepth.stencil_bytes offset mismatch");
_Static_assert(offsetof(R4AmdDepth, width) == 40u, "R4AmdDepth.width offset mismatch");
_Static_assert(offsetof(R4AmdDepth, height) == 44u, "R4AmdDepth.height offset mismatch");
_Static_assert(offsetof(R4AmdDepth, depth_format) == 48u, "R4AmdDepth.depth_format offset mismatch");
_Static_assert(offsetof(R4AmdDepth, depth_swizzle) == 52u, "R4AmdDepth.depth_swizzle offset mismatch");
_Static_assert(offsetof(R4AmdDepth, depth_epitch) == 56u, "R4AmdDepth.depth_epitch offset mismatch");
_Static_assert(offsetof(R4AmdDepth, stencil_swizzle) == 60u, "R4AmdDepth.stencil_swizzle offset mismatch");
_Static_assert(offsetof(R4AmdDepth, stencil_epitch) == 64u, "R4AmdDepth.stencil_epitch offset mismatch");
_Static_assert(offsetof(R4AmdDepth, reserved) == 68u, "R4AmdDepth.reserved offset mismatch");

typedef struct R4AmdDraw {
    uint32_t version;
    uint32_t size;
    uint64_t descriptors;
    uint64_t push_constants;
    uint64_t index_address;
    uint64_t index_bytes;
    uint32_t count;
    uint32_t instances;
    uint32_t first_instance;
    int32_t base_vertex;
    uint32_t draw_id;
    uint32_t index_type;
    uint32_t first_index;
    uint32_t first_vertex;
    uint32_t viewport_x;
    uint32_t viewport_y;
    uint32_t viewport_width;
    uint32_t viewport_height;
    uint32_t depth_min;
    uint32_t depth_max;
    uint32_t scissor_x;
    uint32_t scissor_y;
    uint32_t scissor_end_x;
    uint32_t scissor_end_y;
    uint32_t reserved0;
    uint32_t reserved1;
} R4AmdDraw;
_Static_assert(sizeof(R4AmdDraw) == 120u, "R4AmdDraw size mismatch");
_Static_assert(offsetof(R4AmdDraw, version) == 0u, "R4AmdDraw.version offset mismatch");
_Static_assert(offsetof(R4AmdDraw, size) == 4u, "R4AmdDraw.size offset mismatch");
_Static_assert(offsetof(R4AmdDraw, descriptors) == 8u, "R4AmdDraw.descriptors offset mismatch");
_Static_assert(offsetof(R4AmdDraw, push_constants) == 16u, "R4AmdDraw.push_constants offset mismatch");
_Static_assert(offsetof(R4AmdDraw, index_address) == 24u, "R4AmdDraw.index_address offset mismatch");
_Static_assert(offsetof(R4AmdDraw, index_bytes) == 32u, "R4AmdDraw.index_bytes offset mismatch");
_Static_assert(offsetof(R4AmdDraw, count) == 40u, "R4AmdDraw.count offset mismatch");
_Static_assert(offsetof(R4AmdDraw, instances) == 44u, "R4AmdDraw.instances offset mismatch");
_Static_assert(offsetof(R4AmdDraw, first_instance) == 48u, "R4AmdDraw.first_instance offset mismatch");
_Static_assert(offsetof(R4AmdDraw, base_vertex) == 52u, "R4AmdDraw.base_vertex offset mismatch");
_Static_assert(offsetof(R4AmdDraw, draw_id) == 56u, "R4AmdDraw.draw_id offset mismatch");
_Static_assert(offsetof(R4AmdDraw, index_type) == 60u, "R4AmdDraw.index_type offset mismatch");
_Static_assert(offsetof(R4AmdDraw, first_index) == 64u, "R4AmdDraw.first_index offset mismatch");
_Static_assert(offsetof(R4AmdDraw, first_vertex) == 68u, "R4AmdDraw.first_vertex offset mismatch");
_Static_assert(offsetof(R4AmdDraw, viewport_x) == 72u, "R4AmdDraw.viewport_x offset mismatch");
_Static_assert(offsetof(R4AmdDraw, viewport_y) == 76u, "R4AmdDraw.viewport_y offset mismatch");
_Static_assert(offsetof(R4AmdDraw, viewport_width) == 80u, "R4AmdDraw.viewport_width offset mismatch");
_Static_assert(offsetof(R4AmdDraw, viewport_height) == 84u, "R4AmdDraw.viewport_height offset mismatch");
_Static_assert(offsetof(R4AmdDraw, depth_min) == 88u, "R4AmdDraw.depth_min offset mismatch");
_Static_assert(offsetof(R4AmdDraw, depth_max) == 92u, "R4AmdDraw.depth_max offset mismatch");
_Static_assert(offsetof(R4AmdDraw, scissor_x) == 96u, "R4AmdDraw.scissor_x offset mismatch");
_Static_assert(offsetof(R4AmdDraw, scissor_y) == 100u, "R4AmdDraw.scissor_y offset mismatch");
_Static_assert(offsetof(R4AmdDraw, scissor_end_x) == 104u, "R4AmdDraw.scissor_end_x offset mismatch");
_Static_assert(offsetof(R4AmdDraw, scissor_end_y) == 108u, "R4AmdDraw.scissor_end_y offset mismatch");
_Static_assert(offsetof(R4AmdDraw, reserved0) == 112u, "R4AmdDraw.reserved0 offset mismatch");
_Static_assert(offsetof(R4AmdDraw, reserved1) == 116u, "R4AmdDraw.reserved1 offset mismatch");

typedef struct R4AmdRect {
    int32_t x;
    int32_t y;
    uint32_t width;
    uint32_t height;
} R4AmdRect;
_Static_assert(sizeof(R4AmdRect) == 16u, "R4AmdRect size mismatch");
_Static_assert(offsetof(R4AmdRect, x) == 0u, "R4AmdRect.x offset mismatch");
_Static_assert(offsetof(R4AmdRect, y) == 4u, "R4AmdRect.y offset mismatch");
_Static_assert(offsetof(R4AmdRect, width) == 8u, "R4AmdRect.width offset mismatch");
_Static_assert(offsetof(R4AmdRect, height) == 12u, "R4AmdRect.height offset mismatch");

typedef struct R4AmdYuvPlane {
    uint32_t binding;
    uint32_t reserved;
    uint64_t offset;
    uint64_t byte_length;
    uint32_t pitch;
    uint32_t reserved1;
} R4AmdYuvPlane;
_Static_assert(sizeof(R4AmdYuvPlane) == 32u, "R4AmdYuvPlane size mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, binding) == 0u, "R4AmdYuvPlane.binding offset mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, reserved) == 4u, "R4AmdYuvPlane.reserved offset mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, offset) == 8u, "R4AmdYuvPlane.offset offset mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, byte_length) == 16u, "R4AmdYuvPlane.byte_length offset mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, pitch) == 24u, "R4AmdYuvPlane.pitch offset mismatch");
_Static_assert(offsetof(R4AmdYuvPlane, reserved1) == 28u, "R4AmdYuvPlane.reserved1 offset mismatch");

typedef struct R4AmdYuvHeader {
    uint32_t version;
    uint32_t size;
    uint32_t kind;
    uint32_t format;
    uint32_t filter;
    uint32_t blend;
    uint32_t opacity;
    uint32_t width;
    uint32_t height;
    uint32_t target_binding;
    uint32_t plane_count;
    uint32_t reserved;
    R4AmdRect source;
    R4AmdRect destination;
    R4AmdRect scissor;
    R4AmdYuvPlane plane0;
    R4AmdYuvPlane plane1;
    R4AmdYuvPlane plane2;
    uint32_t chroma_x;
    uint32_t chroma_y;
} R4AmdYuvHeader;
_Static_assert(sizeof(R4AmdYuvHeader) == 200u, "R4AmdYuvHeader size mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, version) == 0u, "R4AmdYuvHeader.version offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, size) == 4u, "R4AmdYuvHeader.size offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, kind) == 8u, "R4AmdYuvHeader.kind offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, format) == 12u, "R4AmdYuvHeader.format offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, filter) == 16u, "R4AmdYuvHeader.filter offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, blend) == 20u, "R4AmdYuvHeader.blend offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, opacity) == 24u, "R4AmdYuvHeader.opacity offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, width) == 28u, "R4AmdYuvHeader.width offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, height) == 32u, "R4AmdYuvHeader.height offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, target_binding) == 36u, "R4AmdYuvHeader.target_binding offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, plane_count) == 40u, "R4AmdYuvHeader.plane_count offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, reserved) == 44u, "R4AmdYuvHeader.reserved offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, source) == 48u, "R4AmdYuvHeader.source offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, destination) == 64u, "R4AmdYuvHeader.destination offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, scissor) == 80u, "R4AmdYuvHeader.scissor offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, plane0) == 96u, "R4AmdYuvHeader.plane0 offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, plane1) == 128u, "R4AmdYuvHeader.plane1 offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, plane2) == 160u, "R4AmdYuvHeader.plane2 offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, chroma_x) == 192u, "R4AmdYuvHeader.chroma_x offset mismatch");
_Static_assert(offsetof(R4AmdYuvHeader, chroma_y) == 196u, "R4AmdYuvHeader.chroma_y offset mismatch");

#define R4AMD_INFO_VERSION ((uint32_t)1)
#define R4AMD_STATUS_OK ((int32_t)0)
#define R4AMD_PROFILE_VERSION ((uint32_t)1)
#define R4AMD_COMMAND_ABI ((uint32_t)1)
#define R4AMD_VENDOR_ID ((uint32_t)4098)
#define R4AMD_GC_9_1_0 ((uint32_t)590080)
#define R4AMD_SDMA_4_1_0 ((uint32_t)262400)
#define R4AMD_FEATURE_COPY_LINEAR ((uint32_t)1)
#define R4AMD_FEATURE_COPY_ROWS ((uint32_t)2)
#define R4AMD_FEATURE_COPY_LAYOUT ((uint32_t)4)
#define R4AMD_FEATURE_FILL ((uint32_t)8)
#define R4AMD_FEATURE_PM4 ((uint32_t)16)
#define R4AMD_IMAGE_WORKSPACE_BYTES ((uint32_t)65536)
#define R4AMD_IMAGE_MAX_MIPS ((uint32_t)15)
#define R4AMD_IMAGE_USAGE_TEXTURE ((uint32_t)1)
#define R4AMD_IMAGE_USAGE_COLOR ((uint32_t)2)
#define R4AMD_IMAGE_USAGE_STORAGE ((uint32_t)4)
#define R4AMD_IMAGE_USAGE_SCANOUT ((uint32_t)8)
#define R4AMD_IMAGE_USAGE_DEPTH ((uint32_t)16)
#define R4AMD_IMAGE_FLAG_SCANOUT ((uint32_t)1)
#define R4AMD_IMAGE_FLAG_TILED ((uint32_t)2)
#define R4AMD_VIEW_UINT ((uint32_t)1)
#define R4AMD_VIEW_ALPHA ((uint32_t)2)
#define R4AMD_FORMAT_RG8 ((uint32_t)943215175)
#define R4AMD_FORMAT_R16 ((uint32_t)540422482)
#define R4AMD_FORMAT_RG16 ((uint32_t)842224199)
#define R4AMD_RENDER_PIPELINE_WORDS ((uint32_t)384)
#define R4AMD_RENDER_DRAW_WORDS ((uint32_t)80)
#define R4AMD_FORMAT_S8 ((uint32_t)16777219)
#define R4AMD_NATIVE_YUV_COMMAND_KIND ((uint32_t)1)
#define R4AMD_NATIVE_YUV_COMMAND_BYTES ((uint32_t)504)
#define R4AMD_NATIVE_VA_START ((uint64_t)343597383680)
#define R4AMD_NATIVE_VA_END ((uint64_t)345744867328)
#define R4AMD_STATUS_INVALID ((int32_t)-1)
#define R4AMD_STATUS_UNSUPPORTED ((int32_t)-2)
#define R4AMD_STATUS_STALE ((int32_t)-3)
#define R4AMD_STATUS_OOM ((int32_t)-4)
#define R4AMD_STATUS_LIMIT ((int32_t)-5)

#define R4AMD_INFO_V1_EXPORT_NAME "INFO_V1"
#define R4AMD_INFO_V1_ABI_MAJOR 1u
#define R4AMD_INFO_V1_REVISION 1u
#define R4AMD_INFO_V1_INTERFACE_ID_LO 0x414d4431ull
#define R4AMD_INFO_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4AMD_INFO_V1_TABLE_SIZE 40u
#define R4AMD_INFO_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4AMD_INFO_V1_TABLE_SIZE, R4AMD_INFO_V1_ABI_MAJOR, R4AMD_INFO_V1_REVISION, R4AMD_INFO_V1_INTERFACE_ID_LO, R4AMD_INFO_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AmdInfoV1GetInfoFn)(R4AmdInfo * output, uint32_t output_bytes);
typedef struct R4AmdInfoV1 {
    R4LInterfaceHeader header;
    R4AmdInfoV1GetInfoFn get_info;
} R4AmdInfoV1;
_Static_assert(sizeof(R4AmdInfoV1) == 40u, "R4AmdInfoV1 size mismatch");
_Static_assert(offsetof(R4AmdInfoV1, get_info) == 32u, "R4AmdInfoV1.get_info offset mismatch");
typedef struct R4AmdInfoV1Client { const R4LInterfaceHeader *header; } R4AmdInfoV1Client;

static inline int32_t r4amd_info_v1_init(const R4XStartContext *ctx, R4AmdInfoV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4AMD", "INFO_V1");
    const R4LInterfaceExpectation expected = { 0x414d4431ull, 0x52344f53ull, 1u, 1u, 40u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4amd_get_info(R4AmdInfoV1Client *client, R4AmdInfo * output, uint32_t output_bytes) {
    R4AmdInfoV1GetInfoFn function = (R4AmdInfoV1GetInfoFn)r4l_slot_address(client->header, 32u);
    return function(output, output_bytes);
}

#define R4AMD_BACKEND_V1_EXPORT_NAME "BACKEND_V1"
#define R4AMD_BACKEND_V1_ABI_MAJOR 1u
#define R4AMD_BACKEND_V1_REVISION 3u
#define R4AMD_BACKEND_V1_INTERFACE_ID_LO 0x414d4432ull
#define R4AMD_BACKEND_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4AMD_BACKEND_V1_TABLE_SIZE 64u
#define R4AMD_BACKEND_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4AMD_BACKEND_V1_TABLE_SIZE, R4AMD_BACKEND_V1_ABI_MAJOR, R4AMD_BACKEND_V1_REVISION, R4AMD_BACKEND_V1_INTERFACE_ID_LO, R4AMD_BACKEND_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AmdBackendV1NegotiateFn)(const R4AmdDeviceProfile * profile, R4AmdFeatures * output);
typedef int32_t (*R4AmdBackendV1EncodeCopyFn)(const R4AmdCopy * request, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4AmdBackendV1EncodeFillFn)(const R4AmdFill * request, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4AmdBackendV1EncodePm4FrameFn)(const R4AmdPm4Frame * request, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef struct R4AmdBackendV1 {
    R4LInterfaceHeader header;
    R4AmdBackendV1NegotiateFn negotiate;
    R4AmdBackendV1EncodeCopyFn encode_copy;
    R4AmdBackendV1EncodeFillFn encode_fill;
    R4AmdBackendV1EncodePm4FrameFn encode_pm4_frame;
} R4AmdBackendV1;
_Static_assert(sizeof(R4AmdBackendV1) == 64u, "R4AmdBackendV1 size mismatch");
_Static_assert(offsetof(R4AmdBackendV1, negotiate) == 32u, "R4AmdBackendV1.negotiate offset mismatch");
_Static_assert(offsetof(R4AmdBackendV1, encode_copy) == 40u, "R4AmdBackendV1.encode_copy offset mismatch");
_Static_assert(offsetof(R4AmdBackendV1, encode_fill) == 48u, "R4AmdBackendV1.encode_fill offset mismatch");
_Static_assert(offsetof(R4AmdBackendV1, encode_pm4_frame) == 56u, "R4AmdBackendV1.encode_pm4_frame offset mismatch");
typedef struct R4AmdBackendV1Client { const R4LInterfaceHeader *header; } R4AmdBackendV1Client;

static inline int32_t r4amd_backend_v1_init(const R4XStartContext *ctx, R4AmdBackendV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4AMD", "BACKEND_V1");
    const R4LInterfaceExpectation expected = { 0x414d4432ull, 0x52344f53ull, 1u, 3u, 64u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4amd_negotiate(R4AmdBackendV1Client *client, const R4AmdDeviceProfile * profile, R4AmdFeatures * output) {
    R4AmdBackendV1NegotiateFn function = (R4AmdBackendV1NegotiateFn)r4l_slot_address(client->header, 32u);
    return function(profile, output);
}

static inline int32_t r4amd_encode_copy(R4AmdBackendV1Client *client, const R4AmdCopy * request, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4AmdBackendV1EncodeCopyFn function = (R4AmdBackendV1EncodeCopyFn)r4l_slot_address(client->header, 40u);
    return function(request, commands, capacity, written);
}

static inline int32_t r4amd_encode_fill(R4AmdBackendV1Client *client, const R4AmdFill * request, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4AmdBackendV1EncodeFillFn function = (R4AmdBackendV1EncodeFillFn)r4l_slot_address(client->header, 48u);
    return function(request, commands, capacity, written);
}

static inline int32_t r4amd_encode_pm4_frame(R4AmdBackendV1Client *client, const R4AmdPm4Frame * request, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4AmdBackendV1EncodePm4FrameFn function = (R4AmdBackendV1EncodePm4FrameFn)r4l_slot_address(client->header, 56u);
    return function(request, commands, capacity, written);
}

#define R4AMD_IMAGE_V1_EXPORT_NAME "IMAGE_V1"
#define R4AMD_IMAGE_V1_ABI_MAJOR 1u
#define R4AMD_IMAGE_V1_REVISION 1u
#define R4AMD_IMAGE_V1_INTERFACE_ID_LO 0x414d4433ull
#define R4AMD_IMAGE_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4AMD_IMAGE_V1_TABLE_SIZE 72u
#define R4AMD_IMAGE_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4AMD_IMAGE_V1_TABLE_SIZE, R4AMD_IMAGE_V1_ABI_MAJOR, R4AMD_IMAGE_V1_REVISION, R4AMD_IMAGE_V1_INTERFACE_ID_LO, R4AMD_IMAGE_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AmdImageV1CalculateFn)(const R4AmdImageRequest * request, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageLayout * output, R4AmdMip * mips, uint32_t mip_capacity);
typedef int32_t (*R4AmdImageV1AddressFn)(const R4AmdImageRequest * request, const R4AmdCoordinate * coordinate, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageAddress * output);
typedef int32_t (*R4AmdImageV1MetadataFn)(const R4AmdImageRequest * request, uint8_t * workspace, uint32_t workspace_bytes, R4AmdMetadata * output);
typedef int32_t (*R4AmdImageV1ImportImageFn)(const R4AmdImageRequest * request, const R4AmdImageImport * imported, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageLayout * output, R4AmdMip * mips, uint32_t mip_capacity);
typedef int32_t (*R4AmdImageV1DescriptorsFn)(const R4AmdImageRequest * request, const R4AmdImageView * view, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageDescriptors * output);
typedef struct R4AmdImageV1 {
    R4LInterfaceHeader header;
    R4AmdImageV1CalculateFn calculate;
    R4AmdImageV1AddressFn address;
    R4AmdImageV1MetadataFn metadata;
    R4AmdImageV1ImportImageFn import_image;
    R4AmdImageV1DescriptorsFn descriptors;
} R4AmdImageV1;
_Static_assert(sizeof(R4AmdImageV1) == 72u, "R4AmdImageV1 size mismatch");
_Static_assert(offsetof(R4AmdImageV1, calculate) == 32u, "R4AmdImageV1.calculate offset mismatch");
_Static_assert(offsetof(R4AmdImageV1, address) == 40u, "R4AmdImageV1.address offset mismatch");
_Static_assert(offsetof(R4AmdImageV1, metadata) == 48u, "R4AmdImageV1.metadata offset mismatch");
_Static_assert(offsetof(R4AmdImageV1, import_image) == 56u, "R4AmdImageV1.import_image offset mismatch");
_Static_assert(offsetof(R4AmdImageV1, descriptors) == 64u, "R4AmdImageV1.descriptors offset mismatch");
typedef struct R4AmdImageV1Client { const R4LInterfaceHeader *header; } R4AmdImageV1Client;

static inline int32_t r4amd_image_v1_init(const R4XStartContext *ctx, R4AmdImageV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4AMD", "IMAGE_V1");
    const R4LInterfaceExpectation expected = { 0x414d4433ull, 0x52344f53ull, 1u, 1u, 72u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4amd_image_calculate(R4AmdImageV1Client *client, const R4AmdImageRequest * request, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageLayout * output, R4AmdMip * mips, uint32_t mip_capacity) {
    R4AmdImageV1CalculateFn function = (R4AmdImageV1CalculateFn)r4l_slot_address(client->header, 32u);
    return function(request, workspace, workspace_bytes, output, mips, mip_capacity);
}

static inline int32_t r4amd_image_address(R4AmdImageV1Client *client, const R4AmdImageRequest * request, const R4AmdCoordinate * coordinate, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageAddress * output) {
    R4AmdImageV1AddressFn function = (R4AmdImageV1AddressFn)r4l_slot_address(client->header, 40u);
    return function(request, coordinate, workspace, workspace_bytes, output);
}

static inline int32_t r4amd_image_metadata(R4AmdImageV1Client *client, const R4AmdImageRequest * request, uint8_t * workspace, uint32_t workspace_bytes, R4AmdMetadata * output) {
    R4AmdImageV1MetadataFn function = (R4AmdImageV1MetadataFn)r4l_slot_address(client->header, 48u);
    return function(request, workspace, workspace_bytes, output);
}

static inline int32_t r4amd_image_import_image(R4AmdImageV1Client *client, const R4AmdImageRequest * request, const R4AmdImageImport * imported, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageLayout * output, R4AmdMip * mips, uint32_t mip_capacity) {
    R4AmdImageV1ImportImageFn function = (R4AmdImageV1ImportImageFn)r4l_slot_address(client->header, 56u);
    return function(request, imported, workspace, workspace_bytes, output, mips, mip_capacity);
}

static inline int32_t r4amd_image_descriptors(R4AmdImageV1Client *client, const R4AmdImageRequest * request, const R4AmdImageView * view, uint8_t * workspace, uint32_t workspace_bytes, R4AmdImageDescriptors * output) {
    R4AmdImageV1DescriptorsFn function = (R4AmdImageV1DescriptorsFn)r4l_slot_address(client->header, 64u);
    return function(request, view, workspace, workspace_bytes, output);
}

#define R4AMD_RENDER_V1_EXPORT_NAME "RENDER_V1"
#define R4AMD_RENDER_V1_ABI_MAJOR 1u
#define R4AMD_RENDER_V1_REVISION 1u
#define R4AMD_RENDER_V1_INTERFACE_ID_LO 0x414d4434ull
#define R4AMD_RENDER_V1_INTERFACE_ID_HI 0x52344f53ull
#define R4AMD_RENDER_V1_TABLE_SIZE 56u
#define R4AMD_RENDER_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4AMD_RENDER_V1_TABLE_SIZE, R4AMD_RENDER_V1_ABI_MAJOR, R4AMD_RENDER_V1_REVISION, R4AMD_RENDER_V1_INTERFACE_ID_LO, R4AMD_RENDER_V1_INTERFACE_ID_HI }
typedef int32_t (*R4AmdRenderV1ShaderFn)(uint32_t profile, uint8_t * code, uint32_t capacity, R4AmdShader * output);
typedef int32_t (*R4AmdRenderV1EncodePipelineFn)(const R4AmdShader * vertex, const R4AmdShader * fragment, const R4AmdPipeline * pipeline, const R4AmdImageDescriptors * color, const R4AmdDepth * depth, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef int32_t (*R4AmdRenderV1EncodeDrawFn)(const R4AmdDraw * draw, uint32_t * commands, uint32_t capacity, uint32_t * written);
typedef struct R4AmdRenderV1 {
    R4LInterfaceHeader header;
    R4AmdRenderV1ShaderFn shader;
    R4AmdRenderV1EncodePipelineFn encode_pipeline;
    R4AmdRenderV1EncodeDrawFn encode_draw;
} R4AmdRenderV1;
_Static_assert(sizeof(R4AmdRenderV1) == 56u, "R4AmdRenderV1 size mismatch");
_Static_assert(offsetof(R4AmdRenderV1, shader) == 32u, "R4AmdRenderV1.shader offset mismatch");
_Static_assert(offsetof(R4AmdRenderV1, encode_pipeline) == 40u, "R4AmdRenderV1.encode_pipeline offset mismatch");
_Static_assert(offsetof(R4AmdRenderV1, encode_draw) == 48u, "R4AmdRenderV1.encode_draw offset mismatch");
typedef struct R4AmdRenderV1Client { const R4LInterfaceHeader *header; } R4AmdRenderV1Client;

static inline int32_t r4amd_render_v1_init(const R4XStartContext *ctx, R4AmdRenderV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4AMD", "RENDER_V1");
    const R4LInterfaceExpectation expected = { 0x414d4434ull, 0x52344f53ull, 1u, 1u, 56u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4amd_shader(R4AmdRenderV1Client *client, uint32_t profile, uint8_t * code, uint32_t capacity, R4AmdShader * output) {
    R4AmdRenderV1ShaderFn function = (R4AmdRenderV1ShaderFn)r4l_slot_address(client->header, 32u);
    return function(profile, code, capacity, output);
}

static inline int32_t r4amd_encode_pipeline(R4AmdRenderV1Client *client, const R4AmdShader * vertex, const R4AmdShader * fragment, const R4AmdPipeline * pipeline, const R4AmdImageDescriptors * color, const R4AmdDepth * depth, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4AmdRenderV1EncodePipelineFn function = (R4AmdRenderV1EncodePipelineFn)r4l_slot_address(client->header, 40u);
    return function(vertex, fragment, pipeline, color, depth, commands, capacity, written);
}

static inline int32_t r4amd_encode_draw(R4AmdRenderV1Client *client, const R4AmdDraw * draw, uint32_t * commands, uint32_t capacity, uint32_t * written) {
    R4AmdRenderV1EncodeDrawFn function = (R4AmdRenderV1EncodeDrawFn)r4l_slot_address(client->header, 48u);
    return function(draw, commands, capacity, written);
}

#endif
