// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4GFX";

pub const R4GfxLinearLayout = extern struct {
    byte_length: u64,
    pitch: u64,
    width: u32,
    height: u32,
    format: u32,
    reserved: u32,
};

pub const R4GfxCpuImage = extern struct {
    cpu_address: u64,
    byte_length: u64,
    pitch: u64,
    width: u32,
    height: u32,
    format: u32,
    reserved: u32,
};

pub const R4GfxRect = extern struct {
    x: u32,
    y: u32,
    width: u32,
    height: u32,
};
pub const status_ok: i32 = 0;
pub const format_xrgb8888: u32 = 875713112;
pub const format_argb8888: u32 = 875713089;
pub const format_r8: u32 = 538982482;
pub const status_invalid: i32 = -1;
pub const status_unsupported: i32 = -2;
pub const status_overflow: i32 = -3;

pub const api_v1_export_name = "API_V1";
pub const api_v1_revision: u16 = 1;
pub const api_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 48,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x34584647,
    .interface_id_hi = 0x35393730,
};
pub const ApiV1LinearLayoutFn = *const fn (width: u32, height: u32, format: u32, row_alignment: u64, output: *R4GfxLinearLayout) callconv(.c) i32;
pub const ApiV1FillRectFn = *const fn (image: *const R4GfxCpuImage, rect: *const R4GfxRect, color: u32) callconv(.c) i32;
pub const ApiV1 = extern struct {
    header: InterfaceHeader,
    linear_layout: ApiV1LinearLayoutFn,
    fill_rect: ApiV1FillRectFn,
};

pub const ApiV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !ApiV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, api_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x34584647,
            .interface_id_hi = 0x35393730,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 48,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn linear_layout(self: *const ApiV1Client, width: u32, height: u32, format: u32, row_alignment: u64, output: *R4GfxLinearLayout) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1LinearLayoutFn, self.header, 32) orelse unreachable;
        return function(width, height, format, row_alignment, output);
    }

    pub fn fill_rect(self: *const ApiV1Client, image: *const R4GfxCpuImage, rect: *const R4GfxRect, color: u32) i32 {
        const function = r4os.runtime_r4l.functionAt(ApiV1FillRectFn, self.header, 40) orelse unreachable;
        return function(image, rect, color);
    }
};
