/* Generated by R4LContractGen. Do not edit. */
#ifndef R4IMG_R4L_BINDING_H
#define R4IMG_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4ImgInfo {
    uint32_t format;
    uint32_t width;
    uint32_t height;
    uint32_t channels;
} R4ImgInfo;
_Static_assert(sizeof(R4ImgInfo) == 16u, "R4ImgInfo size mismatch");
_Static_assert(offsetof(R4ImgInfo, format) == 0u, "R4ImgInfo.format offset mismatch");
_Static_assert(offsetof(R4ImgInfo, width) == 4u, "R4ImgInfo.width offset mismatch");
_Static_assert(offsetof(R4ImgInfo, height) == 8u, "R4ImgInfo.height offset mismatch");
_Static_assert(offsetof(R4ImgInfo, channels) == 12u, "R4ImgInfo.channels offset mismatch");

typedef struct R4ImgSvgOptions {
    uint32_t flags;
    uint32_t background;
    uint64_t glyph_context;
    uint64_t glyph_row;
    uint64_t link_context;
    uint64_t link_record;
    uint16_t glyph_width;
    uint16_t glyph_height;
    uint16_t glyph_advance;
    int16_t glyph_baseline;
    uint64_t reserved;
} R4ImgSvgOptions;
_Static_assert(sizeof(R4ImgSvgOptions) == 56u, "R4ImgSvgOptions size mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, flags) == 0u, "R4ImgSvgOptions.flags offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, background) == 4u, "R4ImgSvgOptions.background offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_context) == 8u, "R4ImgSvgOptions.glyph_context offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_row) == 16u, "R4ImgSvgOptions.glyph_row offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, link_context) == 24u, "R4ImgSvgOptions.link_context offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, link_record) == 32u, "R4ImgSvgOptions.link_record offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_width) == 40u, "R4ImgSvgOptions.glyph_width offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_height) == 42u, "R4ImgSvgOptions.glyph_height offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_advance) == 44u, "R4ImgSvgOptions.glyph_advance offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, glyph_baseline) == 46u, "R4ImgSvgOptions.glyph_baseline offset mismatch");
_Static_assert(offsetof(R4ImgSvgOptions, reserved) == 48u, "R4ImgSvgOptions.reserved offset mismatch");

typedef struct R4ImgDecoderDiagnostic {
    uint64_t scratch_peak;
    uint32_t allocation_failed;
    uint32_t reserved;
} R4ImgDecoderDiagnostic;
_Static_assert(sizeof(R4ImgDecoderDiagnostic) == 16u, "R4ImgDecoderDiagnostic size mismatch");
_Static_assert(offsetof(R4ImgDecoderDiagnostic, scratch_peak) == 0u, "R4ImgDecoderDiagnostic.scratch_peak offset mismatch");
_Static_assert(offsetof(R4ImgDecoderDiagnostic, allocation_failed) == 8u, "R4ImgDecoderDiagnostic.allocation_failed offset mismatch");
_Static_assert(offsetof(R4ImgDecoderDiagnostic, reserved) == 12u, "R4ImgDecoderDiagnostic.reserved offset mismatch");

#define R4IMG_STATUS_OK ((int32_t)0)
#define R4IMG_FORMAT_PNG ((uint32_t)0)
#define R4IMG_FORMAT_JPEG ((uint32_t)1)
#define R4IMG_FORMAT_BMP ((uint32_t)2)
#define R4IMG_FORMAT_SVG ((uint32_t)3)
#define R4IMG_SVG_FLAG_GLYPHS ((uint32_t)1)
#define R4IMG_SVG_FLAG_LINKS ((uint32_t)2)
#define R4IMG_SVG_FLAG_BACKGROUND ((uint32_t)4)
#define R4IMG_MAX_DIMENSION ((uint32_t)4096)
#define R4IMG_MAX_PIXELS ((uint64_t)8847360)
#define R4IMG_MAX_SCRATCH_BYTES ((uint64_t)234881024)
#define R4IMG_MAX_SVG_SOURCE_BYTES ((uint64_t)262144)
#define R4IMG_STATUS_EMPTY ((int32_t)-1)
#define R4IMG_STATUS_UNSUPPORTED_FORMAT ((int32_t)-2)
#define R4IMG_STATUS_INVALID_IMAGE ((int32_t)-3)
#define R4IMG_STATUS_INVALID_DIMENSIONS ((int32_t)-4)
#define R4IMG_STATUS_TOO_LARGE ((int32_t)-5)
#define R4IMG_STATUS_PIXEL_BUFFER_TOO_SMALL ((int32_t)-6)
#define R4IMG_STATUS_SCRATCH_BUFFER_TOO_SMALL ((int32_t)-7)
#define R4IMG_STATUS_DECODE_FAILED ((int32_t)-8)
#define R4IMG_STATUS_UNSUPPORTED_FEATURE ((int32_t)-9)
#define R4IMG_STATUS_INVALID_ARGUMENT ((int32_t)-10)

#define R4IMG_API_V1_EXPORT_NAME "API_V1"
#define R4IMG_API_V1_ABI_MAJOR 1u
#define R4IMG_API_V1_REVISION 1u
#define R4IMG_API_V1_INTERFACE_ID_LO 0x5233f7f0fb63b451ull
#define R4IMG_API_V1_INTERFACE_ID_HI 0x315346a3a7ea4152ull
#define R4IMG_API_V1_TABLE_SIZE 80u
#define R4IMG_API_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4IMG_API_V1_TABLE_SIZE, R4IMG_API_V1_ABI_MAJOR, R4IMG_API_V1_REVISION, R4IMG_API_V1_INTERFACE_ID_LO, R4IMG_API_V1_INTERFACE_ID_HI }
typedef int32_t (*R4ImgApiV1ProbeFn)(const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, R4ImgInfo * output);
typedef int32_t (*R4ImgApiV1ScratchBytesFn)(const R4ImgInfo * info, uint64_t encoded_length, uint64_t * output_bytes);
typedef int32_t (*R4ImgApiV1DecodeFn)(const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, uint32_t * pixels, uint64_t pixel_capacity, uint8_t * scratch, uint64_t scratch_length, R4ImgInfo * output_info, uint64_t * output_pixel_count);
typedef int32_t (*R4ImgApiV1DecodeSvgAtFn)(const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, uint32_t * pixels, uint64_t pixel_capacity, uint8_t * scratch, uint64_t scratch_length, uint32_t width, uint32_t height, const R4ImgSvgOptions * options, R4ImgInfo * output_info, uint64_t * output_pixel_count);
typedef int32_t (*R4ImgApiV1ScaleCompositeFn)(const R4ImgInfo * source_info, const uint32_t * source_pixels, uint64_t source_pixel_count, uint32_t * destination, uint64_t destination_capacity, uint32_t width, uint32_t height, uint32_t background, uint64_t * output_pixel_count);
typedef int32_t (*R4ImgApiV1DecoderDiagnosticFn)(R4ImgDecoderDiagnostic * output);
typedef struct R4ImgApiV1 {
    R4LInterfaceHeader header;
    R4ImgApiV1ProbeFn probe;
    R4ImgApiV1ScratchBytesFn scratch_bytes;
    R4ImgApiV1DecodeFn decode;
    R4ImgApiV1DecodeSvgAtFn decode_svg_at;
    R4ImgApiV1ScaleCompositeFn scale_composite;
    R4ImgApiV1DecoderDiagnosticFn decoder_diagnostic;
} R4ImgApiV1;
_Static_assert(sizeof(R4ImgApiV1) == 80u, "R4ImgApiV1 size mismatch");
_Static_assert(offsetof(R4ImgApiV1, probe) == 32u, "R4ImgApiV1.probe offset mismatch");
_Static_assert(offsetof(R4ImgApiV1, scratch_bytes) == 40u, "R4ImgApiV1.scratch_bytes offset mismatch");
_Static_assert(offsetof(R4ImgApiV1, decode) == 48u, "R4ImgApiV1.decode offset mismatch");
_Static_assert(offsetof(R4ImgApiV1, decode_svg_at) == 56u, "R4ImgApiV1.decode_svg_at offset mismatch");
_Static_assert(offsetof(R4ImgApiV1, scale_composite) == 64u, "R4ImgApiV1.scale_composite offset mismatch");
_Static_assert(offsetof(R4ImgApiV1, decoder_diagnostic) == 72u, "R4ImgApiV1.decoder_diagnostic offset mismatch");
typedef struct R4ImgApiV1Client { const R4LInterfaceHeader *header; } R4ImgApiV1Client;

static inline int32_t r4img_api_v1_init(const R4XStartContext *ctx, R4ImgApiV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4IMG", "API_V1");
    const R4LInterfaceExpectation expected = { 0x5233f7f0fb63b451ull, 0x315346a3a7ea4152ull, 1u, 1u, 80u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4img_probe(R4ImgApiV1Client *client, const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, R4ImgInfo * output) {
    R4ImgApiV1ProbeFn function = (R4ImgApiV1ProbeFn)r4l_slot_address(client->header, 32u);
    return function(encoded, encoded_length, content_type, content_type_length, output);
}

static inline int32_t r4img_scratch_bytes(R4ImgApiV1Client *client, const R4ImgInfo * info, uint64_t encoded_length, uint64_t * output_bytes) {
    R4ImgApiV1ScratchBytesFn function = (R4ImgApiV1ScratchBytesFn)r4l_slot_address(client->header, 40u);
    return function(info, encoded_length, output_bytes);
}

static inline int32_t r4img_decode(R4ImgApiV1Client *client, const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, uint32_t * pixels, uint64_t pixel_capacity, uint8_t * scratch, uint64_t scratch_length, R4ImgInfo * output_info, uint64_t * output_pixel_count) {
    R4ImgApiV1DecodeFn function = (R4ImgApiV1DecodeFn)r4l_slot_address(client->header, 48u);
    return function(encoded, encoded_length, content_type, content_type_length, pixels, pixel_capacity, scratch, scratch_length, output_info, output_pixel_count);
}

static inline int32_t r4img_decode_svg_at(R4ImgApiV1Client *client, const uint8_t * encoded, uint64_t encoded_length, const uint8_t * content_type, uint64_t content_type_length, uint32_t * pixels, uint64_t pixel_capacity, uint8_t * scratch, uint64_t scratch_length, uint32_t width, uint32_t height, const R4ImgSvgOptions * options, R4ImgInfo * output_info, uint64_t * output_pixel_count) {
    R4ImgApiV1DecodeSvgAtFn function = (R4ImgApiV1DecodeSvgAtFn)r4l_slot_address(client->header, 56u);
    return function(encoded, encoded_length, content_type, content_type_length, pixels, pixel_capacity, scratch, scratch_length, width, height, options, output_info, output_pixel_count);
}

static inline int32_t r4img_scale_composite(R4ImgApiV1Client *client, const R4ImgInfo * source_info, const uint32_t * source_pixels, uint64_t source_pixel_count, uint32_t * destination, uint64_t destination_capacity, uint32_t width, uint32_t height, uint32_t background, uint64_t * output_pixel_count) {
    R4ImgApiV1ScaleCompositeFn function = (R4ImgApiV1ScaleCompositeFn)r4l_slot_address(client->header, 64u);
    return function(source_info, source_pixels, source_pixel_count, destination, destination_capacity, width, height, background, output_pixel_count);
}

static inline int32_t r4img_decoder_diagnostic(R4ImgApiV1Client *client, R4ImgDecoderDiagnostic * output) {
    R4ImgApiV1DecoderDiagnosticFn function = (R4ImgApiV1DecoderDiagnosticFn)r4l_slot_address(client->header, 72u);
    return function(output);
}

#endif
