// Generated by R4LContractGen. Do not edit.
const r4os = @import("r4os");

pub const InterfaceHeader = r4os.runtime_r4l.InterfaceHeader;

pub const module_name = "R4NV";

pub const R4NvDeviceProfile = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    copy_class: u32,
    rm_release: u32,
    command_abi: u32,
    adapter_id: u32,
    flags: u32,
    device_generation: u64,
    reset_generation: u64,
};

pub const R4NvFeatures = extern struct {
    version: u32,
    size: u32,
    command_abi: u32,
    features: u32,
    copy_class: u32,
    gpu_address_bits: u32,
    max_command_words: u32,
    reserved: u32,
    max_copy_bytes: u64,
    max_rows: u64,
};

pub const R4NvCopy = extern struct {
    version: u32,
    size: u32,
    source: u64,
    target: u64,
    bytes: u64,
    semaphore: u64,
    copy_class: u32,
    rows: u32,
    source_pitch: u32,
    target_pitch: u32,
    point: u32,
    flags: u32,
};

pub const R4NvDriverProfile = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    copy_class: u32,
    rm_release: u32,
    command_abi: u32,
    reserved0: u32,
    reserved1: u32,
};

pub const R4NvCopyBlock = extern struct {
    enabled: u32,
    width: u32,
    height: u32,
    x: u32,
    y: u32,
    log2_gobs: u32,
};

pub const R4NvCopyLayout = extern struct {
    copy: R4NvCopy,
    source_block: R4NvCopyBlock,
    target_block: R4NvCopyBlock,
};

pub const R4NvDigest = extern struct {
    word0: u64,
    word1: u64,
    word2: u64,
    word3: u64,
};

pub const R4NvShaderKey = extern struct {
    version: u32,
    size: u32,
    vendor_id: u32,
    device_id: u32,
    graphics_class: u32,
    shader_model: u32,
    rm_release: u32,
    command_abi: u32,
    shader_abi: u32,
    resource_abi: u32,
    input_format: u32,
    output_format: u32,
    driver_build: u64,
    device_uuid: R4NvDigest,
    pipeline_state: R4NvDigest,
};

pub const R4NvShaderInfo = extern struct {
    version: u32,
    size: u32,
    profile: u32,
    stage: u32,
    shader_model: u32,
    registers: u32,
    code_bytes: u32,
    instructions: u32,
    scratch_bytes: u32,
    stack_bytes: u32,
    header_bytes: u32,
    resource_abi: u32,
    max_warps_per_sm: u32,
    reserved: u32,
    compiler_id: R4NvDigest,
};

pub const R4NvShaderView = extern struct {
    info: R4NvShaderInfo,
    header_address: u64,
    code_address: u64,
};
pub const command_abi: u32 = 1;
pub const rm_release: u32 = 570144;
pub const feature_copy_linear: u32 = 1;
pub const feature_copy_rows: u32 = 2;
pub const max_command_words: u32 = 19;
pub const status_ok: i32 = 0;
pub const feature_copy_layout: u32 = 4;
pub const max_layout_command_words: u32 = 37;
pub const shader_abi: u32 = 1;
pub const shader_resource_abi: u32 = 1;
pub const shader_model_sm86: u32 = 86;
pub const shader_graphics_class_ampere_b: u32 = 51095;
pub const shader_cache_header_bytes: u32 = 384;
pub const shader_cache_max_bytes: u32 = 1152;
pub const shader_profile_rectangle_vertex: u32 = 1;
pub const shader_profile_texture_fragment: u32 = 2;
pub const shader_profile_srgb_decode_fragment: u32 = 3;
pub const shader_profile_srgb_encode_fragment: u32 = 4;
pub const shader_profile_solid_fragment: u32 = 5;
pub const shader_profile_solid_vertex: u32 = 6;
pub const status_invalid: i32 = -1;
pub const status_unsupported: i32 = -2;
pub const status_capacity: i32 = -3;
pub const status_cache_miss: i32 = -4;

pub const backend_v1_export_name = "BACKEND_V1";
pub const backend_v1_revision: u16 = 2;
pub const backend_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 56,
    .abi_major = 1,
    .abi_minor = 2,
    .interface_id_lo = 0x52344e5642454e44,
    .interface_id_hi = 0x52344f5330373931,
};
pub const BackendV1NegotiateFn = *const fn (profile: *const R4NvDeviceProfile, output: *R4NvFeatures) callconv(.c) i32;
pub const BackendV1EncodeCopyFn = *const fn (request: *const R4NvCopy, commands: [*]u32, capacity: u32, written: *u32) callconv(.c) i32;
pub const BackendV1EncodeCopyLayoutFn = *const fn (request: *const R4NvCopyLayout, commands: [*]u32, capacity: u32, written: *u32) callconv(.c) i32;
pub const BackendV1 = extern struct {
    header: InterfaceHeader,
    negotiate: BackendV1NegotiateFn,
    encode_copy: BackendV1EncodeCopyFn,
    encode_copy_layout: BackendV1EncodeCopyLayoutFn,
};

pub const shader_v1_export_name = "SHADER_V1";
pub const shader_v1_revision: u16 = 1;
pub const shader_v1_header = InterfaceHeader{
    .magic = r4os.runtime_r4l.interface_magic,
    .header_version = r4os.runtime_r4l.interface_header_version,
    .flags = 0,
    .size = 56,
    .abi_major = 1,
    .abi_minor = 1,
    .interface_id_lo = 0x52344e5653484452,
    .interface_id_hi = 0x52344f5330373934,
};
pub const ShaderV1ShaderInfoFn = *const fn (profile: u32, output: *R4NvShaderInfo) callconv(.c) i32;
pub const ShaderV1ShaderCacheWriteFn = *const fn (profile: u32, key: *const R4NvShaderKey, bytes: [*]u8, capacity: u32, written: *u32) callconv(.c) i32;
pub const ShaderV1ShaderCacheReadFn = *const fn (key: *const R4NvShaderKey, bytes: [*]const u8, length: u32, output: *R4NvShaderView) callconv(.c) i32;
pub const ShaderV1 = extern struct {
    header: InterfaceHeader,
    shader_info: ShaderV1ShaderInfoFn,
    shader_cache_write: ShaderV1ShaderCacheWriteFn,
    shader_cache_read: ShaderV1ShaderCacheReadFn,
};

pub const BackendV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !BackendV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, backend_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x52344e5642454e44,
            .interface_id_hi = 0x52344f5330373931,
            .abi_major = 1,
            .min_revision = 2,
            .required_size = 56,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn negotiate(self: *const BackendV1Client, profile: *const R4NvDeviceProfile, output: *R4NvFeatures) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1NegotiateFn, self.header, 32) orelse unreachable;
        return function(profile, output);
    }

    pub fn encode_copy(self: *const BackendV1Client, request: *const R4NvCopy, commands: [*]u32, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1EncodeCopyFn, self.header, 40) orelse unreachable;
        return function(request, commands, capacity, written);
    }

    pub fn encode_copy_layout(self: *const BackendV1Client, request: *const R4NvCopyLayout, commands: [*]u32, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(BackendV1EncodeCopyLayoutFn, self.header, 48) orelse unreachable;
        return function(request, commands, capacity, written);
    }
};

pub const ShaderV1Client = struct {
    header: *const InterfaceHeader,

    pub fn init(raw: *const r4os.abi.R4XStartContext) !ShaderV1Client {
        const item = r4os.r4xstart.Context.init(raw).findImportNamed(module_name, shader_v1_export_name) orelse return error.MissingImport;
        const header = try r4os.runtime_r4l.validateImport(item, .{
            .interface_id_lo = 0x52344e5653484452,
            .interface_id_hi = 0x52344f5330373934,
            .abi_major = 1,
            .min_revision = 1,
            .required_size = 56,
            .known_required_flags = 0,
        });
        if (r4os.runtime_r4l.slotAddress(header, 32) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 40) == null) return error.MissingSlot;
        if (r4os.runtime_r4l.slotAddress(header, 48) == null) return error.MissingSlot;
        return .{ .header = header };
    }

    pub fn shader_info(self: *const ShaderV1Client, profile: u32, output: *R4NvShaderInfo) i32 {
        const function = r4os.runtime_r4l.functionAt(ShaderV1ShaderInfoFn, self.header, 32) orelse unreachable;
        return function(profile, output);
    }

    pub fn shader_cache_write(self: *const ShaderV1Client, profile: u32, key: *const R4NvShaderKey, bytes: [*]u8, capacity: u32, written: *u32) i32 {
        const function = r4os.runtime_r4l.functionAt(ShaderV1ShaderCacheWriteFn, self.header, 40) orelse unreachable;
        return function(profile, key, bytes, capacity, written);
    }

    pub fn shader_cache_read(self: *const ShaderV1Client, key: *const R4NvShaderKey, bytes: [*]const u8, length: u32, output: *R4NvShaderView) i32 {
        const function = r4os.runtime_r4l.functionAt(ShaderV1ShaderCacheReadFn, self.header, 48) orelse unreachable;
        return function(key, bytes, length, output);
    }
};
