/* Generated by R4LContractGen. Do not edit. */
#ifndef R4VIDEO_R4L_BINDING_H
#define R4VIDEO_R4L_BINDING_H

#include <stddef.h>
#include <stdint.h>
#include <r4os/r4l.h>

typedef struct R4VideoRuntime {
    uint64_t address;
    uint64_t generation;
} R4VideoRuntime;
_Static_assert(sizeof(R4VideoRuntime) == 16u, "R4VideoRuntime size mismatch");
_Static_assert(offsetof(R4VideoRuntime, address) == 0u, "R4VideoRuntime.address offset mismatch");
_Static_assert(offsetof(R4VideoRuntime, generation) == 8u, "R4VideoRuntime.generation offset mismatch");

typedef struct R4VideoDecoder {
    uint64_t address;
    uint64_t generation;
} R4VideoDecoder;
_Static_assert(sizeof(R4VideoDecoder) == 16u, "R4VideoDecoder size mismatch");
_Static_assert(offsetof(R4VideoDecoder, address) == 0u, "R4VideoDecoder.address offset mismatch");
_Static_assert(offsetof(R4VideoDecoder, generation) == 8u, "R4VideoDecoder.generation offset mismatch");

typedef struct R4VideoStartup {
    uint32_t version;
    uint32_t size;
    uint64_t application;
    uint64_t memory_limit;
    uint32_t max_decoders;
    uint32_t thread_limit;
} R4VideoStartup;
_Static_assert(sizeof(R4VideoStartup) == 32u, "R4VideoStartup size mismatch");
_Static_assert(offsetof(R4VideoStartup, version) == 0u, "R4VideoStartup.version offset mismatch");
_Static_assert(offsetof(R4VideoStartup, size) == 4u, "R4VideoStartup.size offset mismatch");
_Static_assert(offsetof(R4VideoStartup, application) == 8u, "R4VideoStartup.application offset mismatch");
_Static_assert(offsetof(R4VideoStartup, memory_limit) == 16u, "R4VideoStartup.memory_limit offset mismatch");
_Static_assert(offsetof(R4VideoStartup, max_decoders) == 24u, "R4VideoStartup.max_decoders offset mismatch");
_Static_assert(offsetof(R4VideoStartup, thread_limit) == 28u, "R4VideoStartup.thread_limit offset mismatch");

typedef struct R4VideoCapsQuery {
    uint32_t version;
    uint32_t size;
    uint32_t backend;
    uint32_t adapter_id;
    uint32_t codec;
    uint32_t profile;
    uint32_t bit_depth;
    uint32_t chroma;
} R4VideoCapsQuery;
_Static_assert(sizeof(R4VideoCapsQuery) == 32u, "R4VideoCapsQuery size mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, version) == 0u, "R4VideoCapsQuery.version offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, size) == 4u, "R4VideoCapsQuery.size offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, backend) == 8u, "R4VideoCapsQuery.backend offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, adapter_id) == 12u, "R4VideoCapsQuery.adapter_id offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, codec) == 16u, "R4VideoCapsQuery.codec offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, profile) == 20u, "R4VideoCapsQuery.profile offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, bit_depth) == 24u, "R4VideoCapsQuery.bit_depth offset mismatch");
_Static_assert(offsetof(R4VideoCapsQuery, chroma) == 28u, "R4VideoCapsQuery.chroma offset mismatch");

typedef struct R4VideoCaps {
    uint32_t version;
    uint32_t size;
    R4VideoCapsQuery query;
    uint32_t min_width;
    uint32_t min_height;
    uint32_t max_width;
    uint32_t max_height;
    uint32_t max_level;
    uint32_t output_formats;
    uint64_t max_packet_bytes;
    uint32_t max_pending_packets;
    uint32_t max_frame_leases;
    uint64_t device_generation;
    uint64_t reset_generation;
    uint32_t flags;
    uint32_t reserved;
} R4VideoCaps;
_Static_assert(sizeof(R4VideoCaps) == 104u, "R4VideoCaps size mismatch");
_Static_assert(offsetof(R4VideoCaps, version) == 0u, "R4VideoCaps.version offset mismatch");
_Static_assert(offsetof(R4VideoCaps, size) == 4u, "R4VideoCaps.size offset mismatch");
_Static_assert(offsetof(R4VideoCaps, query) == 8u, "R4VideoCaps.query offset mismatch");
_Static_assert(offsetof(R4VideoCaps, min_width) == 40u, "R4VideoCaps.min_width offset mismatch");
_Static_assert(offsetof(R4VideoCaps, min_height) == 44u, "R4VideoCaps.min_height offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_width) == 48u, "R4VideoCaps.max_width offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_height) == 52u, "R4VideoCaps.max_height offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_level) == 56u, "R4VideoCaps.max_level offset mismatch");
_Static_assert(offsetof(R4VideoCaps, output_formats) == 60u, "R4VideoCaps.output_formats offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_packet_bytes) == 64u, "R4VideoCaps.max_packet_bytes offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_pending_packets) == 72u, "R4VideoCaps.max_pending_packets offset mismatch");
_Static_assert(offsetof(R4VideoCaps, max_frame_leases) == 76u, "R4VideoCaps.max_frame_leases offset mismatch");
_Static_assert(offsetof(R4VideoCaps, device_generation) == 80u, "R4VideoCaps.device_generation offset mismatch");
_Static_assert(offsetof(R4VideoCaps, reset_generation) == 88u, "R4VideoCaps.reset_generation offset mismatch");
_Static_assert(offsetof(R4VideoCaps, flags) == 96u, "R4VideoCaps.flags offset mismatch");
_Static_assert(offsetof(R4VideoCaps, reserved) == 100u, "R4VideoCaps.reserved offset mismatch");

typedef struct R4VideoConfig {
    uint32_t version;
    uint32_t size;
    R4VideoCapsQuery query;
    uint64_t memory_limit;
    uint32_t max_width;
    uint32_t max_height;
    uint32_t pending_packets;
    uint32_t frame_leases;
    uint32_t threads;
    uint32_t flags;
} R4VideoConfig;
_Static_assert(sizeof(R4VideoConfig) == 72u, "R4VideoConfig size mismatch");
_Static_assert(offsetof(R4VideoConfig, version) == 0u, "R4VideoConfig.version offset mismatch");
_Static_assert(offsetof(R4VideoConfig, size) == 4u, "R4VideoConfig.size offset mismatch");
_Static_assert(offsetof(R4VideoConfig, query) == 8u, "R4VideoConfig.query offset mismatch");
_Static_assert(offsetof(R4VideoConfig, memory_limit) == 40u, "R4VideoConfig.memory_limit offset mismatch");
_Static_assert(offsetof(R4VideoConfig, max_width) == 48u, "R4VideoConfig.max_width offset mismatch");
_Static_assert(offsetof(R4VideoConfig, max_height) == 52u, "R4VideoConfig.max_height offset mismatch");
_Static_assert(offsetof(R4VideoConfig, pending_packets) == 56u, "R4VideoConfig.pending_packets offset mismatch");
_Static_assert(offsetof(R4VideoConfig, frame_leases) == 60u, "R4VideoConfig.frame_leases offset mismatch");
_Static_assert(offsetof(R4VideoConfig, threads) == 64u, "R4VideoConfig.threads offset mismatch");
_Static_assert(offsetof(R4VideoConfig, flags) == 68u, "R4VideoConfig.flags offset mismatch");

typedef struct R4VideoPacket {
    uint32_t version;
    uint32_t size;
    uint64_t data_address;
    uint64_t data_bytes;
    uint64_t stream_generation;
    uint64_t tag;
    int64_t pts_ns;
    int64_t dts_ns;
    uint64_t duration_ns;
    uint32_t flags;
    uint32_t reserved;
} R4VideoPacket;
_Static_assert(sizeof(R4VideoPacket) == 72u, "R4VideoPacket size mismatch");
_Static_assert(offsetof(R4VideoPacket, version) == 0u, "R4VideoPacket.version offset mismatch");
_Static_assert(offsetof(R4VideoPacket, size) == 4u, "R4VideoPacket.size offset mismatch");
_Static_assert(offsetof(R4VideoPacket, data_address) == 8u, "R4VideoPacket.data_address offset mismatch");
_Static_assert(offsetof(R4VideoPacket, data_bytes) == 16u, "R4VideoPacket.data_bytes offset mismatch");
_Static_assert(offsetof(R4VideoPacket, stream_generation) == 24u, "R4VideoPacket.stream_generation offset mismatch");
_Static_assert(offsetof(R4VideoPacket, tag) == 32u, "R4VideoPacket.tag offset mismatch");
_Static_assert(offsetof(R4VideoPacket, pts_ns) == 40u, "R4VideoPacket.pts_ns offset mismatch");
_Static_assert(offsetof(R4VideoPacket, dts_ns) == 48u, "R4VideoPacket.dts_ns offset mismatch");
_Static_assert(offsetof(R4VideoPacket, duration_ns) == 56u, "R4VideoPacket.duration_ns offset mismatch");
_Static_assert(offsetof(R4VideoPacket, flags) == 64u, "R4VideoPacket.flags offset mismatch");
_Static_assert(offsetof(R4VideoPacket, reserved) == 68u, "R4VideoPacket.reserved offset mismatch");

typedef struct R4VideoBuffer {
    uint32_t id;
    uint32_t reserved0;
    uint64_t generation;
} R4VideoBuffer;
_Static_assert(sizeof(R4VideoBuffer) == 16u, "R4VideoBuffer size mismatch");
_Static_assert(offsetof(R4VideoBuffer, id) == 0u, "R4VideoBuffer.id offset mismatch");
_Static_assert(offsetof(R4VideoBuffer, reserved0) == 4u, "R4VideoBuffer.reserved0 offset mismatch");
_Static_assert(offsetof(R4VideoBuffer, generation) == 8u, "R4VideoBuffer.generation offset mismatch");

typedef struct R4VideoFence {
    uint32_t slot;
    uint32_t adapter_id;
    uint64_t timeline;
    uint64_t point;
    uint64_t device_generation;
    uint64_t reset_generation;
} R4VideoFence;
_Static_assert(sizeof(R4VideoFence) == 40u, "R4VideoFence size mismatch");
_Static_assert(offsetof(R4VideoFence, slot) == 0u, "R4VideoFence.slot offset mismatch");
_Static_assert(offsetof(R4VideoFence, adapter_id) == 4u, "R4VideoFence.adapter_id offset mismatch");
_Static_assert(offsetof(R4VideoFence, timeline) == 8u, "R4VideoFence.timeline offset mismatch");
_Static_assert(offsetof(R4VideoFence, point) == 16u, "R4VideoFence.point offset mismatch");
_Static_assert(offsetof(R4VideoFence, device_generation) == 24u, "R4VideoFence.device_generation offset mismatch");
_Static_assert(offsetof(R4VideoFence, reset_generation) == 32u, "R4VideoFence.reset_generation offset mismatch");

typedef struct R4VideoPlane {
    R4VideoBuffer buffer;
    R4VideoBuffer reference;
    uint64_t offset;
    uint64_t pitch;
    uint64_t row_bytes;
    uint32_t rows;
    uint32_t reserved;
} R4VideoPlane;
_Static_assert(sizeof(R4VideoPlane) == 64u, "R4VideoPlane size mismatch");
_Static_assert(offsetof(R4VideoPlane, buffer) == 0u, "R4VideoPlane.buffer offset mismatch");
_Static_assert(offsetof(R4VideoPlane, reference) == 16u, "R4VideoPlane.reference offset mismatch");
_Static_assert(offsetof(R4VideoPlane, offset) == 32u, "R4VideoPlane.offset offset mismatch");
_Static_assert(offsetof(R4VideoPlane, pitch) == 40u, "R4VideoPlane.pitch offset mismatch");
_Static_assert(offsetof(R4VideoPlane, row_bytes) == 48u, "R4VideoPlane.row_bytes offset mismatch");
_Static_assert(offsetof(R4VideoPlane, rows) == 56u, "R4VideoPlane.rows offset mismatch");
_Static_assert(offsetof(R4VideoPlane, reserved) == 60u, "R4VideoPlane.reserved offset mismatch");

typedef struct R4VideoColor {
    uint32_t version;
    uint32_t size;
    uint32_t primaries;
    uint32_t transfer;
    uint32_t range;
    uint32_t matrix;
    uint32_t chroma_location;
    uint32_t bit_depth;
    uint32_t reference_white;
    uint32_t peak;
    uint32_t black;
    uint32_t flags;
} R4VideoColor;
_Static_assert(sizeof(R4VideoColor) == 48u, "R4VideoColor size mismatch");
_Static_assert(offsetof(R4VideoColor, version) == 0u, "R4VideoColor.version offset mismatch");
_Static_assert(offsetof(R4VideoColor, size) == 4u, "R4VideoColor.size offset mismatch");
_Static_assert(offsetof(R4VideoColor, primaries) == 8u, "R4VideoColor.primaries offset mismatch");
_Static_assert(offsetof(R4VideoColor, transfer) == 12u, "R4VideoColor.transfer offset mismatch");
_Static_assert(offsetof(R4VideoColor, range) == 16u, "R4VideoColor.range offset mismatch");
_Static_assert(offsetof(R4VideoColor, matrix) == 20u, "R4VideoColor.matrix offset mismatch");
_Static_assert(offsetof(R4VideoColor, chroma_location) == 24u, "R4VideoColor.chroma_location offset mismatch");
_Static_assert(offsetof(R4VideoColor, bit_depth) == 28u, "R4VideoColor.bit_depth offset mismatch");
_Static_assert(offsetof(R4VideoColor, reference_white) == 32u, "R4VideoColor.reference_white offset mismatch");
_Static_assert(offsetof(R4VideoColor, peak) == 36u, "R4VideoColor.peak offset mismatch");
_Static_assert(offsetof(R4VideoColor, black) == 40u, "R4VideoColor.black offset mismatch");
_Static_assert(offsetof(R4VideoColor, flags) == 44u, "R4VideoColor.flags offset mismatch");

typedef struct R4VideoLease {
    R4VideoDecoder decoder;
    uint64_t token;
    uint64_t stream_generation;
} R4VideoLease;
_Static_assert(sizeof(R4VideoLease) == 32u, "R4VideoLease size mismatch");
_Static_assert(offsetof(R4VideoLease, decoder) == 0u, "R4VideoLease.decoder offset mismatch");
_Static_assert(offsetof(R4VideoLease, token) == 16u, "R4VideoLease.token offset mismatch");
_Static_assert(offsetof(R4VideoLease, stream_generation) == 24u, "R4VideoLease.stream_generation offset mismatch");

typedef struct R4VideoFrame {
    uint32_t version;
    uint32_t size;
    R4VideoLease lease;
    uint64_t tag;
    int64_t pts_ns;
    int64_t dts_ns;
    uint64_t duration_ns;
    uint32_t coded_width;
    uint32_t coded_height;
    uint32_t crop_x;
    uint32_t crop_y;
    uint32_t crop_width;
    uint32_t crop_height;
    uint32_t sar_num;
    uint32_t sar_den;
    uint32_t format;
    uint32_t plane_count;
    R4VideoColor color;
    R4VideoPlane plane0;
    R4VideoPlane plane1;
    R4VideoPlane plane2;
    R4VideoFence ready;
    uint32_t flags;
    uint32_t reserved;
} R4VideoFrame;
_Static_assert(sizeof(R4VideoFrame) == 400u, "R4VideoFrame size mismatch");
_Static_assert(offsetof(R4VideoFrame, version) == 0u, "R4VideoFrame.version offset mismatch");
_Static_assert(offsetof(R4VideoFrame, size) == 4u, "R4VideoFrame.size offset mismatch");
_Static_assert(offsetof(R4VideoFrame, lease) == 8u, "R4VideoFrame.lease offset mismatch");
_Static_assert(offsetof(R4VideoFrame, tag) == 40u, "R4VideoFrame.tag offset mismatch");
_Static_assert(offsetof(R4VideoFrame, pts_ns) == 48u, "R4VideoFrame.pts_ns offset mismatch");
_Static_assert(offsetof(R4VideoFrame, dts_ns) == 56u, "R4VideoFrame.dts_ns offset mismatch");
_Static_assert(offsetof(R4VideoFrame, duration_ns) == 64u, "R4VideoFrame.duration_ns offset mismatch");
_Static_assert(offsetof(R4VideoFrame, coded_width) == 72u, "R4VideoFrame.coded_width offset mismatch");
_Static_assert(offsetof(R4VideoFrame, coded_height) == 76u, "R4VideoFrame.coded_height offset mismatch");
_Static_assert(offsetof(R4VideoFrame, crop_x) == 80u, "R4VideoFrame.crop_x offset mismatch");
_Static_assert(offsetof(R4VideoFrame, crop_y) == 84u, "R4VideoFrame.crop_y offset mismatch");
_Static_assert(offsetof(R4VideoFrame, crop_width) == 88u, "R4VideoFrame.crop_width offset mismatch");
_Static_assert(offsetof(R4VideoFrame, crop_height) == 92u, "R4VideoFrame.crop_height offset mismatch");
_Static_assert(offsetof(R4VideoFrame, sar_num) == 96u, "R4VideoFrame.sar_num offset mismatch");
_Static_assert(offsetof(R4VideoFrame, sar_den) == 100u, "R4VideoFrame.sar_den offset mismatch");
_Static_assert(offsetof(R4VideoFrame, format) == 104u, "R4VideoFrame.format offset mismatch");
_Static_assert(offsetof(R4VideoFrame, plane_count) == 108u, "R4VideoFrame.plane_count offset mismatch");
_Static_assert(offsetof(R4VideoFrame, color) == 112u, "R4VideoFrame.color offset mismatch");
_Static_assert(offsetof(R4VideoFrame, plane0) == 160u, "R4VideoFrame.plane0 offset mismatch");
_Static_assert(offsetof(R4VideoFrame, plane1) == 224u, "R4VideoFrame.plane1 offset mismatch");
_Static_assert(offsetof(R4VideoFrame, plane2) == 288u, "R4VideoFrame.plane2 offset mismatch");
_Static_assert(offsetof(R4VideoFrame, ready) == 352u, "R4VideoFrame.ready offset mismatch");
_Static_assert(offsetof(R4VideoFrame, flags) == 392u, "R4VideoFrame.flags offset mismatch");
_Static_assert(offsetof(R4VideoFrame, reserved) == 396u, "R4VideoFrame.reserved offset mismatch");

typedef struct R4VideoReceipt {
    uint32_t version;
    uint32_t size;
    R4VideoFence fence;
    int32_t result;
    uint32_t reserved;
} R4VideoReceipt;
_Static_assert(sizeof(R4VideoReceipt) == 56u, "R4VideoReceipt size mismatch");
_Static_assert(offsetof(R4VideoReceipt, version) == 0u, "R4VideoReceipt.version offset mismatch");
_Static_assert(offsetof(R4VideoReceipt, size) == 4u, "R4VideoReceipt.size offset mismatch");
_Static_assert(offsetof(R4VideoReceipt, fence) == 8u, "R4VideoReceipt.fence offset mismatch");
_Static_assert(offsetof(R4VideoReceipt, result) == 48u, "R4VideoReceipt.result offset mismatch");
_Static_assert(offsetof(R4VideoReceipt, reserved) == 52u, "R4VideoReceipt.reserved offset mismatch");

typedef struct R4VideoControl {
    uint32_t version;
    uint32_t size;
    uint64_t request_id;
    uint32_t operation;
    uint32_t reserved;
} R4VideoControl;
_Static_assert(sizeof(R4VideoControl) == 24u, "R4VideoControl size mismatch");
_Static_assert(offsetof(R4VideoControl, version) == 0u, "R4VideoControl.version offset mismatch");
_Static_assert(offsetof(R4VideoControl, size) == 4u, "R4VideoControl.size offset mismatch");
_Static_assert(offsetof(R4VideoControl, request_id) == 8u, "R4VideoControl.request_id offset mismatch");
_Static_assert(offsetof(R4VideoControl, operation) == 16u, "R4VideoControl.operation offset mismatch");
_Static_assert(offsetof(R4VideoControl, reserved) == 20u, "R4VideoControl.reserved offset mismatch");

typedef struct R4VideoState {
    uint32_t version;
    uint32_t size;
    uint64_t stream_generation;
    uint64_t pending_request;
    uint64_t completed_request;
    uint64_t memory_bytes;
    uint32_t phase;
    uint32_t queued_packets;
    uint32_t ready_frames;
    uint32_t leased_frames;
    int32_t last_error;
    uint32_t reserved;
} R4VideoState;
_Static_assert(sizeof(R4VideoState) == 64u, "R4VideoState size mismatch");
_Static_assert(offsetof(R4VideoState, version) == 0u, "R4VideoState.version offset mismatch");
_Static_assert(offsetof(R4VideoState, size) == 4u, "R4VideoState.size offset mismatch");
_Static_assert(offsetof(R4VideoState, stream_generation) == 8u, "R4VideoState.stream_generation offset mismatch");
_Static_assert(offsetof(R4VideoState, pending_request) == 16u, "R4VideoState.pending_request offset mismatch");
_Static_assert(offsetof(R4VideoState, completed_request) == 24u, "R4VideoState.completed_request offset mismatch");
_Static_assert(offsetof(R4VideoState, memory_bytes) == 32u, "R4VideoState.memory_bytes offset mismatch");
_Static_assert(offsetof(R4VideoState, phase) == 40u, "R4VideoState.phase offset mismatch");
_Static_assert(offsetof(R4VideoState, queued_packets) == 44u, "R4VideoState.queued_packets offset mismatch");
_Static_assert(offsetof(R4VideoState, ready_frames) == 48u, "R4VideoState.ready_frames offset mismatch");
_Static_assert(offsetof(R4VideoState, leased_frames) == 52u, "R4VideoState.leased_frames offset mismatch");
_Static_assert(offsetof(R4VideoState, last_error) == 56u, "R4VideoState.last_error offset mismatch");
_Static_assert(offsetof(R4VideoState, reserved) == 60u, "R4VideoState.reserved offset mismatch");

#define R4VIDEO_OK ((int32_t)0)
#define R4VIDEO_AGAIN ((int32_t)1)
#define R4VIDEO_EOS ((int32_t)2)
#define R4VIDEO_BACKEND_SOFTWARE ((uint32_t)0)
#define R4VIDEO_BACKEND_NVIDIA ((uint32_t)1)
#define R4VIDEO_CODEC_H264 ((uint32_t)1)
#define R4VIDEO_PROFILE_DEFAULT ((uint32_t)0)
#define R4VIDEO_PROFILE_H264_BASELINE ((uint32_t)66)
#define R4VIDEO_PROFILE_H264_MAIN ((uint32_t)77)
#define R4VIDEO_PROFILE_H264_HIGH ((uint32_t)100)
#define R4VIDEO_CHROMA_420 ((uint32_t)1)
#define R4VIDEO_FORMAT_NV12 ((uint32_t)1)
#define R4VIDEO_FORMAT_P010 ((uint32_t)2)
#define R4VIDEO_FORMAT_YUV420P ((uint32_t)3)
#define R4VIDEO_FORMATS_NV12 ((uint32_t)1)
#define R4VIDEO_FORMATS_P010 ((uint32_t)2)
#define R4VIDEO_FORMATS_YUV420P ((uint32_t)4)
#define R4VIDEO_MATRIX_UNSPECIFIED ((uint32_t)2)
#define R4VIDEO_MATRIX_BT470BG ((uint32_t)5)
#define R4VIDEO_MATRIX_BT709 ((uint32_t)1)
#define R4VIDEO_MATRIX_BT2020_NCL ((uint32_t)9)
#define R4VIDEO_CHROMA_UNSPECIFIED ((uint32_t)0)
#define R4VIDEO_CHROMA_LEFT ((uint32_t)1)
#define R4VIDEO_CHROMA_CENTER ((uint32_t)2)
#define R4VIDEO_CHROMA_TOP_LEFT ((uint32_t)3)
#define R4VIDEO_PACKET_PTS ((uint32_t)1)
#define R4VIDEO_PACKET_DTS ((uint32_t)2)
#define R4VIDEO_PACKET_DURATION ((uint32_t)4)
#define R4VIDEO_FRAME_KEY ((uint32_t)8)
#define R4VIDEO_PHASE_OPEN ((uint32_t)0)
#define R4VIDEO_PHASE_DRAINING ((uint32_t)1)
#define R4VIDEO_PHASE_DRAINED ((uint32_t)2)
#define R4VIDEO_PHASE_FLUSHING ((uint32_t)3)
#define R4VIDEO_PHASE_CLOSING ((uint32_t)4)
#define R4VIDEO_PHASE_CLOSED ((uint32_t)5)
#define R4VIDEO_PHASE_FAILED ((uint32_t)6)
#define R4VIDEO_CONTROL_QUERY ((uint32_t)0)
#define R4VIDEO_CONTROL_DRAIN ((uint32_t)1)
#define R4VIDEO_CONTROL_FLUSH ((uint32_t)2)
#define R4VIDEO_CONTROL_CLOSE ((uint32_t)3)
#define R4VIDEO_MATRIX_SMPTE170M ((uint32_t)6)
#define R4VIDEO_COLOR_REFERENCE_WHITE ((uint32_t)1)
#define R4VIDEO_COLOR_LUMINANCE ((uint32_t)2)
#define R4VIDEO_COLOR_UNSPECIFIED ((uint32_t)2)
#define R4VIDEO_BACKEND_AMD ((uint32_t)2)
#define R4VIDEO_CODEC_HEVC ((uint32_t)2)
#define R4VIDEO_CODEC_VP9 ((uint32_t)3)
#define R4VIDEO_CODEC_MPEG2 ((uint32_t)4)
#define R4VIDEO_CODEC_VC1 ((uint32_t)5)
#define R4VIDEO_CODEC_JPEG ((uint32_t)6)
#define R4VIDEO_CODEC_AV1 ((uint32_t)7)
#define R4VIDEO_CODEC_MPEG4_PART2 ((uint32_t)8)
#define R4VIDEO_PROFILE_HEVC_MAIN ((uint32_t)1)
#define R4VIDEO_PROFILE_HEVC_MAIN10 ((uint32_t)2)
#define R4VIDEO_PROFILE_VP9_0 ((uint32_t)0)
#define R4VIDEO_PROFILE_VP9_2 ((uint32_t)2)
#define R4VIDEO_PROFILE_MPEG2_SIMPLE ((uint32_t)5)
#define R4VIDEO_PROFILE_MPEG2_MAIN ((uint32_t)4)
#define R4VIDEO_PROFILE_VC1_SIMPLE ((uint32_t)0)
#define R4VIDEO_PROFILE_VC1_MAIN ((uint32_t)1)
#define R4VIDEO_PROFILE_VC1_ADVANCED ((uint32_t)3)
#define R4VIDEO_PROFILE_JPEG_BASELINE ((uint32_t)0)
#define R4VIDEO_ERROR_INVALID ((int32_t)-1)
#define R4VIDEO_ERROR_UNSUPPORTED ((int32_t)-2)
#define R4VIDEO_ERROR_BUSY ((int32_t)-3)
#define R4VIDEO_ERROR_NO_MEMORY ((int32_t)-4)
#define R4VIDEO_ERROR_STALE ((int32_t)-5)
#define R4VIDEO_ERROR_DECODE ((int32_t)-6)
#define R4VIDEO_ERROR_DEVICE_LOST ((int32_t)-7)
#define R4VIDEO_ERROR_CLOSED ((int32_t)-8)
#define R4VIDEO_ERROR_INTERNAL ((int32_t)-9)

#define R4VIDEO_VIDEO_V1_EXPORT_NAME "VIDEO_V1"
#define R4VIDEO_VIDEO_V1_ABI_MAJOR 1u
#define R4VIDEO_VIDEO_V1_REVISION 1u
#define R4VIDEO_VIDEO_V1_INTERFACE_ID_LO 0x314f454449563452ull
#define R4VIDEO_VIDEO_V1_INTERFACE_ID_HI 0x313045444f434544ull
#define R4VIDEO_VIDEO_V1_TABLE_SIZE 104u
#define R4VIDEO_VIDEO_V1_HEADER_INITIALIZER { R4L_INTERFACE_MAGIC, R4L_INTERFACE_HEADER_VERSION, 0u, R4VIDEO_VIDEO_V1_TABLE_SIZE, R4VIDEO_VIDEO_V1_ABI_MAJOR, R4VIDEO_VIDEO_V1_REVISION, R4VIDEO_VIDEO_V1_INTERFACE_ID_LO, R4VIDEO_VIDEO_V1_INTERFACE_ID_HI }
typedef int32_t (*R4VideoV1OpenFn)(const R4VideoStartup * startup, R4VideoRuntime * runtime);
typedef int32_t (*R4VideoV1QueryCapsFn)(const R4VideoRuntime * runtime, const R4VideoCapsQuery * query, R4VideoCaps * output);
typedef int32_t (*R4VideoV1CreateFn)(const R4VideoRuntime * runtime, const R4VideoConfig * config, R4VideoDecoder * decoder);
typedef int32_t (*R4VideoV1SendFn)(const R4VideoDecoder * decoder, const R4VideoPacket * packet);
typedef int32_t (*R4VideoV1ReceiveFn)(const R4VideoDecoder * decoder, R4VideoFrame * frame);
typedef int32_t (*R4VideoV1ReleaseFn)(const R4VideoLease * lease, const R4VideoReceipt * receipt);
typedef int32_t (*R4VideoV1ControlFn)(const R4VideoDecoder * decoder, const R4VideoControl * request, R4VideoState * state);
typedef int32_t (*R4VideoV1DestroyFn)(const R4VideoDecoder * decoder);
typedef int32_t (*R4VideoV1FinishFn)(const R4VideoRuntime * runtime, uint64_t timeout_ns);
typedef struct R4VideoV1 {
    R4LInterfaceHeader header;
    R4VideoV1OpenFn open;
    R4VideoV1QueryCapsFn query_caps;
    R4VideoV1CreateFn create;
    R4VideoV1SendFn send;
    R4VideoV1ReceiveFn receive;
    R4VideoV1ReleaseFn release;
    R4VideoV1ControlFn control;
    R4VideoV1DestroyFn destroy;
    R4VideoV1FinishFn finish;
} R4VideoV1;
_Static_assert(sizeof(R4VideoV1) == 104u, "R4VideoV1 size mismatch");
_Static_assert(offsetof(R4VideoV1, open) == 32u, "R4VideoV1.open offset mismatch");
_Static_assert(offsetof(R4VideoV1, query_caps) == 40u, "R4VideoV1.query_caps offset mismatch");
_Static_assert(offsetof(R4VideoV1, create) == 48u, "R4VideoV1.create offset mismatch");
_Static_assert(offsetof(R4VideoV1, send) == 56u, "R4VideoV1.send offset mismatch");
_Static_assert(offsetof(R4VideoV1, receive) == 64u, "R4VideoV1.receive offset mismatch");
_Static_assert(offsetof(R4VideoV1, release) == 72u, "R4VideoV1.release offset mismatch");
_Static_assert(offsetof(R4VideoV1, control) == 80u, "R4VideoV1.control offset mismatch");
_Static_assert(offsetof(R4VideoV1, destroy) == 88u, "R4VideoV1.destroy offset mismatch");
_Static_assert(offsetof(R4VideoV1, finish) == 96u, "R4VideoV1.finish offset mismatch");
typedef struct R4VideoV1Client { const R4LInterfaceHeader *header; } R4VideoV1Client;

static inline int32_t r4video_video_v1_init(const R4XStartContext *ctx, R4VideoV1Client *out_client) {
    if (out_client == 0) return R4L_BINDING_INVALID_EXPECTATION;
    out_client->header = 0;
    const R4XStartImport *item = r4xstart_find_import_named(ctx, "R4VIDEO", "VIDEO_V1");
    const R4LInterfaceExpectation expected = { 0x314f454449563452ull, 0x313045444f434544ull, 1u, 1u, 104u, 0u, 0u };
    const R4LInterfaceHeader *header = 0;
    int32_t status = r4l_validate_import(item, &expected, &header);
    if (status != R4L_BINDING_OK) return status;
    if (r4l_slot_address(header, 32u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 40u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 48u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 56u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 64u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 72u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 80u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 88u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    if (r4l_slot_address(header, 96u) == 0) return R4L_BINDING_TABLE_TOO_SMALL;
    out_client->header = header;
    return R4L_BINDING_OK;
}

static inline int32_t r4video_open(R4VideoV1Client *client, const R4VideoStartup * startup, R4VideoRuntime * runtime) {
    R4VideoV1OpenFn function = (R4VideoV1OpenFn)r4l_slot_address(client->header, 32u);
    return function(startup, runtime);
}

static inline int32_t r4video_query_caps(R4VideoV1Client *client, const R4VideoRuntime * runtime, const R4VideoCapsQuery * query, R4VideoCaps * output) {
    R4VideoV1QueryCapsFn function = (R4VideoV1QueryCapsFn)r4l_slot_address(client->header, 40u);
    return function(runtime, query, output);
}

static inline int32_t r4video_create(R4VideoV1Client *client, const R4VideoRuntime * runtime, const R4VideoConfig * config, R4VideoDecoder * decoder) {
    R4VideoV1CreateFn function = (R4VideoV1CreateFn)r4l_slot_address(client->header, 48u);
    return function(runtime, config, decoder);
}

static inline int32_t r4video_send(R4VideoV1Client *client, const R4VideoDecoder * decoder, const R4VideoPacket * packet) {
    R4VideoV1SendFn function = (R4VideoV1SendFn)r4l_slot_address(client->header, 56u);
    return function(decoder, packet);
}

static inline int32_t r4video_receive(R4VideoV1Client *client, const R4VideoDecoder * decoder, R4VideoFrame * frame) {
    R4VideoV1ReceiveFn function = (R4VideoV1ReceiveFn)r4l_slot_address(client->header, 64u);
    return function(decoder, frame);
}

static inline int32_t r4video_release(R4VideoV1Client *client, const R4VideoLease * lease, const R4VideoReceipt * receipt) {
    R4VideoV1ReleaseFn function = (R4VideoV1ReleaseFn)r4l_slot_address(client->header, 72u);
    return function(lease, receipt);
}

static inline int32_t r4video_control(R4VideoV1Client *client, const R4VideoDecoder * decoder, const R4VideoControl * request, R4VideoState * state) {
    R4VideoV1ControlFn function = (R4VideoV1ControlFn)r4l_slot_address(client->header, 80u);
    return function(decoder, request, state);
}

static inline int32_t r4video_destroy(R4VideoV1Client *client, const R4VideoDecoder * decoder) {
    R4VideoV1DestroyFn function = (R4VideoV1DestroyFn)r4l_slot_address(client->header, 88u);
    return function(decoder);
}

static inline int32_t r4video_finish(R4VideoV1Client *client, const R4VideoRuntime * runtime, uint64_t timeout_ns) {
    R4VideoV1FinishFn function = (R4VideoV1FinishFn)r4l_slot_address(client->header, 96u);
    return function(runtime, timeout_ns);
}

#endif
