# Copyright 2026 R4. SPDX-License-Identifier: Apache-2.0
# Materialize fixed compiler outputs; this script never runs a compiler.
[CmdletBinding()]
param([string]$CompilerOutputDirectory = '')
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$unit = [IO.Path]::GetFullPath('../..', $PSScriptRoot)
$libraryRoot = [IO.Path]::GetFullPath('..', $unit)
$settings = @{}
foreach ($line in Get-Content -LiteralPath (Join-Path $libraryRoot 'Settings.R4S')) {
    if ($line -match '^([A-Z_]+)=(.+)$') { $settings[$Matches[1]] = $Matches[2] }
}
$root = [IO.Path]::GetFullPath($settings.WORKSPACE_ROOT.Replace('\', '/'), $libraryRoot)
$artifacts = [IO.Path]::GetFullPath($settings.ARTIFACTS_ROOT.Replace('\', '/'), $root)
$source = if ($CompilerOutputDirectory) { [IO.Path]::GetFullPath($CompilerOutputDirectory, $root) }
          else { Join-Path $artifacts ('Tools/R4NAK/' + $(if ($IsWindows) { 'Windows-x64' } else { 'Linux-x64' })) }
$record = Get-Content -LiteralPath (Join-Path $source 'build.json') -Raw | ConvertFrom-Json
$lock = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'Sources.lock.json') -Raw | ConvertFrom-Json
function Hash([string]$Path) { (Get-FileHash -LiteralPath $Path).Hash.ToLowerInvariant() }
$targets=@($lock.targets|Where-Object sm -eq $record.target.sm)
if($targets.Count -ne 1){throw 'Unrecognized shader target'}
$shaderTarget=$targets[0]
if ($record.schema -ne 1 -or !$record.reproducible -or $record.target.max_warps_per_mp -ne $shaderTarget.max_warps_per_mp -or
    $record.profiles.Count -ne $lock.profiles.Count -or $record.compiler_id -notmatch '^[0-9a-f]{64}$') {
    throw 'A complete, reproducibly verified architecture-specific compiler build is required.'
}
foreach ($inputFile in $record.inputs) {
    if ((Hash (Join-Path $PSScriptRoot $inputFile.path)) -ne $inputFile.sha256) { throw "Compiler input changed: $($inputFile.path). Rebuild the compiler outputs." }
}
$programs = @(foreach ($profile in $lock.profiles) {
    $proof = @($record.profiles | Where-Object profile -eq $profile.id)
    if ($proof.Count -ne 1 -or $proof[0].name -cne $profile.name) { throw 'Missing or ambiguous shader profile.' }
    $proof = $proof[0]
    $prefix = Join-Path $source $profile.name
    foreach ($pair in @(@('.bin','sha256'), @('.json','metadata_sha256'), @('.asm.txt','assembly_sha256'), @('.nir.txt','nir_sha256'))) {
        if ((Hash ($prefix+$pair[0])) -cne $proof.($pair[1])) { throw "Shader artifact changed: $($profile.name)$($pair[0])" }
    }
    $info = Get-Content -LiteralPath ($prefix+'.json') -Raw | ConvertFrom-Json
    if ($info.schema -ne 1 -or $info.mesa -cne $lock.mesa.version -or $info.sm -ne $shaderTarget.sm -or $info.max_warps_per_mp -ne $shaderTarget.max_warps_per_mp -or $info.stage -ne $profile.stage -or
        $info.profile -ne $profile.id -or $info.header.Count -ne 32 -or $info.slm_bytes -ne 0 -or $info.crs_bytes -ne 0 -or
        $info.control_barriers -ne 0 -or $info.code_bytes -ne $proof.code_bytes -or $info.code_bytes -eq 0 -or
        $info.code_bytes % 16 -ne 0 -or $info.code_bytes -gt 65536 -or $info.gprs -ne $proof.gprs -or $info.gprs -gt 255 -or
        $info.instructions -ne $proof.instructions -or $info.max_warps_per_sm -lt 1 -or $info.max_warps_per_sm -gt $shaderTarget.max_warps_per_mp) {
        throw "Unsupported fixed-shader metadata: $($profile.name)"
    }
    foreach ($word in $info.header) { if ($word -lt 0 -or $word -gt [uint32]::MaxValue) { throw 'Invalid NVIDIA shader header word.' } }
    [pscustomobject]@{name=$profile.name;info=$info;proof=$proof}
})
# Validate the whole set before replacing generated source files.
$target = Join-Path $unit 'Source/Generated/Shaders'
if($shaderTarget.sm -ne 86){$target=Join-Path $target ('SM'+$shaderTarget.sm)}
[void](New-Item -ItemType Directory -Path $target -Force)
$text = [Text.StringBuilder]::new()
[void]$text.AppendLine('// Generated by Tools/Compiler/EmitRuntime.ps1 from pinned NIR/NAK output. Do not edit.')
[void]$text.AppendLine('// Copyright 2026 R4. SPDX-License-Identifier: Apache-2.0')
$id = [Convert]::FromHexString($record.compiler_id)
[void]$text.AppendLine('pub const compiler_id = [32]u8{ ' + (($id | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ' };')
[void]$text.AppendLine("pub const compiler_abi: u32 = $($lock.compiler_abi);")
[void]$text.AppendLine("pub const resource_abi: u32 = $($lock.graphics_constants_abi);")
[void]$text.AppendLine("pub const sm: u16 = $($shaderTarget.sm);")
[void]$text.AppendLine('pub const Program = struct { profile: u32, stage: u32, gprs: u32, instructions: u32, max_warps_per_sm: u32, header: [32]u32, code: []const u8 };')
[void]$text.AppendLine('pub const programs = [_]Program{')
foreach ($program in $programs) {
    $info = $program.info
    Copy-Item -LiteralPath (Join-Path $source ($program.name+'.bin')) -Destination (Join-Path $target ($program.name+'.bin'))
    [void]$text.AppendLine('    .{ .profile = ' + $info.profile + ', .stage = ' + $info.stage + ', .gprs = ' + $info.gprs +
        ', .instructions = ' + $info.instructions + ', .max_warps_per_sm = ' + $info.max_warps_per_sm +
        ', .header = .{ ' + (($info.header | ForEach-Object { '0x{0:x8}' -f [uint32]$_ }) -join ', ') +
        ' }, .code = @embedFile("' + $program.name + '.bin") },')
}
[void]$text.AppendLine('};')
[IO.File]::WriteAllText((Join-Path $target 'shaders.zig'), $text.ToString().Replace("`r`n", "`n"), [Text.UTF8Encoding]::new($false))
[ordered]@{schema=1;compiler_id=$record.compiler_id;target=$shaderTarget;compiler_inputs=$record.inputs;
    emitter_sha256=(Hash $PSCommandPath);profiles=@($programs | ForEach-Object { $_.proof });
    generated_zig_sha256=(Hash (Join-Path $target 'shaders.zig'))} | ConvertTo-Json -Depth 20 |
    Set-Content -LiteralPath (Join-Path $target 'provenance.json') -Encoding utf8NoBOM
Write-Output "$($programs.Count) verified fixed shaders materialized in $target"
